ལས་ཀ
Esukhia/derge-tengyur-old pull request #101
Opened 2018-11-15 11:16 UTC by Sangkhar

2018-11-15 14:30 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-15 14:30 UTC, rekongrabten commented on derge-tengyur-tags/009_རྒྱུད་འགྲེལ།_ཉ.txt
> +ྱ[304a]
འདིའི་མདུན་ལ་ཡ་བཏགས་ཤིག་ཤོར་འདུག

2018-11-15 14:30 UTC, rekongrabten commented on derge-tengyur-tags/021_རྒྱུད་འགྲེལ།_ཝ.txt
> +[315b.5]པར་འཇུག་པའི་དུས་སུ་གཤེར་པ་ལ་རེག་པ་སྟེ་དེ་ནི་གསོད་བྱེད་མ་དང་ལཱ་མའོ། །དེར་མངོན་པར་ཞེན་པའི་རྣམ་པར་རྟོག་པ་ཟད་པར་བྱེད་པ་མཚན་མ་མེད་པ་དང་། མཆོག་དགའ་དང་། སྙིང་རྗེ་དང་། སྨོན་ལམ་གྱི་རང་བཞིན་དུ་ཤེས་པར་བ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-15 14:30 UTC, rekongrabten commented on derge-tengyur-tags/050_རྒྱུད་འགྲེལ།_ཛི.txt
> +[188b.6]དེ་ནས་སྔགས་ཀྱི་དམ་ཚིག་གི་ཆེད་དུ། མི་གཏོང་བར་ལོའམ་ཟླ་བའི་བར་དུ་སྡོམམ་པ་ཉམས་པ་བླང་ཞིང་བཤགས་ཞེས་སོ། །སོ་སོར་ཐར་པའི་སྡོམ་པ་ལ། །གང་ཞིག་གིས་ནི་ལེགས་གནས་ན། །མཁས་པ་རྣམས་ཀྱིས་དུས་ཀུན་དུ། །སྲོག་གི་ཕྱིར
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-15 14:30 UTC, rekongrabten commented on derge-tengyur-tags/093_ཤེར་ཕྱིན།_ཕ.txt
> +[132a.2]གཉིས་དང་མཚུངས་པར་ལྡན་པ་#འདོད་པ་ལས་དབེན་པའམ། སྒྲིབ་པ་ལས་དབེེན་པ་#སྐྱེས་པའི་ཕྱིར་དབེན་པ་ལས་#སྐྱེས་པའོ། །འདོད་པའི་དོན་རྙེད་ནས་གནས་ངན་ལེན་ཐམས་ཅད་དང་བྲལ་བས་ལུས་དང་སེམས་ཤིན་ཏུ་སྦྱངས་ཏེ། ལས་སུ་རུང་བ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-15 14:30 UTC, rekongrabten commented on derge-tengyur-tags/117_མདོ་སྡེ།_ཉི.txt
> +[15a.2]ནི་བྱང་ཆུབ་ཀྱི་སེམས་ཏེ་སངས་རྒྱས་ཀྱི་ཆོས་རྣམས་ཀྱི་བྱེད་པའོ། །འབྲས་བུ་ནི་ཉན་ཐོས་དང་རང་སངས་རྒྱས་དང་ཡང་དག་པར་རྫོགས་པའི་སངས་རྒྱས་ཉིད་དོ། །དེའི་རང་གི་ངོ་བོ་ཇི་ལྟ་བ་རིག་པ་ནི་སྔོན་གྱི་མཐའ་ཤེས་པའོ། །ཕྱ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-15 14:30 UTC, rekongrabten commented on derge-tengyur-tags/127_སེམས་ཙམ།_ཚི.txt
> +[276a.5]ཉམས་པར་བྱེད་པའི་ཕྱིར། འགྱོད་པ་ལ་སོགས་པས་སེམས་གནས་པའི་བར་དུ་ཐོབ་པར་མི་འགྱུར་བ་ནི་ཞི་གནས་ཀྱི་ཡན་ལག་དང་མི་མཐུན་པ་ཡིན་པར་རིག་པར་བྱའོ། །བརྗེད་(ངས་,ངེས་)པའི་དབང་དུ་བྱས་ནས་རྒོད་པ་དང་། བྱིང་བ་ལ་སོགས་
འདི་རང་འཇགས་འཇོག་རོགས།

2018-11-15 14:30 UTC, rekongrabten commented on derge-tengyur-tags/195_སྒྲ་མདོ།_ལེ.txt
> +[312b.7]གཟུང་བའི་དོན་ཏོ། །ཨིཥུ་ས་ཧ་ལུ་བྷ་རུ་ཥ་རིཥ་རྣམས་ཀྱི་ཏ་ལ་ཡང་ནའོ། །ཨིཥུ་འདོད་པ་ལའོ། །ཥ་ཧ་བཟོད་པ་ལའོ། །ལུ་བྷརྐམ་ཆགས་ལའོ། །རུ་ཥ་རི་ཥ་འཚེ་བ་ལའོ། །འདི་རྣམས་ཀྱི་ཏ་ཡིག་དང་པོ་ལ་ཨིཊ་ཡང་ན་འགྱུར་རོ། །འདོད
འདི་མ་དཔེར་   ལུ་བྷ་རྐམ་ཆགས་  ་ཞེས་གསལ།

2018-11-16 05:21 UTC, Sangkhar commented
བཟོས་ཚར་ཡོད།

2018-11-16 05:21 UTC, closed without merging