ནང་འདྲེན་
Esukhia/derge-tengyur-old pull request #106
Opened 2018-11-16 05:27 UTC by drakpagyamtso

2018-11-19 10:52 UTC, Sangkhar requested changes
འདི་དག་ལ་བསྐྱར་དུ་ལྟ་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/001_བསྟོད་ཚོགས།_ཀ.txt
> +[120a.1]སྔ་མ་ལ་བྲམ་ཟེ་ཡིན་པས་ན་དེ་ནི་དེའི་ང་རྒྱལ་གྱི་བག་ཆགས་སོ། །དེ་བས་ན་སྐྱེ་བོའི་རྩོད་པས་ཆུ་བོ་གངྒཱ་ལ་དམོད་པ་དོར་རོ་ཞེས་བྱ་སྟེ། དེའི་ཕྱིར་ན་དེ་དང་འདྲ་བའི་བག་ཆགས་དང་བཅས་པ་ཞེས་བྱའོ། །དེས་པ་བས་ན་ཉོན་མ
འདི་བཟོ་བཅོས་བྱེད་མི་དགོས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/002_རྒྱུད་འགྲེལ།_ཀ.txt
>  [258a.3]མོའོ། །འཇུག་མ་དང་སུམ་སྐོར་མ་ཞེས་པ་གཉིས་ནི་ཆོམ་རྐུན་མའོ། །མ་མོ་དང་འདོད་མ་ཞེས་པ་གཉིས་ནི་རོ་ལངས་མའོ། །མཚན་མོ་དང་ཁྱེམ་མ་ཞེས་པ་གཉིས་ནི་ཟ་ཕོད་མའོ། །བསིལ་སྦྱིན་མ་དང་གཏུམ་མོ་ཞེས་པ་གཉིས་ནི་མཁའ་སྤྱོད་མ
ཁྱེམ་མ   ཁྱིམ་ཞེས་བཟོ་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/027_རྒྱུད་འགྲེལ།_ལ.txt
> +[288a.5]སྐུ་ཡི་རྗེས་སུ་འཇུག་པར་མཛད། །ལྷ་མོ་ཀུན་དང་མཉམ་ལྡན་པའི། །དེ་ནི་ཁྱབ་བདག་(འཆོད་,འཚེད)པར་བྱེད། །ཕྱག་རྒྱ་ཆེན་པོའི་སྦྱོར་བ་ཡིས། །བཙུན་མོ་ཀུན་ལ་ལོངས་སྤྱོད་མཛོད། །པད་རྩའི་སྐུད་པའི་སྦྱོར་བ་ཡིས། །ཕྲ་མོ
འཆོད་ཞེས་འབྲི་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/042_རྒྱུད་འགྲེལ།_དི.txt
> +[62a.7]བ་འགོས་ལྷས་བཙས་ཀྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ།། {T1861}༄༅༅། །རྒྱ་གར་སྐད་དུ། བྷཊྚཱ་ར་ཀ་ཨཱཪྻ་ཛཾ་བྷ་ལ་ཛ་ལེནྡྲ་སཱ་དྷ་ནཾ། བོད་སྐད་དུ། རྗེ་བཙུན་འཕགས་པ་གནོད་འཛིན་ཆུ་དབང་གི་སྒྲུབ་པའི་ཐབས། སངས་རྒྱ
བཟོ་བཅོས་བྱེད་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/053_རྒྱུད་འགྲེལ།_ཟི.txt
> +[128b.2]དངོས་འགྱུར། །ཤེས་རབ་ཀྱི་ཕྲིན་ཡིག་སློབ་དཔོན་ཆེན་པོ་པདྨ་རྡོ་རྗེས་མཛད་པ་རྫོགས་སོ།། །།པཎྜི་ཏ་ཆེན་པོ་ཤཱནྟ་བྷ་དྲ་དང་། བོད་ཀྱི་ཞུ་ཆེན་གྱི་ལོ་ཙཱ་བ་འགོས་ལྷ་བཙས་ཀྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ།། {T
བཟོ་བཅོས་བྱེད་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/072_རྒྱུད་འགྲེལ།_དུ.txt
> +[243a.7]སུ་འཇུག་པའི་ཆོས་བསྟན་པ་སྣ་ཚོགས་མཉམ་པ་ཉིད་དུ་མཉམ་ཞིང་རྒྱ་ཆེ་ལ་ཟབ་པ་དང་། (སྦོབས་,སྤོབས )པ་དང་། ཆོ་འཕྲུལ་དང་། ལྡན་པ་སངས་རྒྱས་ཀྱི་ཞིང་དུ་མར་དེ་བཞིན་གཤེགས་པ་ལ་མཆོད་པ་ཆེན་པོའི་སྤྲིན་གྱིས་མཆོད་པ་དང་
(སྦོབས་‚སྤོབས་)  འདི་ལྟར་བཟོ་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/074_རྒྱུད་འགྲེལ།_པུ.txt
> +[206b.4]ཐམས་ཅད་ཀྱང་། །ཡིད་ཙམ་ཁྲོས་ནས་གཙོ་ལ་གཟིགས། །སྒོ་མ་མཚམས་ཀྱི་ལྷ་མོ་ནི། །དཀྱིལ་འཁོར་ཀུན་ནས་རབ་ཏུ་གསལ། །ཤར་ལ་སོགས་པའི་ཕྱོགས་རྣམས་དང་། །མེ་ཡི་མཚམས་སུ་གནས་པར་བྱ། །ཐམས་ཅད་པ་ནི་རྫོགས་པ་རུ། །བློ་དང་ལྡན
འདི་བཟོ་བཅོས་བྱེད་དགོས་མི་འདུག  མ་ཡིག་ལ་གསལ་བོ་ལྟ་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/079_རྒྱུད་འགྲེལ།_ཚུ.txt
> +[62b.1]སྤྲང་རྒྱལ་པོ་ཡིན་ཞེས་ཟེར་ཏེ་བརྫུན། །ད་ལྟའི་གང་ཟག་སྔགས་ཀྱི་སྒོར་ཞུགས་པས། །གསང་སྔགས་ཟབ་མོ་ནོར་རྫས་བརྙན་མར་བཙོངས། །འཁོར་བའི་བུ་ཚ་ཕོ་མོ་ཁྱིམ་ཐབ་#བྱེད། །གསང་སྔགས་ཤེས་པས་བདག་ཕུང་སྙིང་རེ་རྗེ། །དེས་ནི
འདི་འཚོང་ཞེས་བཟོ་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/079_རྒྱུད་འགྲེལ།_ཚུ.txt
> +[114a.4]དཔལ་ལྡན་མན་ལུངས་ཀྱི་གཙུག་ལག་ཁང་ཆེན་པོར་པཎྚི་ཏ་གོ་ཏ་མ་བྷ་དྲ་དང་། ལོ་ཙཱ་བ་གྲགས་པ་བྱང་ཆུབ་གཉིས་ཀྱིས་བསྒྱུར་བའོ།། {T3760}/༄༅༅། །རྒྱ་གར་སྐད་དུ། །མཎྜལ་བི་དྷིཿ། བོད་སྐད་དུ། །མཎྜལ་གྱི་ཆོ་ག །བཅོམ་ལྡན་
འདི་ཡང་བཟོ་བཅོས་བྱེད་དགོས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/189_ཚད་མ།_ཝེ.txt
> +<<<<<<< HEAD
འདི་གཙང་མ་བཟོ་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/189_ཚད་མ།_ཝེ.txt
> +>>>>>>> 04beb3235d88fc85c2340e9f2ce3c3c155d9a41b
འདི་ཡང་གཙང་མ་བཟོ་རོགས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
>  [142b.6]གེ་དང་མཐའི་བར་དུ་གནས་པ་རྣམས་དང་རང་ཉིད་ཀྱང་སོ་སོར་བསྡུ་སྟེ། སོ་སོ་བ་ཡང་འཛིན་པར་འགྱུར་རོ་ཞེས་པའི་དོན་ཏོ། །ཨཀ་ནི་འདྲ་བའི་ཡི་གེ་ལ་རིང་པོར་བཤད་དོ། །དཎྜཱ་གྲཾ། ད་དྷཱི་དཾ། མ་དྷཱུཥྞཾ། པ་ཏྲཱི་ཀ་རཿ། མི་
འདི་ལ་ཤད་གཅིག་དཀྱིལ་མ་སླེབས་འདུག

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[142b.5]པར་བྱ་སྟེ། ཨ་ཨི་ཨུཎ། རྀ་ལྀཀ །ཨེ་ཨོང་། ཨཻ་ཨཽ་ཙ། ཧ་ཡ་ཝ་ར་ལཎ། ཉ་མ་ང་ཎ་ནམ། ཛྷ་བྷཉ། གྷ་ཌྷ་དྷཥ། ཛ་བ་གྷ་ཌ་ད་ཤ།། ཁ་ཕ་ཚ་ཋ་ཐ་ཙ་ཊ་ཏ་བ། ཀ་པ་ཡ། ཤ་ཥ་སར། ཧལ། དང་པོ་དང་ཨིཏ་ཀྱི་པར་ཡང་སོ་སོར་བསྡུའོ། །བསྟན་བཅོས
ཛ་བ་གྷ་ཌ་ད་ཤ།།  ཤད་གཅིག་ལྷག་མ་འདུག  གཞན་ཤད་དེ་ཁ་ཡི་མདུན་ལ་འཇོག་དགོས།

2018-11-19 10:52 UTC, Sangkhar commented on derge-tengyur-tags/195_སྒྲ་མདོ།_ལེ.txt
> +[292b.2]ཀྲྀ་བཱ་ས་ཛི་མི་སྭ་དི་སྭ་དྷྱ་རྣམས་ལས་ཨུཎའོ། །བྱུང་བ་ལ། བྷ་སི་ཏ་བྷསྨཱ། ཙ་ར་ཏི་ཙཾརྨཱ། བྷས་གཙོ་བ་ལའོ། །ཙར་འགྲོ་བའི་དོན་ཏོ། །མནའོ། །སྒྲ་མེད་པ་དག་ལའོ་ཞེས་པས་ཨིཊ་མེད་དོ། །འབྱུང་འགྱུར་ལ་ག་མི་ལ་སོགས་པ
འདི་མ་ཡིག་ནང་གཅོ་ཞེས་གསལ་འདུག། ལྟ་རོགས་གནང་།

2018-11-20 05:32 UTC, closed without merging

2018-11-20 05:33 UTC, drakpagyamtso commented
བསྐྱར་བཅོས

2018-11-23 04:57 UTC, drakpagyamtso commented
བསྐྱར་བཟོས་