བསྐྱར་བཟོ 2018.11.20
Esukhia/derge-tengyur-old pull request #115
Opened 2018-11-20 06:18 UTC by gyamtso59

2018-11-20 10:54 UTC, Sangkhar requested changes
བསྐྱར་དུ་བཟོ་རོགས།

2018-11-20 10:54 UTC, Sangkhar commented on derge-tengyur-tags/035_རྒྱུད་འགྲེལ།_ངི.txt
>  [33b.6]ད་ཧ་ན་བཛྲཱ་ཨ་སྭཱ་ཧཱ། ཏིལ་གྱིའོ། །ཨོཾ་བཛྲ་བི་ཛཱ་ཡ་སྭཱ་ཧཱ། སོ་བའིའོ། །ཨོཾ་བཛྲ་མ་ཧཱ་བེ་གཱ་ཡ་སྭཱ་ཧཱ། ནས་ཀྱིའོ། །ཨོཾ་བཛྲ་མ་ཧཱ་བ་ལཱ་ཡ་སྭཱ་ཏཱ། འབྲས་ཀྱིའོ། །ཨོཾ་བཛྲ་གྷ་སྨར་ཡེ་#སྭཱ་ཧཱ། གྲོའིའོ། །ཨོཾ་བཛ
གུག་རྟགས་དང་ཚེག་བསུབ་རོགས།

2018-11-20 10:54 UTC, Sangkhar commented on derge-tengyur-tags/035_རྒྱུད་འགྲེལ།_ངི.txt
> +[34b.2]ཛྭ#ལ་ཧཱུཾ་ཕཊ། ཅེས་སྦར་རོ། །ཨོཾ་བཛྲ་ཨ་ན་#ལ་མ་ཧཱ་བྷཱུཾ་#ཏ་ཛྭ་ལ་ཡ་སརྦྦ་དུཥྚཱན་#ཧཱུཾ་ཕཊ་སྭཱ་ཧཱ། [དྲྀ་]#ཤྱ་ཧོ་ཛཿ་ཧཱུཾ་བཾ་ཧོཿས་མ་ཡ་སྟཾ། ཞེས་པས་དམ་ཚིག་སེམས་དཔའ་ལ་བསྟིམས་ལ་སྤྱི་བོ་ནས་རྐང་པའི་བར་དུ་རྣམ
གུག་རྟགས་བསུབ་རོགས།

2018-11-20 10:54 UTC, Sangkhar commented on derge-tengyur-tags/053_རྒྱུད་འགྲེལ།_ཟི.txt
> +[130b.1]པར་སྨྲ། ཉེ་བར་བྱས་པའི་ལས་བྱེད། །ལེ་ལོ་ཆེ། སྒྲུབ་མི་ཕོད། སྨྲ་བ་ཞན། ཡིད་མི་འཇུག །བརྗེད་པས་ཤེས་བཞིན་དུ་མི་སྤྱོད། ལོག་པར་འཛིན། །དབྲལ་བར་དཀའ། ཡིད་འབྱུང་བར་དཀའ། དམན་པ་ལ་མོས། གླེ་ན་དིག་ལྐུགས། ལག་པས་
གླེན་ཞེས་འབྲི་རོགས།

2018-11-20 10:54 UTC, Sangkhar commented on derge-tengyur-tags/053_རྒྱུད་འགྲེལ།_ཟི.txt
> +[153b.4]ཐུགས་ལ་རྟོག་མི་མངའ། །ཡེ་ཤེས་བདུད་རྩི་དྲི་མ་མེད། །གཟུགས་སོགས་ངོ་བོ་ཉིད་ཀྱིས་ཞི། །ཆོས་དབྱིངས་ཡེ་ཤེས་ངོ་བོར་ལྡན། །མེ་ཏོག་དོན་ལྡན་འདུས་མ་བྱས། །རྡོ་རྗེའི་མིང་དུ་རབ་ཏུ་གྲགས། །འོད་ཟེར་སྒྲ་ལྡན་སེང་གེ
བི་བང་གླིང་བུ་ཅང་ཏེའུ་འཛིན།   འདི་ལྟར་བཟོ་རོགས།

2018-11-20 10:54 UTC, Sangkhar commented on derge-tengyur-tags/131_སེམས་ཙམ།_ཟི.txt
> +<<<<<<< HEAD
འདིའི་headབཟོ་བཅོས་བྱེད་རོགས།

2018-11-20 10:54 UTC, Sangkhar commented on derge-tengyur-tags/131_སེམས་ཙམ།_ཟི.txt
>  [127a.4]པར་གཏན་ལ་དབབ་པ་བསྡུས་པ་#རྫོགས་སོ། ། ། །རྒྱ་གར་གྱི་མཁན་པོ་པོ་པྲ་ཛྙཱ་ཝརྨྨ་དང་། སུ་རེནྡྲ་བོ་དྷི་དང་། ཞུ་ཆེན་གྱི་ལོ་ཙཱ་#བ་བནྡེ་ཡེ་ཤེས་སྡེ་ལ་སོགས་པས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ། །{D131_སེམས།_ཟི
འདིའི་ཤད་དག་ལ་ཞིབ་ཏུ་ལྟ་རོགས།

2018-11-20 10:54 UTC, Sangkhar commented on derge-tengyur-tags/192_ཚད་མ།_འེ.txt
> +[302b.5]བུའི་རྟགས་ལས་སྐྱེས་པའོ། །རྒྱལ་བ་སངས་རྒྱས་སོགས་སྐྱེས་བུ། །ཞེས་བྱ་བ་ལ་སོགས་པ་ལ། མུ་སྟེགས་ཅན་ཞེས་བྱ་བ་ལ་སོགས་པ་སྨོས་ཏེ། ཇི་སྐད་དུ་བཤད་པའི་ཡེ་ཤེས་ཁྱད་པར་དུ་འཕགས་པ་དང་ལྡན་པའི་ཕྱིར་བཅོམ་ལྡན་འདས་བདུ
འདིའི་དོག་རྟགས་ཀྱི་ཚེག་འཇོག་སྟངས་ནོར་འདུག

2018-11-20 10:54 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
>  [3a.6]གྲ་ཧ་ལ་སོགས་པ་ལས་ལྱུ་ནི་དག་གོ། །ཛྙཱ། ཀྲཱྀ། པྲཱི། ཨིཀ་མཐའ་ཉེ་ལས་ཀའོ། །པྲ་ལ་སོགས་པ་རྣམས་ལས་ཨཱཏ་ལས་སོ། །པཱ། གྷྲཱ། དྷྨ། དྷེཊ། དྲི་ཤ་ལས་ཤའོ། །དྷཱ་རི། པཱ་རི།བེ་དི། ཨུ་དེ་ཛི། ཙེ་ཏི། སཱ་ཏི། སཱ་ཧི། བནྡ་
[3a.6] པཱ་རི།བེ་དི།  འདིའི་བར་སྟོང་པ་ཞིག་འཇོག་རོགས།

2018-11-20 10:54 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[53a.6]དག་གི་ཨ་ཙ་ལའོ་ཞེས་པ་རིང་པོ་ཉིད་དོ། ། ཨ་མྲ་ལ་སྔ་མ་ཉིད་དོ། །ཊ་ལའང་ཨཱཔའི་འོ་ཞེས་པ་ཨེ་ཉིད་དོ། །ཨེ་ཙའི་ཨ་ཡ་ཨ་ཝ་ཨཱ་ཡ་ཨཱ་ཝའོ། །ང་ཡིག་ཕྱིས་པ་རྣམས་ལ་ཕ་རོལ་དུ་ཨཱ་པ་ལས་ཡཱཊའོ་ཞེས་པ་ཡཱ་ཊའོ། །ཨེ་ཙ་ལའོ་ཞེས་པ
འདི་ལ་ཡང་སྟོང་པ་ཞིག་འདུག

2018-11-21 07:10 UTC, Sangkhar requested changes

2018-11-21 07:10 UTC, Sangkhar commented on derge-tengyur-tags/015_རྒྱུད་འགྲེལ།_ཕ.txt
>  [123b.5]ལོ་ཞེས་བྱ་ཡིན། །ཡང་ན་ཁརྶ་པཱ་ཎི་ཡིན། །སྐུ་གསུམ་ཕྲིན་ལས་གཉིས་དག་པས། །ཤློཀ་ལྔ་རྣམ་པར་དག །ཟབ་པའི་དོན་ལ་མོས་རྣམས་ལ། །གསང་དོན་མཐར་ཐུག་འདིར་བརྗོད་བྱས། །ཁརྶ་པཱ་ཎི་བཟོད་པར་གསོལ། །དགེ་བ་འགྲོ་ལ་ཡོངས་སུ་
[123b.5]  ཤློཀ་  འདིའི་བར་ལ་ཚེག་ཞིག་དགོས་འདུག

2018-11-21 10:50 UTC, kungagyaltsen requested changes
འདི་རྣམས་བསྐྱར་དུ་བཟོ་རོགས།

2018-11-21 10:50 UTC, kungagyaltsen commented on derge-tengyur-tags/010_རྒྱུད་འགྲེལ།_ཏ.txt
>  [135b.7]ཤེས་རབ་མ་ལ་འཁྱུད་པའོ། །གཡས་ན་གུདྷེ་དང་མཆོད་ཛུཕྱིར་ཐོགས། གཡོན་ན་བུམ་པ་དང་བགྲང་ཕྲེང་ཐོགས་པ་སྐུ་མདོག་དཀར་པོར་བསམས་ལ། ཐུགས་ཀར་སྣ་ཚོགས་པདྨའི་སྟེང་དུ་མེ་གྲུ་གསུམ། ལྕེ་ལ་རེ་དམར་པོ་དྷིབསམ་མོ། །དེ་ལྟར
[135b.7]  1 མཆོད་ཛུཕྱིར་ཐོགས།  འདི་ལ་ཡི་གེ་ལྷག་མ་ཞིག་འདུག། 2 རྂ འདི་ལ་ཞིབ་ཏུ་བལྟ་རོགས།

2018-11-21 10:50 UTC, kungagyaltsen commented on derge-tengyur-tags/010_རྒྱུད་འགྲེལ།_ཏ.txt
> -[136a.2]སེམས་དཔའ་སྤྱན་དྲངས་ཏེ། མདུན་གྱི་ནམ་མཁར་བཞུགས་པ་ལ་བསང་གཏོར་དང་། ཡོན་ཆབ་དང་། ཕྱག་བྱས་ལ། ཨོཾ་ཨསྣ་ཡེ་མ་ཧཱ་ཏེ་ཛཱ་སརྦ་ཀརྨ་སཱ་དྷ་ཀ །ཀཱ་རུ་ཎྱ་ཀྲྀ་ཏྭ་སཏཱརྦཨསྨིནྶནྣི་ཧི་ཏྭ་བྷ་བ། ཞེས་བྱ་བའི་སྔགས་ཀྱིས་སྤ
[136a.2]  ༡  ཨོཾ་ཨསྣ་  དག་ནོར་ཤོར་འདུག།

2018-11-21 10:50 UTC, kungagyaltsen commented on derge-tengyur-tags/010_རྒྱུད་འགྲེལ།_ཏ.txt
>  [136a.3]བྲོཀྵ་ཎི་ལ་སོགས་པ་བྱའོ། །གཟར་བུ་ལ་རང་གི་ལྷའི་ས་བོན་བསམས་ལ། གྲུ་མོ་གཉིས་སྤྲད་ལ་གཟར་བུ་བདུན་དབུལ། སྔགས་ནི། ཨོཾ་ཨསྣ་ཡེ་ཧཱུཾ། ཨོཾ་སརྦ་པཱ་པཾ་ད་ཧ་ན་བཛཱ་ཡ་བཛྲ་སཏྭ་སྱ་སརྦ་པཱ་པཾ་ད་ཧ་ན་སྭཱ་ཧཱ། ཨོཾ་བཛྲ་
[136a.3] ༡ ཨོཾ་ཨསྣ དག་ནོར་ཤོར་འདུག། ༢ བཛཱ་  འདི་ལ་ར་བཏགས་ཞིག་ཆད་འདུག བཟོ་རོགས།

2018-11-21 10:50 UTC, kungagyaltsen commented on derge-tengyur-tags/010_རྒྱུད་འགྲེལ།_ཏ.txt
>  [135b.7]ཤེས་རབ་མ་ལ་འཁྱུད་པའོ། །གཡས་ན་གུདྷེ་དང་མཆོད་ཛུཕྱིར་ཐོགས། གཡོན་ན་བུམ་པ་དང་བགྲང་ཕྲེང་ཐོགས་པ་སྐུ་མདོག་དཀར་པོར་བསམས་ལ། ཐུགས་ཀར་སྣ་ཚོགས་པདྨའི་སྟེང་དུ་མེ་གྲུ་གསུམ། ལྕེ་ལ་རེ་དམར་པོ་དྷིབསམ་མོ། །དེ་ལྟར
[135b.7] ༡ གུདྷེ་ ན་ དེ་ཆད་འདུག། ༢ མཆོད་ཛུཕྱིར་ འདི་ན་ཡི་གེ་ལྷག་མ་ཤོར་འདུག་བསྐྱར་དུ་བཟོ་རོགས་གནང། ༣ ལྕེ་ལ་རེ་ འདིར་ཨ་མ་ནང་ལ་ལྩེ་ལ་རཾ་ཡིན། ༤ དྷིབསམ་མོ། འདི་ལ་ཚིག་ལྷག་མ་ཤོར། བསམ་མོ། ༥ །དེ་ལྟར་༼རྂ་༽ འདི་ལ་རཾ། དེ་རྣམས་ཚང་མ་ཐིག་ཕྲིང་གཅིག་གི་ནང་ལ་ཡོད།

2018-11-21 11:13 UTC, kungagyaltsen requested changes
འདི་རྣམས་བསྐྱར་དུ་བཟོ་རོགས།

2018-11-21 11:13 UTC, kungagyaltsen commented on derge-tengyur-tags/010_རྒྱུད་འགྲེལ།_ཏ.txt
>  [136a.3]བྲོཀྵ་ཎི་ལ་སོགས་པ་བྱའོ། །གཟར་བུ་ལ་རང་གི་ལྷའི་ས་བོན་བསམས་ལ། གྲུ་མོ་གཉིས་སྤྲད་ལ་གཟར་བུ་བདུན་དབུལ། སྔགས་ནི། ཨོཾ་ཨསྣ་ཡེ་ཧཱུཾ། ཨོཾ་སརྦ་པཱ་པཾ་ད་ཧ་ན་བཛཱ་ཡ་བཛྲ་སཏྭ་སྱ་སརྦ་པཱ་པཾ་ད་ཧ་ན་སྭཱ་ཧཱ། ཨོཾ་བཛྲ་
[136a.3] ༡ བྲོཀྵ་ཎི་ལ་ འདིར་དག་ནོར་ཤོར། ཨ་མ་ནང་ལ་ བྲོཀྵ་ཎཾ་ལ་ ཡིན། ༢ བཛྲ་ འདི་ཨ་མ་ནང་ལ་ བཛྲཱ་ ཡིན་ཆད་སོང་བ་ཡིན། ༣ ཨོཾ་སརྦ་སཾ་པ་དེ་སྭཱ་ཧཱ། དག་ནོར་། ཨ་མ་ནང་ལ་ ཨོཾ་སརྦ་སི་པ་དེ་སྭཱ་ཧཱ་ ཡིན། འདི་རྣམས་ཡང་སེ་བཟོ་རོགས།

2018-11-21 11:13 UTC, kungagyaltsen commented on derge-tengyur-tags/010_རྒྱུད་འགྲེལ།_ཏ.txt
>  [136a.4]ཨོཾ་མ་ཧཱ་བེེ་གཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་མ་ཧཱ་བ་ལཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་བཛྲ་གྷསྨ་རི་ཡེ་སྭཱ་ཧཱ། ཨོཾ་བཛྲ་ཨཱ་ཡུ་ཥེ་སྭཱ་ཧཱ།ཨོཾ་བཛྲ་ཨ་པྲ་ཏི་ཧ་ཏ་བཛཱ་ཉཱ་ཡ་སྭཱ་ཧཱརྗོ། ཨོཾ་བཛྲ་བོ་དྷི་ཐྲཀྵུ་ཡ་སྭཱ་ཧཱ། ཨོཾ་པ་ཏ་ལཱ་ཡ་སྭཱ་ཧཱ
[136a.4  ༡ ཨོཾ་མ་ཧཱ་བེེ་གཱ་ཡ་སྭཱ་ཧཱ་ འདི་ལ་ལྷག་མ་ཤོར། ཨ་མ་ནང་ལ་ ཨོཾ་མ་ཧཱ་བེ་གཱ་ཡ་སྭཱ་ཧཱ། འདི་འདྲ་ཡིན། ༢ སྭཱ་ཧཱ།ཨོཾ་ འདི་བར་སྟོང་མེད་ སྭཱ་ཧཱ། ཨོཾ་ འདི་འདྲ་ཡིན། ༣ བཛཱ་ཉཱ་ འདི་ལ་ཆད་སོང་འདུག། བཛཱ་༷ཉྫཱ་ ཨ་མ་ནང་ལ་འདི་ཡིན། ཡང་སེ་བཟོ་རོགས་གནང།

2018-11-22 06:37 UTC, kungagyaltsen requested changes
འདི་རྣམས་བསྐྱར་དུ་བཟོ་རོགས།

2018-11-22 06:37 UTC, kungagyaltsen commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[56a.1]ཥི་ཏཱ། ཡོ་ཥི་དྦྷྱཱཾ། ཡོ་ཥི་དྦྷིཿ། ཡོ་ཥི་ཏེ། ཡོ་ཥི་དྦྷྱཱཾ། ཡོ་ཥི་བྡྷྱཱཿ། ཡོ་ཥི་ཏཿ། ཡོ་ཥི་དྦྷྱཱཾ། ཡོ་ཥི་དྦྷྱཱཾ། ཡོ་ཥི་ཏཿ། ཡོ་ཥི་ཏཿ། ཡོ་ཥི་ཏཱཾ། ཡོ་ཥི་ཏི། ཡོ་ཥི་ཏོཿ། ཡོ་ཥི་ཏྶུ། ཧེ་ཡོ་ཥི་ཏ། ཧེ་ཡོ་ཥ
(སོཞེས་‚སོ་ཞེས་) འདི་ལྟར་དོག་རྟགས་ནང་འཇོག་རོགས།

2018-11-22 06:37 UTC, kungagyaltsen commented on derge-tengyur-tags/035_རྒྱུད་འགྲེལ།_ངི.txt
>  [34b.7]པ་དང་བསྟོད་#པས་མཉེས་པར་བྱས་ལ་མར་#དགང་བླུགས་གསུམ་ཕུལ་ཏེ་སྔགས་འདིས་གཤེགས་སུ་གསོལ་ལོ། །ཨོཾ་[ཀྲྀ]་ཏོ་བ་སརྦྦ་སཏྭ་རྠ། །སིདྡྷི་མ་དཏྟཱ་ཡ་ཐཱ་ནུ་ག །གཙྪ་ཏཱྭབུ་དྡྷ་བི་ཥ་ཡཾ། །པུ་ན་ར་ག་མ་ན་ཡ་ཙྪ་མུཿ།# ཞེས་པའ
དོག་རྟགས་མེད་པར་བཟོ་རོགས།

2018-11-22 06:37 UTC, kungagyaltsen commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
>  [55b.6]རྫོགས་པ་ལའམ། ཁར་ལ་ཛྷ་ལའི་ཙ་རའོ། །རྣམ་པར་གཅད་པའོ། །སཾ་པ་ཏ། །སཾ་པ་ད། སཾ་པ་དཽ། སཾ་པ་དཿ། སཾ་པ་དཾ། སཾ་པ་དཽ། སཾ་པ་དཿ། སཾ་པ་དཱ། སཾ་པ་དྦྷྱཾ། སཾ་པ་དྦྷིཿ། སཾ་པ་དེ། སཾ་པ་དྦྷྱཱཾ། སཾ་པ་དྦྷྱཿ། སཾ་པ་དཿ། སཾ་པ
[55b.6] ཛྷ་ལའི་ འདི་ཚག་ཐིག་མི་དགོས། དཔེར་ན་ ཛྷལའི་ འདི་འདྲ་བཞིན་བཟོ་རོགས།

2018-11-22 06:37 UTC, kungagyaltsen commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[61b.7]ལས་ཨཽཏའི་ཤཱིའོ། །ཨ་ལས་ཨཏ་ཨེངའོ། །དང་པོ་དག་གི་ཨཙ་ལའོ། །ཨམ་ལ་སྔ་མའོ། །ཨཱཔའི་ཊཱ་ལའང་ངོ་། །ཨེཙའི་ཨཡ་ཨཝ་ཨཱཡ་ཨཱཝའོ། །སྨཻ་ལྡན་པའི་སྱཱཊ་ཨཏའང་ངོ་། །ཨེཙ་ལའོ། །ཨཀའི་རིང་པོ་ཨཀ་ལའོ། །ཨ་ལས་ཨཱམའི་སཱམའོ། །ངིའ
[61b.7] ཨཀལ་ འདི་ཚག་ཐིག་ཆད་དགོས་འདུག། དཔེར་ན་ ཨཀ་ལ་ བཞིན་བཟོ་རོགས།

2018-11-23 04:53 UTC, Sangkhar approved these changes

2018-11-23 04:53 UTC, merged