བསྐྱར་བཅོས་
Esukhia/derge-tengyur-old pull request #116
Opened 2018-11-20 06:29 UTC by drakpagyamtso

2018-11-20 06:40 UTC, drakpagyamtso commented
2018/11/20

2018-11-20 07:28 UTC, Sangkhar requested changes
བསྐྱར་དུ་བཟོ་རོགས།

2018-11-20 07:28 UTC, Sangkhar commented on derge-tengyur-tags/001_བསྟོད་ཚོགས།_ཀ.txt
> +[120a.1]སྔ་མ་ལ་བྲམ་ཟེ་ཡིན་པས་ན་དེ་ནི་དེའི་ང་རྒྱལ་གྱི་བག་ཆགས་སོ། །དེ་བས་ན་སྐྱེ་བོའི་རྩོད་པས་ཆུ་བོ་གངྒཱ་ལ་དམོད་པ་དོར་རོ་ཞེས་བྱ་སྟེ། དེའི་ཕྱིར་ན་དེ་དང་འདྲ་བའི་བག་ཆགས་དང་བཅས་པ་ཞེས་བྱའོ། །དེས་པ་བས་ན་ཉོན་མ
དེ་བས་ན་ཉོན་མོངས་པའི་བུད་ཤིང་   འདི་ལྟར་བཟོ་རོགས།

2018-11-20 07:28 UTC, Sangkhar commented on derge-tengyur-tags/074_རྒྱུད་འགྲེལ།_པུ.txt
> +[206b.4]ཐམས་ཅད་ཀྱང་། །ཡིད་ཙམ་ཁྲོས་ནས་གཙོ་ལ་གཟིགས། །སྒོ་མ་མཚམས་ཀྱི་ལྷ་མོ་ནི། །དཀྱིལ་འཁོར་ཀུན་ནས་རབ་ཏུ་གསལ། །ཤར་ལ་སོགས་པའི་ཕྱོགས་རྣམས་དང་། །མེ་ཡི་མཚམས་སུ་གནས་པར་བྱ། །ཐམས་ཅད་པ་ནི་རྫོགས་པ་རུ། །བློ་དང་ལྡན
གཅོ་ལ་བཟོ་རོགས།

2018-11-20 07:28 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
>  [47b.6]པྲྀཀྵེ། པྲྀཀྵ་ཡོཿ། པྲྀཀྵེ་ཥུ། ཧེ་པྲྀཀྵ། ཧེ་པྲྀཀྵ། ཧེ་པྲྀཀྵཽ། ཧེཔྲྀཀྵཿ། བྷྱཱ་གྱྔ། གཛ། བླཀྵ་ལ་སོགས་པ་ཨ་མཐའ་ཅན་གཞན་ལའང་འདི་ལྟར་བལྟ་བར་བྱའོ། ། ཨགྣི་ཞེས་པའི་སུ་ལ་སོགས་པ་ཕྱིས་པ་ལས་ཀྱང་རིམ་པས་སུའི་རུ
[47b.6] འདིའི་ནང་ཤད་དཀྱིལ་ལ་འདུག  བཟོ་རོགས

2018-11-20 07:28 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
>  [142b.6]གེ་དང་མཐའི་བར་དུ་གནས་པ་རྣམས་དང་རང་ཉིད་ཀྱང་སོ་སོར་བསྡུ་སྟེ། སོ་སོ་བ་ཡང་འཛིན་པར་འགྱུར་རོ་ཞེས་པའི་དོན་ཏོ། །ཨཀ་ནི་འདྲ་བའི་ཡི་གེ་ལ་རིང་པོར་བཤད་དོ། །དཎྜཱ་གྲཾ། ད་དྷཱི་དཾ། མ་དྷཱུཥྞཾ། པ་ཏྲཱི་ཀ་རཿ། མི་
[142b.6]  འདིའི་ནང་ལ་ཡང་ཤད་དཀྱིལ་ལ་འདུག

2018-11-20 07:28 UTC, Sangkhar commented on derge-tengyur-tags/196_སྒྲ་མདོ།_ཤེ.txt
> +[84a.3]ཞིང་། རི་ཏྭིག་ཅེས་པ་ལ་སོགས་པས་ཀྭིཔ་སྟེ། ལན་གཉིས་བརྗོད་པ་ཚིག་ཕྲད་དུ་བྱས་ནས། དྲྀ་ཤ་ལ་སོགས་པ་ཉིད་ཀྱི་ཕྱིར་ག་ཉིད་དོ། །ད་དྲྀཀ ། ད་དྲྀག །ད་དྷྲྀ་ཤཽ། དྀ་དྷྲ་ཥཿ། ཞེས་པ་ལ་སོགས་པ་སྟེ། དེ་བཞིན་དུ་བུད་མེད་
ཤད་གཅིག་དཀྱིལ་ལ་འདུག

2018-11-20 07:28 UTC, Sangkhar commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
>  [113a.7]ཀྵི་པཿ སི བྱེད་དུ་འཇུག། ཨཽ་ཀྵིཔཽཿ ཀྵིཔཱཿ ཛས སོགས་དང་། དེ་བཞིན་དུ། བྷིདཿ སི་འཇོམས་པར་བྱེད། ཆིདཿ སི དུ་མ་བུར་བྱེད། སོགས་སོ། །བྱིངས་ཛྙཱ་ཁོངས་སུ་ཆུད་པ་ལ་འང་རྐྱེན་ཀ་འཇུག་པར་བཤད་པས། ཛྷཱཿ སི ཤིས་པར་
[113a.7] ཚི་དཿ སི དུམ་བར་བྱེད། འདི་ལྟར་བཟོ་རོགས།

2018-11-20 07:28 UTC, Sangkhar commented on notes/canon_notes_input/D074_རྒྱུད།_པུ_༡༧༡༤.txt
> +198.ཛུ་ཛུ་རེ་སྭཱ་ཧཱ།  གང་ལ་ལ་ཞིག་དེ་བཞིན་aགཤེགས་པའི་མཚན་རྣམས་དང་། གཟུངས་ཀྱི་ཚིག་འདི་དག་འཆང་བ་དང་། ཀློག་པ་དང་། ཡི་གེར་འབྲི་བ་དང་། ཡི་གེར་འདྲིར་སྩོལ་བ་དང་། རབ་ཏུ་གུས་པར་མཆོད་པ་བགྱིད་པ་དེ་དག་ངན་སོང་གསུམ
འདི་ལ་སྟོང་པ་ཞིག་ཤོར་འདུག

2018-11-20 07:28 UTC, Sangkhar commented on notes/canon_notes_input/D074_རྒྱུད།_པུ_༡༧༡༤.txt
>  201. ། ཚེ་རབས་དྲན་པར་འགྱུར། ཏིང་ངེ་འཛིན་དང་གཟུངས་ཀྱང་ཐོབ་པར་འགྱུར་རོ་ཞེས་གསུངས་ཤིང་ཞལ་གྱིས་བཞེས་པ་དང་། དེ་ནས་བྱང་ཆུབ་སེམས་aདཔའ་ཕྱག་ན་རྡོ་རྗེས་དེ་བཞིན་གཤེགས་པ་དེ་དག་ལ་འདི་སྐད་ཅེས་གང་མདོ་སྡེའི་དབང་པོ་འ
འདི་ལ་ཡང་སྟོང་པ་ཤོར་འདུག

2018-11-20 07:28 UTC, Sangkhar commented on notes/canon_notes_input/D117_མདོ།_ཉི_༠༠༣༡.txt
> +12. ། རྒྱལ་བ་ཀུན་ལ་རབ་ཏུ་ཕྱག་འཚལ་ལོ། །ཞེས་བྱ་བ་ནི་ཉོན་མོངས་པའི་དགྲ་ལས་རྒྱལ་བའི་ཕྱིར་དང་བདུད་ལས་རྒྱལ་བའི་ཕྱིར་ན་སངས་རྒྱས་བཅོམ་ལྡན་འདས་རྣམས་ལ་རྒྱལ་བ་ཞེས་བརྗོད་དེ། ཇི་སྐད་དུ་བཅོམ་ལྡན་འདས་ཀྱིས། སྡིག་པའི་
འདི་ལ་ཡང་སྟོང་པ་འདུག  aཞིག་བསུབ་འདུག

2018-11-20 07:28 UTC, Sangkhar commented on notes/canon_notes_input/D194_སྒྲ།_རེ_༠༠༠༦.txt
>  640. ། དེ་ལྟར། རཛྫུཿ། ར་ཛྫུ
ཤད་བཟོ་རོགས།

2018-11-20 07:28 UTC, Sangkhar commented on notes/canon_notes_input/D194_སྒྲ།_རེ_༠༠༠༦.txt
>  641. ། རཛྫ་ཝཿ། ན་ནཾ་དྲྀ་ཞེས་པ་འདིའི། རྀཏ་
ཤད་འདི་ཡང་བཟོ་རོགས།

2018-11-20 07:28 UTC, Sangkhar commented on notes/canon_notes_input/D194_སྒྲ།_རེ_༠༠༠༦.txt
>  646. ། ན་ནནྡྲྀ་བྷྱཱཾ། ན་ནནྡྲྀ་བྷིཿ། ན་ནནྡྲེ། ན་ནནྡྲྀ་བྷྱཱཾ། ན་ནནྡྲྀ་བྷྱཿ། ན་ནནྡུཿ། ན་ནནྡྲྀ་བྷྱཱཾ
ཤད་འདི་ཡང་།

2018-11-21 06:46 UTC, drakpagyamtso commented
བསྐྱར་བཅོས་2018/11/21

2018-11-21 10:51 UTC, Sangkhar approved these changes

2018-11-21 10:52 UTC, merged