བསྐྱར་བཟོས།2018/11/20
Esukhia/derge-tengyur-old pull request #117
Opened 2018-11-20 06:39 UTC by Sermig

2018-11-20 10:15 UTC, Sangkhar requested changes
འདི་རྣམས་བསྐྱར་དུ་བཟོ་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/009_རྒྱུད་འགྲེལ།_ཉ.txt
>  [71b.5]དང་། །བདུད་རྩི་བཟའ་བ་བསམ་པར་བྱ། །ཨོཾ་ཏྲཻ་ལོ་ཀྱཱ་ཀྵེ་པ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཕཊ་སྭཱ་ཧཱ། །དཔལ་ཧེ་རུ་ཀ་ཕྱག་གཉིས་པའི་སྒྲུབ་ཐབས། སློབ་དཔོན་བཛྲ་ཨ་ལ་ལས་མཛད་པ་རྫོགས་སོ།།{D009_རྒྱུད།_ཉ_༠༠༥༧}༄༅༅། །རྒྱ་གར་སྐད་ད
[71b.5]  རྫོགས་སོ།།{D009_རྒྱུད།_ཉ_༠༠༥༧} འདིའི་བར་སྟོང་པ་ཞིག་འཇོག་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/085_ཤེར་ཕྱིན།_ཆ.txt
> +[65b.1]འདི་ནི་གཉིས་ཏེ་དངོས་པོ་ཐམས་ཅད་དང་རྣམ་པ་ཐམས་ཅད་དོ་ཞེས་བྱ་བའི་ཚུལ་གྱིས་#ན། འདིར་ཐམས་ཅད་ནས་ཞེས་བྱ་བ་ནི་ཕུང་པོ་ལ་སོགས་པ་དངོས་པོའི་རང་བཞིན་གྱིས་སོ། །ཐམས་ཅད་ཅེས་བྱ་བ་ནི་ཕྱི་དང་ནང་གི་བདག་ཉིད་ཅན་གྱི་ད
འདི་ནང་དོག་རྟགས་འཇོག་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/085_ཤེར་ཕྱིན།_ཆ.txt
> +[141b.2]དེ་ལ་དགེ་སློང་ནི་བརྗོད་པ་གསུམ་ལ་སོགས་པས་བསྙན་པར་རྫོགས་པར་བྱས་པའོ། །དགེ་སློང་མ་ཡང་དེ་བཞིན་ནོ། །དགེ་བསྙེན་ནི་སྐྱབས་གསུམ་ཡོངས་སུ་འཛིན་པ་དང་། བསླབ་པའི་གཞི་ལྔ་ཡོངས་སུ་འཛིན་པའོ། །དགེ་བསྙེན་མ་ཡང་དེ་
དོག་རྟགས་ནང་འཇོག་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/085_ཤེར་ཕྱིན།_ཆ.txt
> +[178b.1]འཇིགས་པ་ལ་སོགས་པའི་ཡོན་ཏན་གྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སླད་དུ་ཉེས་པ་མེད་པ་ནི་སྐྱོན་མེད་པ་སྟེ། འདོད་ཆགས་མེད་པ། ཞེ་སྡང་མེད་པ། གཏི་མུག་མེད་པ་ཞེས་བྱ་བའི་དོན་ཏོ། །རབ་ཏུ་སྐྱེ་བ་ནི་ཡོངས་སུ་རྟོག་པ་སྟེ། དེ་ལ
འདི་ཡང་དོག་རྟགས་ནང་འཇོག་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/085_ཤེར་ཕྱིན།_ཆ.txt
> +[248a.5]པས་གདོང་དུ་མི་ལྟ་བའོ#། །ལྷ་གཞན་ལ་མི་རྟེན་ནོ་ཞེས་བྱ་བ་ནི་སྐྱབས་པ་ལ་སོགས་པའི་ངོ་བོར་བདག་གིར་མི་བྱེད་པའོ། །སྨོན་ལམ་གྲུབ་པས་མི་ཁོམ་པ་#བརྒྱད་ཟད་པ་ནི་རབ་འབྱོར་ཡང་ཞེས་བྱ་བ་ལ་སོགས་པ་གསུངས་པ་ཡིན་ཏེ། ང
དོག་རྟགས་མི་དགོས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/085_ཤེར་ཕྱིན།_ཆ.txt
>  [261a.7]ཀྱི་ཚིག་བླ་དགས་མ་ལགས་སམ་ཞེས་བྱའོ། །དེའི་ཚིག་གི་ལན་འདེབས་པར་མཛད་པ་ནི་རབ་འབྱོར་འདི་ཇི་སྙམ་དུ་སེམས་ཞེས་བྱ་བ་ལ་སོགས་པ་གསུངས་པ་ཡིན་ནོ། །ཆོས་ཐམས་ཅད་ཅེས་བྱ་བ་ནི་དང་པོ་ལ་སོགས་པའི་རྣམ་པ་རྣམས་སོ། །སྟོང
འདི་ཡང་དོག་རྟགས་མི་དགོས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/085_ཤེར་ཕྱིན།_ཆ.txt
> +[300a.1]ཐམས་ཅད་ནི་ཞེས་བྱ་བ་ལ་སོགས་པ་གསུངས་པ་ཡིན་ཏ་མག་ལམ་དུ་ཡང་སྣང་བར་ཡང་#མི་འགྱུར་ཏེ་ཞེས་བྱ་བ་ལ་སོགས་པའི་ཚིག་བཞི་ནི་གཟུང་བ་དང་འཛིན་པའི་རྣམ་པར་རྟོག་པ་བཞི་པོ་མཐོང་བའི་ལམ་ན་མི་སྣང་བར་བསྟན་པའི་དོན་དུ་སྨོ
(ཏ་‚ཏེ་)  (མག་‚མིག་)  འདི་གཉིས་དོག་རྟགས་ནང་འཇོག་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/085_ཤེར་ཕྱིན།_ཆ.txt
> +[312b.3]ཕྱིར་དགེ་བ་དང་མི་དགེ་བའི་ཆོས་བསགས་པ་ཚད་མེད་པའི་ཕྱིར་རོ། །ལོག་པར་རྟོགས་པ་བརྒྱད་པའི་དོན་ནི་ཆོས་ཐམས་ཅད་ཅེས་བྱ་བ་ལ་སོགས་པ་གསུངས་པ་ཡིན་ཏེ། གཟུགས་ལ་སོགས་པར་དམིགས་པ་བཀག་པས་དགེ་འདུན་དཀོན་མཆོག་ལ་ལག་པར
དོག་རྟགས་འཇོག་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/086_ཤེར་ཕྱིན།_ཇ.txt
> +[16b.6]སྒྲུབ་པ་ནི་མོས་པས་སྤྱོད་པའི་ས་ཡིན་པར་རྟོགས་པར་བྱའོ། །ཆོགས་ཀྱི་བསྒྲུབ་#པ་ནི་རྩེ་མོ་#དང་སྦྱིན་པ་ལ་སོགས་པ་དྲུག་དང་། ཞི་གནས་དང་། ལྷག་མཐོང་དང་། ཟུང་དུ་འཇུག་པའི་ལམ་དང་། ཐབས་ལ་མཁས་པ་དང་། ཡེ་ཤེས་དང་།
དོག་རྟགས་ནང་འཇོག་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/086_ཤེར་ཕྱིན།_ཇ.txt
> +[44a.6]རང་གི་དོན་ཕུན་སུམ་(ཆགས་,ཚོགས)་པ་ལས་ལྡོག་པ་མེད་པའི་ཕྱིར་མི་ལྡོག་པའོ། །གཞན་གྱི་དོན་ཕུན་སུམ་ཚོགས་པ་ལས་མི་གཡོ་བའི་ཕྱིར་གཡོ་བ་མེད་ཅིང་ངོ་། །གཉི་གའི་དོན་ཕུན་སུམ་ཚོགས་པ་ཇི་ལྟ་བ་#བྱེད་པ་དང་མི་འབྲལ་བའི
དོག་རྟགས་ཀྱི་ཚེག་འཇོག་སྟངས་འགྲིག་མི་འདུག

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/098_དབུ་མ།_ཛ.txt
> +[228b.7]དགའ་བ་ཞེས་བྱའོ། །དེ་བཞིན་དུ་གང་དང་པོ་འབྱུང་བ་ལས་གྱུར་པ་མི་དང་། བྱོལ་སོང་དང་། རི་(དགས་,དྭགས་)དང་། སྦྲུལ་ལ་སོགས་པའི་རྒྱུ་མཚན་ལས་བྱུང་ཞིང་སྐྱེས་པས་འཇིག་#པ་དང་། འཐབ་རྩོད་དང་། རྡེག་པ་ལ་སོགས་པའི་#ས
འདི་ལ་དོག་རྟགས་མི་དགོས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/110_དབུ་མ།_ཀི.txt
> +[137b.1]ཐམས་ཅད་ཀྱི་དོན་གྱི་ཕྱིར་ཕ་ལྟ་བུ་དང་། མ་ལྟ་བུ་དང་། སྤུན་ལྟ་བུ་དང་། གཉེན་ལྟ་བུ་དང་། སྣག་གི་གཉེན་མཚམས་ལྟ་བུར་འགྱུར་བར་བྱང་ཆུབ་ཏུ་སེམས་བསྐྱེད་དོ། །བདག་དེང་ཕྱིན་ཅད་སེམས་ཅན་ཐམས་ཅད་ཀྱི་ཕ་དང་། མ་དང་།
འདི་དོག་རྟགས་ནང་འཇོག་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/118_མདོ་སྡེ།_ཏི.txt
> +[286b.4]པ་དང་། གཉན་པོ་ལ་ལྡེམ་པོར་དགོངས་པ་སྟེ#། བསྒྱུར་བ་ལ་ལྡེམ་པོར་དགོངས་པ་དང་#། རྣམ་པ་བཞི་པོ་འདི་དག་གིས་ཐེག་པ་ཆེན་པོ་ལས་དེ་བཞིན་གཤེགས་པས་ལྡེམ་པོར་གསུངས་པའི་རིགས་པ་ཐམས་ཅད་མདོར་བསྡུས་པ་ཡིན་ནོ། །དེ་ལ་ག
འདི་ཡང་དོག་རྟགས་ནང་འཇོག་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/203_སྣ་ཚོགས།_ངོ.txt
>  [240b.3]དང་། །ན་ལེ་ཤམ་དང་བྱི་དང་ག། །ས་ར་ལ་དང་ཐང་ཤིང་དང་། །སུག་སྨེལ་རུ་རྟ་ཧ་རེ་ཎུ། །བྱ་བྲ་ན་ཁ་ཤ་མ་དང་། །ཧ་ཏི་པི་པི་ལིང་རྩ་བ། །དེ་བཞིན་ཡུངས་ཀར་སེར་པོ་དང་། །པུ་ཙེ་ཤེལ་དང་བོང་བ་དང་། །དེ་བཞིན་དུ་ནི་ག་རུ་ར
[240b.3] །།ཆང་དང་ཏིལ་མར  འདི་ལ་ཤད་གཉིས་བཞག་འདུག  གཅིག་བསུབ་རོགས།

2018-11-20 10:15 UTC, Sangkhar commented on derge-tengyur-tags/209_སྣ་ཚོགས།_ཐོ.txt
>  [362a.4]ཅི་ཡང་མི་འཇུག་སྟེ། གང་གི་ཕྱིར་འདི་ནི་རྐྱེན་ཐམས་ཅད་ལ་ཡང་མཚུངས་སོ། །ཨཱ་ཀྵིཔྟ་སྱཱ་བི་པཱུརྦ་ཀ་ཀརྨ་བཻ་ཀལྦེ་ནཱ་ནུཏྤཏྟིཿ། (འཕེན་པའི་རྐྱེན་སྔོན་དུ་འགྲོ་བ་ལས་ཀྱི་རྣམ་པར་རྟོག་པས་མི་སྐྱེད་དོ། །)གང་གི་ཚེ
འདིའི་མཆན་དེ་འོག་ལ་འཇོག་རོགས།

2018-11-21 06:24 UTC, closed without merging

2018-11-21 09:36 UTC, Sermig commented
ནང་འདྲེན་

2018-11-21 09:40 UTC, Sermig commented
ནང་འདྲེན

2018-11-21 10:25 UTC, Sermig commented on derge-tengyur-tags/085_ཤེར་ཕྱིན།_ཆ.txt
> +[300a.1]ཐམས་ཅད་ནི་ཞེས་བྱ་བ་ལ་སོགས་པ་གསུངས་པ་ཡིན་ཏ་མག་ལམ་དུ་ཡང་སྣང་བར་ཡང་#མི་འགྱུར་ཏེ་ཞེས་བྱ་བ་ལ་སོགས་པའི་ཚིག་བཞི་ནི་གཟུང་བ་དང་འཛིན་པའི་རྣམ་པར་རྟོག་པ་བཞི་པོ་མཐོང་བའི་ལམ་ན་མི་སྣང་བར་བསྟན་པའི་དོན་དུ་སྨོ
ལས་ཚར་ཡིན

2018-11-21 10:28 UTC, Sermig commented
ལདི་དག་བཟོས་ཚར་ཡོད།

2018-11-21 10:29 UTC, Sermig commented on derge-tengyur-tags/209_སྣ་ཚོགས།_ཐོ.txt
>  [362a.4]ཅི་ཡང་མི་འཇུག་སྟེ། གང་གི་ཕྱིར་འདི་ནི་རྐྱེན་ཐམས་ཅད་ལ་ཡང་མཚུངས་སོ། །ཨཱ་ཀྵིཔྟ་སྱཱ་བི་པཱུརྦ་ཀ་ཀརྨ་བཻ་ཀལྦེ་ནཱ་ནུཏྤཏྟིཿ། (འཕེན་པའི་རྐྱེན་སྔོན་དུ་འགྲོ་བ་ལས་ཀྱི་རྣམ་པར་རྟོག་པས་མི་སྐྱེད་དོ། །)གང་གི་ཚེ
བཟོས་ཡོད།

2018-11-21 10:29 UTC, Sermig reviewed
བསྐྱར་བཟོ།

2018-11-23 04:44 UTC, Sermig commented on derge-tengyur-tags/086_ཤེར་ཕྱིན།_ཇ.txt
>  [237a.4]དམིགས་པ་དག་བསྒོམ་#པ་ཡང་མེད་སྒོམ་པ་མེད་པ་ཡང་མ་ཡིན་པ་སྟེ། གཟུགས་ལ་སོགས་པ་ལ་མི་དམིགས་པ་དང་དམིགས་པའོ། །ཕྱིན་ཅི་ལོག་ལ་མངོན་པར་ཞེན་པས་ཞེས་བྱ་བ་ནི་གཟུང་བ་ལ་སོགས་པ་ལ་མངོན་པར་ཞེན་པས་སོ། །དོན་ཇི་ལྟ་བ་བ
ལས་ཀ