དེ་རིང་གི་ལས་ཀ་
Esukhia/derge-tengyur-old pull request #142
Opened 2018-11-27 11:15 UTC by drakpagyamtso

2018-11-27 11:15 UTC, drakpagyamtso commented
ལས་ཀ་

2018-11-27 11:17 UTC, drakpagyamtso commented
གཟའ་མིག་དམར་

2018-11-28 06:34 UTC, Sangkhar requested changes
བསྐྱར་དུ་བཟོ་རོགས།

2018-11-28 06:34 UTC, Sangkhar commented on derge-tengyur-tags/107_དབུ་མ།_ས.txt
>  [131a.2]རྣམས་ཉིད་གླང་པོ་ཆེ་དང་རི་དྭགས་དང་#འདྲ་བས། མུ་སྟེགས་བྱེད་ཀྱི་གླང་པོ་ཆེ་དང་རི་དྭགས་རྣམས་སོ། །དེ་དག་གི་ཚོགས་ནི་ཁྱུའོ་ཞེས་ཚིག་རྣམ་པར་སྦྱར་#རོ། །འདི་ལྟ་སྟེ་ཞེས་བྱ་བ་འདིས་ནི་མུ་སྟེགས་ཅན་འདི་དག་གཟུག
[131a.2]འདིར་རི་དྭགས་ཟེར་བའི་ཡི་གེ་གཉིས་ཡོད་པ་དེའི་ཝ་ཟུར་བསུབ་རོགས་ཞུ།

2018-11-28 06:34 UTC, Sangkhar commented on derge-tengyur-tags/107_དབུ་མ།_ས.txt
>  [131a.4]དང་མཚུངས་པ་སྟེ། བུམ་པ་ལ་སོགས་པའི་ཁོངས་སུ་གཏོགས་པའི་ནམ་མཁའ་གང་ཡིན་པ་དེ་ནི་ཆུང་བས་དེ་རྣམ་པར་བཅད་པས་#ཐམས་ཅད་ལ་ཁྱབ་པའི་ནམ་མཁའ་བསྟན་པའི་ཕྱིར་ཆེན་པོ་ཉིད་བྱེ་བྲག་ཏུ་བྱས་སོ། །གཉུག་མ་ནི་ལྷན་ཅིག་སྐྱེས་
[131a.4]  འདི་ལ་ཡང་ཝ་ཟུར་བསུབ་རོགས།

2018-11-28 10:10 UTC, Sangkhar requested changes
འདི་ལ་ཅིག་ལྟ་རོགས།

2018-11-28 10:10 UTC, Sangkhar commented on derge-tengyur-tags/118_མདོ་སྡེ།_ཏི.txt
> +[264b.5]པ་ཆེན་པོ་བསྡུས་པའི་འགྲེལ་པ་སློབ་དཔོན་དབྱིགས་གཉེན་གྱིས་མཛད་པ་ལས་མིང་ནི་གཞན་གྱི་དབང་གི་ངོ་བོ་ཉིད་དུ་རྟོགས་སོ། །དོན་ནི་ཀུན་དུ་བརྟགས་པའི་ངོ་བོ་ཉིད་དུ་རྟོགས་སོ་ཞེས་བཤད་དེ། དེ་ལས་ཟག་པ་དང་བཅས་པའི་སེ
འདིའི་ཨང་གྲངས་དཀྱིལ་ལ་སླེབས་འདུག གསལ་བོ་ཞིག་ལྟ་རོགས།

2018-11-29 04:23 UTC, Sangkhar requested changes
འདི་གཉིས་བཟོ་རོགས།

2018-11-29 04:23 UTC, Sangkhar commented on derge-tengyur-tags/118_མདོ་སྡེ།_ཏི.txt
> +[36a.2]བསྟན་པས། གཞན་དག་ཡིད་ཆེས་པ་བསྐྱེད་པས་ཡིད་ཆེས་པར་བྱེད་པའི་(གླིང་,གླེང)་གཞི་ཞེས་བྱའོ། །མདོ་ཀུན་ལས་མཐུན་པར་འབྱུང་བའི་ཕྱིར། ཐུན་མོང་གི་གླེང་གཞི་ཞེས་བྱའོ། །འོད་ཟེར་གཏོང་བ་ལ་སོགས་པས་ཡང་དག་པའི་གཞུང་ཉི
དོག་རྟགས་ཀྱི་ཚེག་འཇོག་ས་ནོར་འདུག

2018-11-29 04:23 UTC, Sangkhar commented on derge-tengyur-tags/118_མདོ་སྡེ།_ཏི.txt
> +[264b.5]པ་ཆེན་པོ་བསྡུས་པའི་འགྲེལ་པ་སློབ་དཔོན་དབྱིགས་གཉེན་གྱིས་མཛད་པ་ལས་མིང་ནི་གཞན་གྱི་དབང་གི་ངོ་བོ་ཉིད་དུ་རྟོགས་སོ། །དོན་ནི་ཀུན་དུ་བརྟགས་པའི་ངོ་བོ་ཉིད་དུ་རྟོགས་སོ་ཞེས་བཤད་དེ། དེ་ལས་ཟག་པ་དང་བཅས་པའི་སེ
ཕལ་ཆེར་ཡི་གེ་གཅིག་བསུབ་འདུག

2018-11-29 04:35 UTC, merged