ལས་ཀ 2018/11/29
Esukhia/derge-tengyur-old pull request #148
Opened 2018-11-29 11:05 UTC by Sermig

2018-11-29 12:34 UTC, Sangkhar requested changes
བཟོ་རོགས།

2018-11-29 12:34 UTC, Sangkhar commented on derge-tengyur-tags/128_སེམས་ཙམ།_ཛི.txt
> +[121b.2]གསུངས་པའི་ཆོས་འདུལ་བའི་ཕྱོགས་ལ་ཀུན་དུ་སྦྱོར་བ་གསུམ་སྤངས་པའི་ཕྱིར་རྣམ་པར་གཞག་སྟེ། དེ་ལ་ཁྱིམ་པའི་ཕྱོགས་ལ་ནི་འཇིག་ཚོགས་ལ་ལྟ་བ་སྟེ། དེས་དེ་དང་པོ་ཉིད་ནས་བརྩོན་པར་མི་བྱེད་པས་#(འཇིག་ཆོགས་‚འཇིག་ཚོགས་
(ཆོགས་‚ཚོགས་)  འདི་ལྟར་དོག་རྟགས་འཇོག་རོགས།

2018-11-29 12:34 UTC, Sangkhar commented on derge-tengyur-tags/129_སེམས་ཙམ།_ཝི.txt
> +[22b.2]ལ། འཁོར་བ་དེ་ལས་ཀྱང་མི་རྟག་པ་ལ་སོགས་པའི་རྣམ་པ་དག་གིས་ཡིད་སྐྱོ་བར་མི་བྱེད་དོ། །གལ་ཏེ་འཁོར་བ་ལ་ཡང་དག་པ་#ཇི་ལྟ་བ་བཞིན་དུ་ཡོངས་(སུམ་‚སུ་མ)ཤེས་ན་ནི། །འདོད་ཆགས་དང་། ཞེ་སྡང་དང་། གཏི་མུག་ལ་སོགས་པ་ཀུན་
དོག་རྟགས་ནང་ཚེག་གཅིག་ཆད་འདུག

2018-11-29 12:34 UTC, Sangkhar commented on derge-tengyur-tags/134_སེམས་ཙམ།_རི.txt
> +[353a.3]འདི་ལ་མདོ་སྡེ་པ་རྣམས་ཀྱི་ལྟ་བ་ནི་གཟུགས་ཀྱི་འདོད་པ་དང་བྲལ་བ་གཟུགས་ཅན་གྱི་ཁམས་སུ་འཆི་བ་ལ་གང་གིས་ན་གཟུགས་མེད་པའི་ཁམས་ན་སྤྱོད་པའི་སྲིད་པར་ཉིང་(མཚང་ས་‚མཚམས)སྦྱོར་བར་འགྱུར་བ་འཆི་བའི་སེམས་ཐ་མ་གཟུགས་
དོག་རྟགས་ནང་ཚེག་ཆད་འདུག

2018-11-29 12:34 UTC, Sangkhar commented on derge-tengyur-tags/160_འདུལ་བ།_ཞུ.txt
>  [29b.1]བ་ཡིན་ཏེ། དེ་བས་ན་བྱིན་གྱིས་བརླབ་པ་གཞན་ལ་བྱ་བར་རིགས་པ་ཡིན་ནོ། །ངག་གིས་བྱིན་གྱིས་བརླབ་པ་ཤིན་ཏུ་བདེ་བ་ཉིད་ཀྱི་ཕྱིར་རོ། །གནང་བ་འདི་ཉིད་ལས་ནི་འདིས་ཡང་དག་པར་བླངས་པ་འདི་ལས་ཉམས་པར་འགྱུར་བ་མ་ཡིན་ཞེས་བ
[29b.1]  འདིར་དོག་རྟགས་བཟོ་ཡ་ཞིག་ལྷག་འདུག

2018-11-29 12:34 UTC, Sangkhar commented on derge-tengyur-tags/160_འདུལ་བ།_ཞུ.txt
> +[277b.7]གྱིའོ་ཞེས་བྱ་བར་རིག་པར་བྱའོ། །དགེ་འདུན་གྱི་དོན་དུ་འདི་ལ་ལོག་པར་རྟོགས་པ་ལ་བསྒྲུབ་པར་གྱུར་པ་ཉིད་ཅེས་བྱ་བ་འདི་ལ་ཡང་དགེ་འདུན་དག་གི་ཞེས་བྱ་བས་ཤེས་པའོ། །གང་གི་ཆད་ལས་ལྷག་པར་བྱེད་དམ་བྱེད་དུ་འཇུག་པ་ལ་
འདི་དོག་རྟགས་ནང་འཇོག་རོགས

2018-11-29 12:34 UTC, Sangkhar commented on derge-tengyur-tags/160_འདུལ་བ།_ཞུ.txt
> +[278a.3]ཡིན་པ་གང་གིས་བྱེད་དམ་བྱེད་དུ་བཅུག་པ་ལ་ལྟུང་བྱེད་ཡིན་ཞེ་ན། དེའི་ཕྱིར་དེ་དག་གི་ཆད་ནི་བུ་གར་གཞུག་པའི་ཕྱོགས་མ་གཏོགས་པར་ཁྲུ་གང་ངོ་ཞེས་བྱ་བ་སྨོས་ཏེ། བུ་གར་གཞུག་པ་ཞེས་བྱ་བའི་ཕྱོགས་དག་མ་གཏོགས་པར་ལྷག་
འདི་ཡང་དོག་རྟགས་ནང་འཇོག་རོགས།

2018-12-01 04:32 UTC, kungagyaltsen requested changes

2018-12-01 04:32 UTC, kungagyaltsen commented on derge-tengyur-tags/128_སེམས་ཙམ།_ཛི.txt
> +[121b.2]གསུངས་པའི་ཆོས་འདུལ་བའི་ཕྱོགས་ལ་ཀུན་དུ་སྦྱོར་བ་གསུམ་སྤངས་པའི་ཕྱིར་རྣམ་པར་གཞག་སྟེ། དེ་ལ་ཁྱིམ་པའི་ཕྱོགས་ལ་ནི་འཇིག་ཚོགས་ལ་ལྟ་བ་སྟེ། དེས་དེ་དང་པོ་ཉིད་ནས་བརྩོན་པར་མི་བྱེད་པས་#འཇིག་(ཆོགས་‚ཚོགས་)ལ་ལྟ
[121b.2] (འཇིག་ཆོགས) ཨ་མ་སེར་པོ་ལྟར་དུ་བཟོ་རོགས།

2018-12-01 04:32 UTC, kungagyaltsen commented on derge-tengyur-tags/129_སེམས་ཙམ།_ཝི.txt
> +[22b.2]ལ། འཁོར་བ་དེ་ལས་ཀྱང་མི་རྟག་པ་ལ་སོགས་པའི་རྣམ་པ་དག་གིས་ཡིད་སྐྱོ་བར་མི་བྱེད་དོ། །གལ་ཏེ་འཁོར་བ་ལ་ཡང་དག་པ་#ཇི་ལྟ་བ་བཞིན་དུ་ཡོངས་(སུམ་‚སུ་མ་)ཤེས་ན་ནི། །འདོད་ཆགས་དང་། ཞེ་སྡང་དང་། གཏི་མུག་ལ་སོགས་པ་ཀུན
[22b.2]  ཡོངས་(སུམ་‚སུ་མ)ཤེས་ན་ནི ཨ་མ་སེར་པོ་ནང་ནས་ ཡོངས་སུ་མ་ཤེས་ན་ནི། བཞིན་བཟོ་རོགས།

2018-12-01 05:24 UTC, Sangkhar approved these changes

2018-12-01 05:26 UTC, merged