2018-11-30
Esukhia/derge-tengyur-old pull request #153
Opened 2018-11-30 09:45 UTC by tseringwa

2018-11-30 11:04 UTC, Sangkhar requested changes
བསྐྱར་བཟོ་བྱེད་རོགས།

2018-11-30 11:04 UTC, Sangkhar commented on derge-tengyur-tags/005_རྒྱུད་འགྲེལ།_ང.txt
> +[113a.5]གཞུག །རིག་མ་ཞེས་པ་ནི་ཤེས་རབ་བཙུན་མོའོ། །དེ་ནི་དཀྱིལ་འཁོརདུ་གཞུག་པར་བྱའོ། །བཟང་མོ་ནི་ལྷའི་རྣལ་འབྱོར་དང་ལྡན་པའོ། །རིགས་ལྔ་ལས་བྱུང་ནི་རྡོ་རྗེའི་རིགས་ལ་སོགས་པའི་རིགས་ལྔ་ལས་སྐྱེས་སོ། །ཡང་ན་རིགས་པ་
ཚེག་ཞིག་ཆད་འདུག

2018-11-30 11:04 UTC, Sangkhar commented on derge-tengyur-tags/005_རྒྱུད་འགྲེལ།_ང.txt
> +[309b.1]འདོད་ཆགས་བྲལ་བ་འབྱུང་ནི་བཙུན་མོ་ནང་ནས་འབྱུང་བའི་བར་དུ་བྱུང་བའོ། །མངལ་གྱི་ཁྲུ་མ་ཆོས་གོས་ཀྱི་གཙོ་བོ་ཙི་བ་རའོ། །དེ་བཞིན་མ་མཁན་པོ་ཉིད་ནི་མཁན་པོ་ལྟ་བུ་སྟེ་དེ་ལ་ནོད་པའོ། །མགོ་བོ་ཐལ་མོ་སྦྱར་བ་ནི་སྐྱ
(ནི)   ཡི་གེ་གཅིག་བསུབ་འདུག

2018-11-30 11:04 UTC, Sangkhar commented on derge-tengyur-tags/009_རྒྱུད་འགྲེལ།_ཉ.txt
> +[213b.4]བྷཱུ་ཏ། བ[ཏྣི]་བ་ཨུ། རཱཀྵ་ཙནྡ། སྲུ་ཛྫ། མཱ་ད་བྦ། ཏ་ལེ་པཱ་ཏཱ་ལ། ཨཥྚ་སབྦ། ཨི་དཾ། བ་ལི། བྷཱཾ་ཛ། ཛི་གྷ། པུཥྤ། དྷཱུ་པ། རྨཱ་ས། ཛི་གྷ། སཾ་བྷ་སཔྤ། ཀཛྫ་སཱ་དྷ། ཁནྟི་ཁུ་ནི་ཕེ་ཌ་གཱ་ད། ཨོཾ་ཨ་ཀཱ་རོ་མུ་ཁཾ་སར
[213b.4] (བ་ལི། བྷཱཾ་ཛ། ཛི་གྷ། རྨཱ་ས། ཛི་གྷ སཾ་བྷ་སཔྤ།)    བ་ལིཾ། བྷུཾ་ཛ། ཛིཾ་གྷ། མཱཾ་ས། པིཾ་གྷ། ཨཾ་བྷ་སཔྤ། འདི་ཚོ་འདི་ལྟར་བཟོ་རོགས།  ཤོག་ངོས་འདིའི་སྔགས་ཡིག་ཚོར་ཞིབ་ལྟ་རེ་བྱེད་རོགས།

2018-11-30 11:04 UTC, Sangkhar commented on derge-tengyur-tags/010_རྒྱུད་འགྲེལ།_ཏ.txt
>  [136a.4]ཨོཾ་མ་ཧཱ་བེེ་གཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་མ་ཧཱ་བ་ལཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་བཛྲ་གྷསྨ་རི་ཡེ་སྭཱ་ཧཱ། ཨོཾ་བཛྲ་ཨཱ་ཡུ་ཥེ་སྭཱ་ཧཱ།ཨོཾ་བཛྲ་ཨ་པྲ་ཏི་ཧ་ཏ་བཛཱ་ཉཱ་ཡ་སྭཱ་ཧཱརྗོ། ཨོཾ་བཛྲ་བོ་དྷི་ཐྲཀྵུ་ཡ་སྭཱ་ཧཱ། ཨོཾ་པ་ཏ་ལཱ་ཡ་སྭཱ་ཧཱ
[136a.4] སྭཱ་ཧཱ།ཨོཾ་བཛྲ  འདིའི་བར་ལ་སྟོང་པ་ཞིག་འཇོག་རོགས།

2018-11-30 11:04 UTC, Sangkhar commented on derge-tengyur-tags/203_སྣ་ཚོགས།_ངོ.txt
>  [92a.1]{D4323}༄༅༅།། ཚེའི་གནས་སྐབས་ཀྱི་འབྲས་བུ་གནོད་པ་འབྱུང་བ་ཞེས་བྱ་བའི་ལས་བཞུགས་སོ།། །། ༄༅།།འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །གཟའི་གནོད་པ་སྤང་བའོ། །ཉི་མ་ལ་མེ་ལྟར་མཆོད་པར་བྱའོ། །ཟླ་བ་ལ་ཀླུ་མཆོད་པར་བྱའོ།
[92a.1]  འདིའི་དབུ་མཁྱུད་དང་པོ་ཕྱེད་ཀ་བ་(༄)ཡིན། དབུ་མཁྱུད་གཉིས་པའི་སྔོན་གྱི་བཞི་ཤད་དེ་གཉིས་ཤད་བཟོ་རོགས།

2018-12-01 04:49 UTC, kungagyaltsen approved these changes

2018-12-01 04:49 UTC, merged