གཟའ་པ་སང་གི་ལས་ཀ་2018.11.30
Esukhia/derge-tengyur-old pull request #157
Opened 2018-11-30 11:21 UTC by drakpagyamtso

2018-11-30 11:49 UTC, Sangkhar requested changes
བསྐྱར་དུ་བཟོ་རོགས།

2018-11-30 11:49 UTC, Sangkhar commented on derge-tengyur-tags/035_རྒྱུད་འགྲེལ།_ངི.txt
>  [16b.1]དང་། མེ་ཏོག་ལ་སོགས་པའི་མཆོད་པ་ལྔས་མཆོད་དེ། ཁ་ཟས་སྦྱར་#བའི་ཏིང་ངེ་འཛིན་གྱིས་གཏོར་མ་བྱིན་གྱིས་བརླབས་ཏེ#། ཨོཾ་ཨིནྡྲཱ་ཡ་#སྭཱ་ཧཱ། ཨོཾ་ཡ་མཱ་ཡ་#སྭཱ་ཧཱ། ཨོཾ་བ་རུ་ཎཱ་ཡ་#སྭཱ་ཧཱ། ཨོཾ་ཀུ་བེ་རཱ་ཡ་#སྭཱ་ཧཱ།
བཀུག་རྟགས་བསུབ་རོགས།

2018-11-30 11:49 UTC, Sangkhar commented on derge-tengyur-tags/035_རྒྱུད་འགྲེལ།_ངི.txt
> +[16b.2]བཱ་#ཡ་བེ་སྭ་ཧཱ། ཨོཾ་ཨཱི་ཤཱ་ནཱ་ཡ་#སྭཱ་ཧཱ། ཨོཾ་སཱུརྱཱ་ཡ་#སྭཱ་ཧཱ། ཨོཾ་ཙནྡྲ་དི་ཏ་ཡ་#སྭཱ་ཧཱ། ཨོཾ་[པྲྀ]་ཐི་བྱེ་#སྭཱ་ཧཱ། ཞེས་པས་གཏོར་མ་དབུལ་ལོ། །ཨོཾ་ཨ་ཀཱ་རོ་མུ་ཁཾ་སརྦ་དྷརྨཱ་ཎཱཾ་ཨཱདྱ་ནུཏྤ་ནྣ་མ་ཏྭཱ་ཏ་#
འདི་ཡང་བཀུག་རྟགས་བསུབ་རོགས།

2018-11-30 11:49 UTC, Sangkhar commented on derge-tengyur-tags/120_མདོ་སྡེ།_དི.txt
> +[181a.6]པ་མ་ཡིན་ནོ་སྙམ་པའི་དོགས་#པ་བསལ་བའི་ཕྱིར་དེ་བཞིན་གཤེགས་པ་རྣམས་ནི་ཚེ་མཐའ་ཡས་པ་སྟེ། དེའི་འོག་ཏུ་དེ་བཞིན་གཤེགས་པའི་སྐུ་ཚེའི་ཚད་ཀྱི་ལེའུ་བཞག་གོ། །དེ་བཞིན་གཤེགས་པའི་སྤྲུལ་པའི་སྐུའི་ཚེ་ཚད་དེ་(ལྟན་,ལ
དོག་རྟགས་ནང་ཚེག་ཞིག་ཆད་འདུག

2018-12-03 03:56 UTC, drakpagyamtso commented
བསྐྱར་བཟོས་

2018-12-03 04:01 UTC, drakpagyamtso commented
བསྐྱར་བཟོས་2018/12/3

2018-12-03 04:47 UTC, Sangkhar approved these changes

2018-12-03 05:15 UTC, Sangkhar approved these changes

2018-12-03 05:15 UTC, merged