Merge pull request #1 from Esukhia/master
Esukhia/derge-tengyur-old pull request #17
Opened 2018-09-03 03:52 UTC by Sermig

Merge with Esukhia master

2018-09-03 11:31 UTC, Sermig commented
སྒྲ་མདོ་རེ་ཡི་སྒང་ན་པར་སྟོང་ཆེན་པོ་ཞིག སྒྲ་མདོ་རེ་ཡི་ཆོས་ཚན་འདི་རྙེད་མ་སོང་། {T4281} - མདོ་འགྲེལ་༼སྒྲ་མདོ༽ རེ 231a-278a
འཇམ་དཔལ་གྱི་སྒྲ་བརྡ་སྤྲོད་པའི་སྐབས་ལྔ་པའི་རྐང་པ་གཉིས་པའི་

2018-09-03 12:32 UTC, rekongrabten commented
ང་ལ་གང་ཡང་འབྱོར་མི་འདུག

2018-09-03 12:43 UTC, rekongrabten commented
སྒྲ་མདོའི་ཆོས་ཚན་དེ་༢༣༡ན དབུ་ཁྱུད་ཡོད་པ་དེ་རང་རེད།

2018-09-04 07:49 UTC, ngawangtrinley requested changes
ད་དུང་འདུག

2018-09-04 07:49 UTC, ngawangtrinley commented on derge-tengyur-tags/110_དབུ་མ།_ཀི.txt
> +[8b]་པ། བསམ་པ་དང་བརྗོད་པ་ཐམས་ཅད་ཀྱི་ཡུལ་ལས་འདས་པ། མྱ་ངན་ལས་འདས་པ་ནི་བླང་དུ་མེད། འཁོར་བ་ནི་སྤང་དུ་མེད་དེ་
འོ།

2018-09-04 07:49 UTC, ngawangtrinley commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[231a.5]བའོ། །༄༅༅། །ཨོཾ་བཅོམ་ལྡན་འདས་འཇམ་པའི་དབྱངས་ལ་ཕྱག་འཚལ་ལོ། །ངས་ལས་བུ་རྒྱུད་ལའོ། །ན་བ་ཏནྟི་སྔོན་མ་ནི་འདི་ལས་ཞེས་པ་བུ་རྒྱུད་དེ། དེ་ལ་མངོན་པར་བརྗོད་པའི་བུ་རྒྱུད་དེ་ལས་དྲུག་པའི་མཐའ་ལས་ཨཎ་འགྱུར་ཏེ།
ཨང་མི་འདུག་གམ།

2018-09-04 07:49 UTC, ngawangtrinley commented on derge-tengyur-tags/099_དབུ་མ།_ཝ.txt
> +
འདི་བསྣན་མི་དགོས།

2018-09-04 10:43 UTC, rekongrabten commented on derge-tengyur-tags/110_དབུ་མ།_ཀི.txt
> +[8b]་པ། བསམ་པ་དང་བརྗོད་པ་ཐམས་ཅད་ཀྱི་ཡུལ་ལས་འདས་པ། མྱ་ངན་ལས་འདས་པ་ནི་བླང་དུ་མེད། འཁོར་བ་ནི་སྤང་དུ་མེད་དེ་
འདི་ཚོ་བདེ་སྤྱོད་ཡོད་ནི་མ་རེད། དབུ་མ་བཟོ་མཁན་གཞན་ཡོད་རེད།

2018-09-05 04:19 UTC, merged