ལས་བྱ2018/12/3
Esukhia/derge-tengyur-old pull request #171
Opened 2018-12-03 11:15 UTC by Sermig

2018-12-03 11:55 UTC, Sangkhar requested changes
བསྐྱར་ཏུ་བཟོ་རོགས།

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/084_ཤེར་ཕྱིན།_ཅ.txt
> +[323b.7]བཅོམ་ལྡན་འདས་(གྱིས་‚ཀྱིས)་#ཚེ་དང་ལྡན་པ་རབ་འབྱོར་ལ་འདི་སྐད་ཅེས་བཀའ་སྩལ་ཏོ། །རབ་འབྱོར་དེ་དེ་བཞིན་ནོ། །དེ་དེ་བཞིན་ཏེ། ཇི་སྐད་སྨྲས་པ་དེ་བཞིན་ཏེ། རབ་འབྱོར་དངོས་པོ་མེད་པ་ལ་ནི་ལས་ཀྱང་མེད། བྱ་བ་ཡང་མེ
དོག་རྟགས་ཀྱི་ཚེག་འགྲིག་མི་འདུག

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/118_མདོ་སྡེ།_ཏི.txt
> +[183b.5]ལས་སྐྱེ་བར་བཤད་དེ། དེའི་ཕྱིར་དེ་ཉིད་ལས་འདིའི་(ཕྱེ་,བྱེ)་བྲག་ཀྱང་རྣམ་པ་བདུན་ནམ་རྣམ་པ་དགུ་ཡོད་དེ་ཕྱོགས་རྣམ་པ་གསུམ་དང་བདག་དང་ཡོན་ཏན་གྱི་གནས་ལས་སྐྱེས་པའོ་ཞེས་བཤད་དེ། དེ་ལ་རེ་ཞིག་ང་རྒྱལ་རྣམ་པ་བདུན
ཚེག་འགྲིག་པ་དེ་ནོར་བ་བཟོས་འདུག

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/123_སེམས་ཙམ།_ཕི.txt
> +[141b.1]དབྱངས་སྙན་པ་ལྟ་བུ་སྟེ། གདུལ་བྱ་འདུལ་བར་#བྱེད་(བའི‚་པའི་)ཆོས་སྟོན་པའི་ཕྱིར་རོ། །རྟོན་པ་དང་ལྡན་པ་ནི་རྒྱལ་པོ་ལྟ་བུ་སྟེ། ཆུད་མི་ཟ་བའི་རྒྱུ་ཡིན་པའི་ཕྱིར་རོ། །བསོད་ནམས་དང་ཡེ་ཤེས་ཀྱི་ཚོགས་དང་ལྡན་པ་ན
འདིའི་ཚེག་འགྲིག་མི་འདུག

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/123_སེམས་ཙམ།_ཕི.txt
> +[142a.4]འཕེལ་བར་བྱེད་པས་རྟག་ཏུ་དགེ་བ་དང་ལྡན་(བ‚་པ)དང་། སྙིང་བརྩེ་བ་དང་ལྡན་པར་ཡང་འགྱུར་ཏེ། དེས་ན་དེ་དགེ་བ་དང་ལྡན་པའི་ཕྱིར། བདེ་བས་ཀྱང་དགའ་ལ་སྙིང་བརྩེ་བ་དང་ལྡན་པའི་ཕྱིར་གཞན་གྱི་དོན་བྱེད་པའི་རྒྱུ་མཚན་ཅན
ཚེག་འགྲིག་མི་འདུག

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/127_སེམས་ཙམ།_ཚི.txt
> +[11a.3]ལ་སོགས་པ་དག་ཏུ་སྐྱེ་བ་ཡང་དེ་དང་འདྲ་བར་བལྟ་བར་བྱའོ། །དུད་འགྲོ་དང་། ཡི་དགསདང་། མི་དང་། འདོད་པ་ན་སྤྱོད་པ་དང་། གཟུགས་ན་སྤྱོད་པའི་ལྷའི་རིས་གཞན་དག་ཏུ་སྐྱེ་ན་ནི། སྐྱེ་བའི་#གནས་སུ་བདག་དང་སྐལ་བ་མཉམ་པ་མ
འདིར་ཚེག་ཆད་འདུག

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/127_སེམས་ཙམ།_ཚི.txt
> +[14a.4]འདོད་#པའི་གནས་སྐབས་དེ་ནི་མས་ཁ་ཟས་ཟོས་པ་ལས་འབྱུང་#བའི་(དངས་‚དྭངས་)མ་སྐ་བ་དེས་དེ་བརྟས་#པར་འགྱུར་རོ། །མེར་མེར་པོ་ལ་སོགས་པ་ཤིན་ཏུ་སླ་བའི་དུས་ན་ནི། (དངས་‚དྭངས་)མ་ཤིན་ཏུ་སླ་བས་བརྟས་#པར་འགྱུར་བར་རིག་
འདི་གཉིས་ལ་ཕལ་ཆེར་དོག་རྟགས་མེད་ན་འགྲིག

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/159_འདུལ་བ།_ཝུ.txt
> +[162a.3]བའི་རྣམ་པ་དེ་ཉིད་ལ་ནན་གྱིས་མཆོག་ཏུ་བཟུང་ཞིང་མངོན་པར་ཞེན་ནས་འདི་ཉིད་བདེན་གྱི་གཞན་ནི་བརྫུན་པའོ་ཞེས་རྗེས་སུ་ཐ་སྙད་འདོགས་ཏེ། དེའི་སླད་དུ་དགེ་འདུན་གྱིས་དགེ་སློང་འཆི་ལྟས་ལ། འཆི་ལྟས་ཁྱོད་ཇི་ལྟར་བཅོམ
ཚེག་དོག་རྟགས་ནང་འཇོག་རོགས།

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/161_འདུལ་བ།_ཟུ.txt
> +[48a.7]བཅོམ་ལྡན་འདས་(གྱིས་‚ཀྱིས)་བཀའ་སྩལ་པ། དེ་ལྟ་བས་ན་དགེ་སློང་མས་དགེ་སློང་ལ་མི་གཙང་བས་མ་རུངས་པར་མི་བྱའོ། །བྱེད་ན་འགལ་ཚབས་ཅན་དུ་འགྱུར་རོ་ཞེས་གསུངས་པ་ཡིན་ནོ། །བཤང་བ་ལས་གྱུར་པའི་ལྟུང་བྱེད་གསུམ་མོ། །ལྟ
འདི་ཡང་ཚེག་དོག་རྟགས་ནང་འཇོག་དགོས།

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/162_འདུལ་བ།_འུ.txt
> +[362a.6]ནི་དེ་ནས་ཁྱིམ་བདག་མགོན་མེད་ཟས་སྦྱིན་གྱིས་ཐོས་ནས་རིན་པོ་ཆེ་སྣ་བཞི་ལས་བྱས་པའི་སེང་གེའི་ཁྲི་བཤམས་པ་དག །དགེ་སློང་དག་དེ་ལ་མི་འཁོད་ནས། བཅོམ་ལྡན་འདས་(གྱིས་‚ཀྱིས)་བཀའ་སྩལ་པ། འདུ་བྱེད་ཐམས་ཅད་མི་རྟག་གོ
འདི་ཡང་གཅིག་པ་རེད།

2018-12-03 11:55 UTC, Sangkhar commented on derge-tengyur-tags/167_འདུལ་བ།_སུ.txt
> +[21b.3]ཀུན་དགའ་བོ་ལ་སོགས་པ་རྣམས་ཀྱིས་སྨྲས་སོ། །དེ་ལྟར་གྱུར་པ་བཅོམ་ལྡན་འདས་ཀྱིས་གསན་ཏོ། །དེ་ནས་བཅོམ་ལྡན་འདས་(གྱིས་‚ཀྱིས)་#རྣམ་པ་དུ་མས་སྨད་ནས་འདུལ་བ་ལ་#བསླབ་པའི་གནས་བཅས་སོ། །ལྷ་དག་མཐོང་ཞེས་དེ་ཡི་སྒྲ། །
འདི་ཡང་།

2018-12-04 04:20 UTC, kungagyaltsen approved these changes

2018-12-04 04:21 UTC, merged