ལས་ཀ 2018/12/4
Esukhia/derge-tengyur-old pull request #177
Opened 2018-12-04 11:11 UTC by Sermig

2018-12-04 12:05 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-04 12:05 UTC, Sangkhar commented on derge-tengyur-tags/127_སེམས་ཙམ།_ཚི.txt
> +[282b.3]དབྱིངས་ལ་ཡང་ཉེ་བར་ཞི་བ་རྣམ་པ་བཞི་པོ་རྣམ་གྲངས་སུ་འགྲོ་བའི་ཉེ་བར་ཞི་བ་དང་། ཕུང་པོ་ཐམས་ཅད་ཉེ་བར་ཞི་བ་དང་། ཕུང་པོ་ལ་བརྟེན་#པའི་སྡུག་བསྔལ་ཉེ་བར་ཞི་བ་དང་། ཕུང་པོ་ལ་བརྟེན་#་པའིསྡུག་བསྔལ་སྐྱེར་#དོགས་
ཚེག་ཆད་འདུག

2018-12-05 12:18 UTC, kungagyaltsen requested changes
བསྐྱར་དུ་བཟོ་རོགས།

2018-12-05 12:18 UTC, kungagyaltsen commented on derge-tengyur-tags/114_མདོ་སྡེ།_ཅི.txt
> +[36b.6]དཔའ་རྣམས་ཀྱི་ཆོས་མི་ཟད་པ་བསྟན་པ་ལས་#བརྩམས་ཏེ་སྤོབས་པར་གྱིས་ཤིག་ཅེས་བྱ་བ་ནི་ཆོས་མི་ཟད་པ་དེ་#ལྟ་བུར་ཤོད་ཅེས་བྱ་བའི་ཐ་ཚིག་གོ། །བློ་གྲོས་མི་ཟད་པས་སྨྲས་པ། ཏིའི་བུ་བྱང་ཆུབ་སེམས་དཔའ་རྣམས་ཀྱི་དང་པོ་སེ
[36b.6] བཙུན་པ་ཤ་ར་དྭ་ ཡི་གེ་དེ་རྣམས་ཆད་འདུག།

2018-12-06 04:06 UTC, Sangkhar requested changes
བཟོ་རོགས

2018-12-06 04:06 UTC, Sangkhar commented on derge-tengyur-tags/114_མདོ་སྡེ།_ཅི.txt
> +[3a.1]ཞེས་བྱ་བ་ནས་བརྩམས་ཏེ། སོ་སོ་ཡང་དག་པར་རིག་པ་བཞི་མི་ཟད་པ་ཞེས་བྱ་བ་ཡན་ཆད་ཀྱིས་བསྟན་པར་བྱ་བའི་མཐུ་འཐོབ་པ་བསྟན་ཏོ། །གཞན་ཡང་བཙུན་པ་ཤར་དྭ་ཏིའི་བུ་ཞེས་བྱ་བ་ནས་བརྩམས་ཏེ། རྟོན་པ་བཞི་མི་ཟད་པ་ཞེས་བྱ་བ་ཡན་ཆ
ཚེག

2018-12-06 04:06 UTC, Sangkhar commented on derge-tengyur-tags/114_མདོ་སྡེ།_ཅི.txt
> +[12a.2]པ་ཕུན་སུམ་ཚོགས་པ་བསྟན་ཏོ། །དེ་ནས་ཚེ་དང་ལྡན་པ་ཤ་ར་དྭ་ཞེས་བྱ་བ་ནས་ཕྱོགས་བཅུའི་སངས་རྒྱས་ཀྱི་ཞིང་ཚད་མེད་པ་ནས་ཆོས་ཉན་པའི་ཕྱིར་ལུས་#སོ་ཞེས་བྱ་བའི་བར་གྱིས་མཐུ་ཆེན་པོ་བསྟན་པ་ཕུན་སུམ་ཚོགས་པ་བསྟན་ཏོ། །ད
ཡི་གེ་བསུབ་འདུག

2018-12-06 04:06 UTC, Sangkhar commented on derge-tengyur-tags/114_མདོ་སྡེ།_ཅི.txt
> +[19a.6]སྦྱར་རོ། །ལན་བདུན་བསྐོར་བ་ནི་ལུས་དང་ངག་གི་ལས་རྣམ་#བདུན་སྦྱང་བའི་ཕྱིར་རོ། །ཚེ་དང་ལྡན་པ་ཤ་ར་དྭ་བཅོམ་ལྡན་འདས་ལ་དོན་རྣམ་པ་བཞི་#ཞུས་པ་ལས། བྱང་ཆུབ་སེམས་དཔའ་བློ་གྲོས་མི་ཟད་པ་འདི་ལ་དྲིས་ཤིག་ཅེས་གསུངས་
ཡི་གེ་བསུབ་འདུག

2018-12-06 04:06 UTC, Sangkhar commented on derge-tengyur-tags/114_མདོ་སྡེ།_ཅི.txt
> +[36b.6]དཔའ་རྣམས་ཀྱི་ཆོས་མི་ཟད་པ་བསྟན་པ་ལས་#བརྩམས་ཏེ་སྤོབས་པར་གྱིས་ཤིག་ཅེས་བྱ་བ་ནི་ཆོས་མི་ཟད་པ་དེ་#ལྟ་བུར་ཤོད་ཅེས་བྱ་བའི་ཐ་ཚིག་གོ། །བློ་གྲོས་མི་ཟད་པས་སྨྲས་པ། ཤ་ར་དྭ་ཏིའི་བུ་བྱང་ཆུབ་སེམས་དཔའ་རྣམས་ཀྱི་ད
ཡི་གེ་བསུབ་འདུག

2018-12-06 04:21 UTC, Sangkhar approved these changes

2018-12-06 04:22 UTC, merged