2018/12/4
Esukhia/derge-tengyur-old pull request #178
Opened 2018-12-04 11:11 UTC by drakpagyamtso

2018-12-04 11:27 UTC, drakpagyamtso commented
2018/12/4དེ་རིང་

2018-12-04 11:59 UTC, Sangkhar requested changes
བསྐྱར་དུ་བཟོ་རོགས།

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/018_རྒྱུད་འགྲེལ།_ཙ.txt
> +[58b.7]བཟླས་ཤིང་། འབྱུང་བཞིའི་སྟེང་དུ་བཅགས་ན་ཆུ་ལ་ཐང་བཞིན་དུ་འགྲོ་བར་འགྱུར་བའོ། །ཆུ་སྦྲུལ་གྱི་ཁྲག་སྤྲ་ཚིལ་གྱིས་(གཏུམས་,བཏུམས་)ལ་རང་གི་ཁར་བཅུག་སྟེ་སྔགས་སྤེལ་ཚིག་དང་བཅས་པས་བཟླས་ན་འགྲོ་བའམ་གནས་པ་ལ་ལུས་ལ
འདི་ལ་དོག་རྟགས་མེད་པར་མ་ཡིག་ལྟར་བཟོ་རོགས།

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/050_རྒྱུད་འགྲེལ།_ཛི.txt
> +[72a.3]མར་ལ་མངོན་པར་བསྔགས་ཏེ། སྐྱེ་བའི་སྒོ་ལ་བསྐུས་ན་སྦྲུམ་མ་བདེ་བར་བཙའ་བར་འགྱུར་རོ། །ཨོཾ་ཏཱ་རེ་ཏུཏྟཱ་རེ། མོ་ཀྵ་ཡཱ་བཛྲི་པཾ་སྭཱ་ཧཱ། གུར་གུམ་གྱིས་གྲོ་ག་ལ་གང་གི་མིང་སྨོས་པའི་སྔགས་མངོན་པར་བྲིས་ལ། སྤྲ་ཚིལ
འདི་ཡང་མ་ཡིག་ལྟར་རང་སོར་བཞག་ཆོག

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/074_རྒྱུད་འགྲེལ།_པུ.txt
> +[48b.3]འདོད་ན་གང་འདོད་པའི་ཤ་ཁྲག་དང་སྤུ་དང་གཤོག་པ་གཡས་པའི་སྤུ་རྩེ་རྣམས་ཕྱེ་མར་བྱས་ལ་བག་ཟན་དང་བསྲེས་ལ་གང་འདོད་པའི་གཟུགས་བྱས་ལ་དེ་ཉིད་སྤུས་ལུས་མགོ་མཇུག་བརྒྱན་པ་བསེའི་ག་འུའི་ནང་དུ་བཅུག་ལ་ཕག་ནག་པོའི་ཀོ་བས
འདི་ཡང་མ་ཡིག་ལྟར་བཞག་ཆོག

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/086_ཤེར་ཕྱིན།_ཇ.txt
> +[59b.1]བསྔལ་ལོ། །དེ་ལྟར་དེ་བཞིན་དུ་བྱང་ཆུབ་མཆོག་ཞུགས་རྙེད་པར་དཀའ་བའི་ཕྱིར་རིན་པོ་ཆེ་དང་འདྲ་བའི་སྙིང་རྗེ་དང་བཅས་པའི་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཡིད་ལ་བྱེད་པ་དོར་བར་མི་བྱའོ། །རིན་ཆེན་དོར་བ་རྙེད་པ་ལྟར། །
འདི་ཡང་།

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/103_དབུ་མ།_ཡ.txt
> +[138a.4]བ་དེ་བཞིན་དུ་བྱིས་པ་སོ་སོའི་སྐྱེ་བོ་ཐམས་ཅད་ཀྱང་སྡུག་བསྔལ་དང་ཉེ་བར་འཚེ་བའི་སྣུམ་ཆོས་ཀྱིས་#ཉོན་མོངས་པ་དག་ཞུ་བར་བྱས་པ་ཡིན་དུ་ཟིན་ཀྱང་མ་རིག་པས་(གཏུམས་,བཏུམས་)ཤིང་ཐིབས་པོའི་རྣམ་པ་ཅན་མི་ཤེས་པའི་ནད་
འདི་ཡང་།

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/123_སེམས་ཙམ།_ཕི.txt
> +[60a.6]མོངས་གོས་ཧྲུལ་གྱིས་(གཏུམས་,བཏུམས་)འཁོར་བའི་ལམ་ན་གནས་པའི་ཁམས། །དུད་འགྲོ་ལ་ཡང་གཟིགས་ནས་ཐར་པར་བྱ་ཕྱིར་རྒྱལ་བ་ཆོས་སྟོན་ཏོ། །ཇི་ལྟར་མི་མོ་གཟུགས་ངན་མགོན་མེད་འགའ། །མགོན་མེད་འདུག་གནས་སུ་ནི་འདུག་གྱུར་ལ
སྡེ་མཚན་འདིའི་དོག་རྟགས་ཚང་མ་མེད་ཀྱང་ཆོག་གི

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/123_སེམས་ཙམ།_ཕི.txt
> +[108a.3]ཐར་པར་བྱ་བའི་དོན་དུ་ཐབས་སྟོན་མཛད། །ཇི་ལྟར་རིན་ཆེན་རང་བཞིན་དེ་བཞིན་གཤེགས་སྐུ་དྲི་ངན་གོས་གཏུམས་པ། །ལམ་གནས་ལྷ་ཡི་མིག་གིས་#མཐོང་ནས་མཐར་ཕྱིན་མི་ལ་སྟོན་པ་ལྟར། །དེ་བཞིན་ཉོན་མོངས་གོས་ཧྲུལ་གྱིས་(གཏུམས
འདི་ཡང་།

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[53a.7]ནུ་ཊའོ། །དེ་ལ་(དིའི་,ངིའི་)ཨཱ་མའོ་ཞེས་པ་ཨཱ་མ་འབྱུང་ངོ་། །ཨཀའི་རིང་པོ་ཨ་ཀ་ལའོ། །ཀུན་དུ་དོད་པའི་སུ་ལའོ་ཞེས་པ་ཨེ་ཉིད་དོ། །ཨེང་ཐུང་ད་ལས་ཏ་མ་ཡིན་པའི་ཀུན་དུ་བོད་པ་ལའོ་ཞེས་སུ་དབྱིའོ། །ས་ས་ཛུ་ཥའི་དུའོ
འདི་ལ་ངའི་ཞེས་ཐད་ཀར་བྲིས་ནས་དོག་རྟགས་མེད་པར་བཟོ་རོགས།

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[53b.3]ཉིད་དོ། །ཨ་ཀའི་རིང་པོ་ཨ་ཀ་ལའོ། །བུད་མེད་ཨཱི་ཨཱུ་དག་ལས་སོ་ཞེས་པ་ནུཊའོ། །ར་ཥ་ལས་ནའི་ཎ་ཚིག་གཅིག་ལའོ། །(དིའི་,ངིའི་)ཨཱ་མ་དེ་ལའོ་ཞེས་པ་(དིའི་,ངིའི་)ཨཱ་མ་དུ་འགྱུར་རོ། །ཨ་ཀའི་རིང་པོ་ཨ་ཀ་ལའོ། །ཀུ་ལས་ཀ
འདི་ལའང་ངའི་ཞེས་བྲིས་ནས་དོག་རྟགས་རྣམས་མེད་པ་བཟོ་རོགས།

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[53b.6]ལའོ། །ཨ་ཀིའི་རིང་པོ་ཨ་ཀ་ལའོ། །བུད་མེད་ཨཱི་ཨཱུ་དག་ལས་སོ་ཞེས་ནུ་ཊའོ། །(དིའི་,ངིའི་)ཨཱ་མ་དེ་ལའོ། །(དིའི་,ངིའི་)ཨཱ་མ་དེ་ལའོ། །ཨ་ཀའི་རིང་པོ་ཨ་ཀ་ལའོ། །ཀུ་ལས་ཀྱང་ཞེས་པའོ། །ཀུན་དུ་བོད་པ་ལ་ངི་ཨཱུའི་ཞེས
འདིར་བརྗོད་པ་གཉིས་བརྩེགས་ཤོར་འདུག  ངའི་ཞེས་ཐད་ཀར་བྲིས་ནས་དོག་རྟགས་དང་བརྗོད་པ་ལྷག་མ་བསུབ་རོགས།

2018-12-04 11:59 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[54a.4]བྱིངས་བྷཱུ་རྣམས་ཀྱི་ཨི་ཡ་ཨུ་ཝ་དག་གོ་ཞེས་པ་ཨུ་ཝ་རུ་བསྒྱུར་རོ། །དེ་ཨི་ཡ་ཨུ་ཝའི་ཡང་ནའོ་ཞེས་པ་སྔོན་དུ་ཨཊ་ཡང་ནའོ། །ཨེ་ཙི་ལའོ། །ཨ་ཀའི་ཨ་ཀ་ལ་རིང་པོའོ། །དེ་ཨི་ཡ་ཨུ་ཝའི་ཡང་ནའོ་ཞེས་པ་ནུཊ་ཡང་ནའོ། །ཚིག་གཅ
ངའི་ཞེས་བྲིས་ནས་དོག་རྟགས་མེད་པ་བཟོ་རོགས།

2018-12-05 11:22 UTC, drakpagyamtso commented
བསྐྱར་བཅོས

2018-12-05 12:11 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-05 12:11 UTC, Sangkhar commented on derge-tengyur-tags/123_སེམས་ཙམ།_ཕི.txt
> +[60a.4]བར་འགྱུར་བ་ཡིན། །ཇི་ལྟར་རིན་ཆེན་ལས་བྱས་རྒྱལ་བའི་གཟུགས། །གོས་ཧྲུལ་དྲི་ངན་གྱིས་ནི་(གཏུམས་,བཏུམས་)གྱུར་པ། །ལམ་གནས་ལྷ་ཡིས་མཐོང་ནས་གྲོལ་བྱའི་ཕྱིར། །ལམ་གནས་དོན་དེ་དེ་ལ་སྨྲ་བ་ལྟར། །ཐོགས་མེད་སྤྱན་མངའ་
འདི་བཟོ་རོགས།

2018-12-05 12:11 UTC, Sangkhar commented on derge-tengyur-tags/123_སེམས་ཙམ།_ཕི.txt
> +[60a.5](གཏུམས་,བཏུམས་)བདེ་གཤེགས་དངོས་པོ་ཉིད། །དུད་འགྲོ་ལ་ཡང་གཟིགས་ནས་དེ་བཞིན་དེ། །ཐར་པར་བྱ་བའི་དོན་དུ་ཐབས་སྟོན་མཛོད། །ཇི་ལྟར་རིན་ཆེན་རང་བཞིན་དེ་བཞིན་གཤེགས་སྐུ་དྲི་ངན་གོས་གཏུམས་པ། །ལམ་གནས་ལྷ་ཡི་མིག་གི
ད་དུང་འདི

2018-12-05 12:11 UTC, Sangkhar commented on derge-tengyur-tags/123_སེམས་ཙམ།_ཕི.txt
> +[60a.6]མོངས་གོས་ཧྲུལ་གྱིས་(གཏུམས་,བཏུམས་)འཁོར་བའི་ལམ་ན་གནས་པའི་ཁམས། །དུད་འགྲོ་ལ་ཡང་གཟིགས་ནས་ཐར་པར་བྱ་ཕྱིར་རྒྱལ་བ་ཆོས་སྟོན་ཏོ། །ཇི་ལྟར་མི་མོ་གཟུགས་ངན་མགོན་མེད་འགའ། །མགོན་མེད་འདུག་གནས་སུ་ནི་འདུག་གྱུར་ལ
ཡང་འདི

2018-12-06 04:36 UTC, Sangkhar approved these changes

2018-12-06 04:36 UTC, merged