2018/12/6གཟའ་ཕུར་བུ་
Esukhia/derge-tengyur-old pull request #188
Opened 2018-12-06 11:02 UTC by drakpagyamtso

2018-12-06 13:07 UTC, kungagyaltsen requested changes
བསྐྱར་དུ་བཟོ་རོགས།

2018-12-06 13:07 UTC, kungagyaltsen commented on derge-tengyur-tags/025_རྒྱུད་འགྲེལ།_ཡ.txt
> +[76b.7]པར་བརྒྱན། །ཤམ་ཐབས་གླང་པོའི་པགས་པ་སྟེ། །ན་རའི་པགས་པ་གོས་སུ་མནབས། །མི་གཡོ་འཚེ་བ་མེད་པ་ཡི། བསམ་བས་ཀུན་ནས་བསྒོམ་པར་བྱ། །ཨོཾ་ཨྸྸཿཨཾ་སྭཱ་ཧཱ། ཨྸྸ་སྐྱེས་རླུང་གིས་དབུགས་འབྱིན་འབྱུང་། །གཏུམ་མོ་ལྷ་ཡི་དབང
[76b.7] ་མནབས། འདི་ཚག་ཐིག་བཞག་རོགས། དཔེ་ན་ མན་བས།

2018-12-06 13:07 UTC, kungagyaltsen commented on derge-tengyur-tags/082_ཤེར་ཕྱིན།_ག.txt
> +[2a.1]བཞིན་མ་ཡིན་འགྲོ་བ་འདི་ཡིན་ཞིང་། །ལྟ་བ་མཆོག་ཏུ་མི་ལེགས་ཆགས་སྡང་མུན་པ་རབ་ཏུ་ལྷག་གྱུར་མི་གཡོ་ལ། །ཚེ་ཡང་རིང་པོ་མེད་དང་མུན་པས་དྲི་བྲལ་སྣང་བ་བཟང་པོ་དང་ལྡན་པས#། །ཐེ་ཚོམ་ཡུལ་མིན་མདོ་འདི་
[2a.1]  ་མུན་པ་ འདི་ཨ་མ་ལྟར་དུ་བཟོ་རོགས་ དཔེ་ན མན་པ་

2018-12-06 13:07 UTC, kungagyaltsen commented on derge-tengyur-tags/190_ཚད་མ།_ཞེ.txt
> +[124b.7]བ་ལ་མ་ཡིན་ཏེ། དོན་གྱི་ཟུར་ཙམ་ངེས་པ་མེད་པས་སོ། །བརྡར་བྱས་པའི་ཐ་སྙད་བརྒྱུད་པ་ལ་མཁས་པས་ངེས་པ་དང་ལྡན་པ་ནི་འདིར་ཐུན་མོང་བ་ཉིད་དོ། །དེའི་ཕྱིར་འདི་ནི་ནགས་ཚལ་ན་ངུ་བ་ཡིན་ཏེ། ཨམ་པ་ཨམ་བེ་ཞེས་བྱ་བ་ནི་དཔེ
[124b.7] འདི་ཨ་མ་ལྟར་དུ་བཟོ་དགོས། ངུ་བ་མ་ཡིན་དུ་བ་ཡིན།

2018-12-07 03:59 UTC, drakpagyamtso commented on derge-tengyur-tags/082_ཤེར་ཕྱིན།_ག.txt
> +[2a.1]བཞིན་མ་ཡིན་འགྲོ་བ་འདི་ཡིན་ཞིང་། །ལྟ་བ་མཆོག་ཏུ་མི་ལེགས་ཆགས་སྡང་མུན་པ་རབ་ཏུ་ལྷག་གྱུར་མི་གཡོ་ལ། །ཚེ་ཡང་རིང་པོ་མེད་དང་མུན་པས་དྲི་བྲལ་སྣང་བ་བཟང་པོ་དང་ལྡན་པས#། །ཐེ་ཚོམ་ཡུལ་མིན་མདོ་འདི་
མ་ཡིག་ལྟར་བཟོས་ཡོད་པས་་་་བསྐྱར་བཅོས་བྱེད་དགོས་ཀྱི་མི་འདུག་

2018-12-07 04:02 UTC, drakpagyamtso commented on derge-tengyur-tags/025_རྒྱུད་འགྲེལ།_ཡ.txt
> +[76b.7]པར་བརྒྱན། །ཤམ་ཐབས་གླང་པོའི་པགས་པ་སྟེ། །ན་རའི་པགས་པ་གོས་སུ་མནབས། །མི་གཡོ་འཚེ་བ་མེད་པ་ཡི། བསམ་བས་ཀུན་ནས་བསྒོམ་པར་བྱ། །ཨོཾ་ཨྸྸཿཨཾ་སྭཱ་ཧཱ། ཨྸྸ་སྐྱེས་རླུང་གིས་དབུགས་འབྱིན་འབྱུང་། །གཏུམ་མོ་ལྷ་ཡི་དབང
མནབས་ནི་གོས་སོགས་གྱོན་པའི་དོན་ཡིན་པས་་་་མ་ཡིག་ལྟར་བཟོས་ཡོད་

2018-12-07 04:44 UTC, kungagyaltsen approved these changes

2018-12-07 04:44 UTC, merged