ལས་ཀ2018/12/6
Esukhia/derge-tengyur-old pull request #189
Opened 2018-12-06 11:04 UTC by Sermig

2018-12-06 12:45 UTC, Sangkhar requested changes

2018-12-06 12:45 UTC, Sangkhar commented on derge-tengyur-tags/053_རྒྱུད་འགྲེལ།_ཟི.txt
> +[132b.3]རུ་གནས་ཏེ། མི་རྟོག་པའི་ནུས་པ་རྙེད་ནས་ཚོགས་ཀྱི་གསེབ་ཏུ་ཕྱིན་ཀྱང་ཞེ་སྡང་ལ་སོགས་གང་བྱུང་ཡང་དྲན་པ་དང་མི་འབྲལ་ཞིང་གཞན་གྱི་དབང་དུ་མི་འགྲོ་ན་དུས་ལ་བབ་པའོ། །ཡང་ན་ཀུན་དུ་རྒྱུ་ཉིད་བྱ་སྟེ།གནས་གཅིག་ཏུ་ཡུ
(ཉིད་བྱ་སྟེ།གནས་གཅིག) འདི་ལ་བར་སྟོང་ཞིག་འཇོག་དགོས་

2018-12-06 12:45 UTC, Sangkhar commented on derge-tengyur-tags/120_མདོ་སྡེ།_དི.txt
> +[250a.1]མདོ་ལས་དེ་ཅིའི་སླད་དུ་ཞེ་ན་བཅོམ་ལྡན་འདས་སྐྱེས་བུ་དེ་ཤོ་འི་བར་དུ་ནི་ཐེག་པ་ཆེན་པོ་བསྟན་པའི་ཕྱིར་བརྫུན་#དུ་མི་འགྱུར་བ་བསྟན་པའོ། །མདོ་ལས་དེ་སྐད་ཅེས་གསོལ་པ་དང་། བཅོམ་ལྡན་འདས་ཀྱིས་ཚེ་དང་ལྡན་པ་ཤཱ་རི
ཡི་གེ་བསུབ་འདུག

2018-12-06 12:45 UTC, Sangkhar commented on derge-tengyur-tags/159_འདུལ་བ།_ཝུ.txt
> +[27b.2]འབྲེལ་བ་མེད་པ་རང་རང་གི་ལྷུང་བཟེད་དག་ཐོགས་ལ་དགེ་འདུན་གྱི་ནང་དུ་གཤེགས་པར་མཛོད་ཅིག་ཅེས་སོ། །འཁོད་པའི་དོན་དུ་ནན་ཏན་བྱའོ། །བསྔགས་པ་བརྩམ་ཞིང་དབུལ་བར་བྱའོ། །གནས་བརྟན་ལྷུང་བཟེད་འདི་ནི་ཤིན་ཏུ་གསལ་བ།
ཡི་གེ་བསུབ་འདུག

2018-12-07 04:08 UTC, kungagyaltsen approved these changes

2018-12-07 04:09 UTC, merged