ཞུ་དག 2018.12.06
Esukhia/derge-tengyur-old pull request #191
Opened 2018-12-06 11:22 UTC by tibetanboy

2018-12-06 12:26 UTC, Sangkhar requested changes
བསྐྱར་བཟོ

2018-12-06 12:26 UTC, Sangkhar commented on derge-tengyur-tags/005_རྒྱུད་འགྲེལ།_ང.txt
> +[20a.7]བགེགས་ཐམས་ཅད་ཚར་གཅད་པར་བྱ་བའི་ཕྱིར་དཀྱིལ་འཁོར་ལོ་ལ་སོགས་པ་མངོན་དུ་བྱས་ནས་དང་པོ་ཁོ་ནར་འབྱུང་པོ་ཐམས་ཅད་ཀྱི་གཏོར་མའི་སྔགས་གསུངས་པ། ཨོཾ་ཨ་ཀཱ་རོ་མུ་ཁཾ་སརྦ་བྷརྨཱ་ནཱཾ་ཨཱ་ཌྱ་ནདྤ་ནྞཱུ་ཏྭཱ་ཏ། ཨོཾ་ཨཱཿ་ཧཱ
[ནྞཱུ]  ནྣུ འདི་ལྟར་བཟོ་རོགས།

2018-12-06 12:26 UTC, Sangkhar commented on derge-tengyur-tags/122_མདོ་སྡེ།_པི.txt
> +[192b.1]འཛིན་ཅིང་བློའི་མདུན་དུ་བྱེད་པའོ། །སྐྱེ་བ་དང་མི་སྐྱེ་བ་ལ་མོས་པ་ཡང་དེ་དག་ཉིད་དང་གོ་རིམས་བཞིན་དུ་སྦྱར་རོ། །ཡོད་པ་སྐྱེ་བ་སྐྱེ་སྟེ་མེད་པ་མ་ཡིན་ནོ་ཞེས་པ་ནི་གྲངས་ཅན་པ་རྣམས་ཀྱི་འདོད་པ་ལྟར་ཐོག་མ་ནས་ཡོ
(ཡོད་པ་སྐྱེ་བ་སྐྱེ་སྟེ་མེད་པ་མ་ཡིན་ནོ་)  འདིའི་མ་ཡིག་ལ་ཞིབ་ལྟ་ཞིག་བྱེད་རོགས།

2018-12-07 04:46 UTC, kungagyaltsen approved these changes

2018-12-07 04:46 UTC, merged