ལས་ཀ2018/12/7
Esukhia/derge-tengyur-old pull request #193
Opened 2018-12-07 10:58 UTC by Sermig

2018-12-07 11:06 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-07 11:06 UTC, Sangkhar commented on derge-tengyur-tags/035_རྒྱུད་འགྲེལ།_ངི.txt
>  [197a.4]བཞི་#པ་ལས་གསུངས་པའི་ཧཱུྃ་#བཞི་པའི་སྔགས་ཀྱིས་བཀའ་བསྒོ་སྟེ། ཨོཾ་སུམྦྷ་ནི་སུམྦྷ་ཧཱུཾ། [གྲྀ]་ཧྞ་[གྲྀ]་ཧྞ་ཧཱུཾ། [གྲྀ]་ཧྞཱ་པ་ཡ་[གྲྀ]་ཧྞ་#པ་ཡ་ཧཱུཾ། ཨཱ་ན་ཡ་ཧོ་བྷ་ག་བཱ་ན་བི་དྱཱ་རཱ་ཛཱ་#ཡ་ཧཱུཾ་ཕཊ། དེ་ནས
དོག་རྟགས་དགོས་མིན་བསྐྱར་ལྟ་བྱེད་རོགས།

2018-12-07 11:06 UTC, Sangkhar commented on derge-tengyur-tags/052_རྒྱུད་འགྲེལ།_ཞི.txt
> +[254a.4]ཅོན་ལག་ཐོགས་ཟུར་གྱིས་ལྟ་བྱེད་ཅིང་། །མིག་རྩ་དམར་ཁྲོས་མ་། །རྣལ་འབྱོར་བསྟན་བཅོས་ཐམས་ཅད་དང་། །སྦྱོར་བ་དུ་མ་རབ་ཤེས་ཀྱང་། །དེང་བྱ་སང་བྱ་ཞེས་སྨྲ་ཞིང་། །བསམ་དང་ལྡན་པས་འཆི་བར་འགྱུར། །ཚེ་འདི་གནོད་མང་རླ
ཡི་གེ་བསུབ་འདུག

2018-12-11 05:14 UTC, kungagyaltsen approved these changes

2018-12-11 05:14 UTC, merged