12-7-2018
Esukhia/derge-tengyur-old pull request #195
Opened 2018-12-07 11:00 UTC by kunchokdolma

2018-12-07 11:15 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-07 11:15 UTC, Sangkhar commented on derge-tengyur-tags/161_འདུལ་བ།_ཟུ.txt
> +[262b.6]མ་ཟིན་པ་ཉིད་དོ། །དེ་བཀྲུ་བར་ཞེས་བྱ་བ་ནི་རྐང་པ་དེ་བཀྲུ་བ་ལའོ། །ཆབ་ཁུངས་དེར་ཞུགས་པ་ཉིད་ནའོ་ཞེས་བྱ་བ་ལ། དེར་ཞེས་བྱ་བ་ནི་ཆབ་ཁུང་ལའོ། །ཞུགས་པ་ཉིད་ན་#ཞེས་བྱ་བ་ནི་མ་ཟིན་ནའོ། །སྒོམ་པའི་ཕྱིར་འདུག་པ་(བ
འདི་ལ་དོག་རྟགས་མེད་ཀྱང་ཆོག

2018-12-07 11:15 UTC, Sangkhar commented on derge-tengyur-tags/161_འདུལ་བ།_ཟུ.txt
> +[264b.3]ཀྱིས་གྲོང་དབུས་སུའོ། །ཡུ་བ་ལ་གཞར་དུ་མི་རུང་བ་ཉིད་མ་ཡིན་ནོ་ཞེས་བྱ་བ་ནི་འདིར་དྲི་མ་བཀྲུ་བར་བྱ་བའི་ཕྱིར་ཡུ་བ་ལ་བྱི་དོར་བྱ་བར་རིག་པར་བྱ་སྟེ། །འདིར་དེ་ལྟར་བརྗོད་པར་བྱའོ། །ཆད་ན་ཁྱིམ་དག་ཏུ་གཞག་གོ་ཞེ
འདི་ལ་དོག་རྟགས་མི་དགོས།

2018-12-11 05:18 UTC, kungagyaltsen approved these changes

2018-12-11 05:18 UTC, merged