ཞུ་དག 2018.12.07
Esukhia/derge-tengyur-old pull request #196
Opened 2018-12-07 11:02 UTC by tibetanboy

2018-12-07 11:23 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-07 11:23 UTC, Sangkhar commented on derge-tengyur-tags/019_རྒྱུད་འགྲེལ།_ཚ.txt
> +[96b.2]གྲུབ་ཀུན་གྱི་གནས་ཞེས་བྱ་བ་ནི་འཇིག་རྟེན་དང་འཇིག་རྟེན་ལས་འདས་པའི་དངོས་གྲུབ་རྣམས་ཀྱི་གནས་ཏེ། གོང་ནས་གོང་དུ་འཕེལ་བར་བྱེད་པའི་རྟེན་ཡིན་ནོ། །ཡང་ན་དངོས་གྲུབ་ཀུན་ནི་བཅོམ་ལྡན་འདས་ཉིད་ཡིན་ལ་གནས་ནི་ཕོ་བྲ
འདི་ལ་དོག་རྟགས་བཞག་ན་ཡག་ས་རེད།

2018-12-07 11:23 UTC, Sangkhar commented on derge-tengyur-tags/164_འདུལ་བ།_རུ.txt
> +[92b.1]བཟེད་སྣོམས་ལ་དགེ་འདུན་གྱི་ནང་དུ་(སྦྱོན་‚སྤྱོན)#ཅིག་ཅེས་སོ་ཞེས་པ་ཡིན་ཏེ་སྦྲན་པའི་སྙད་#འདི་སྐད་དུ་གྱིས་ཤིག་པའོ། །འཁོད་པའི་ཕྱིར་བཤམ་ཞེས་པ་ནི་དགེ་འདུན་འདུ་བའི་སར་ཆག་ཆག་གདབ་ཅིང་གདན་#གདིང་བ་ལ་སོགས་པ
དོག་རྟགས་ནང་ཚེག་ཞིག་ཆད་འདུག

2018-12-11 05:07 UTC, kungagyaltsen approved these changes

2018-12-11 05:07 UTC, merged