གཟའ་པ་སང་གི་ལས་ཀ་2018.12.7
Esukhia/derge-tengyur-old pull request #197
Opened 2018-12-07 11:09 UTC by gyamtso59

2018-12-07 11:28 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-07 11:28 UTC, Sangkhar commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +<<<<<<< HEAD
འདི་ན་headལྷག་འདུག བཟོ་རོགས།

2018-12-11 11:53 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-11 11:53 UTC, Sangkhar commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +
འདི་ན་སྟོང་པ་ཞིག་ཤོར་ཡོད་ས་རེད།

2018-12-12 04:40 UTC, kungagyaltsen approved these changes

2018-12-12 04:40 UTC, merged