གཟའ་ཟླ་བའི་ལས་ཀ2018.12.17
Esukhia/derge-tengyur-old pull request #221
Opened 2018-12-17 11:05 UTC by gyamtso59

2018-12-17 12:14 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-17 12:14 UTC, Sangkhar commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[218b.5]དཱི་ནཱ་རེ་པི་ཙནིཥྐོསྟྲཱྀ་ཀལྐོ྅སྟྲཱི་ས་མ་ལཻ་ན་སོཿ། །དམྦྷེ་བྱ་ཐ་པི་ནཱ་ཀོ྅སྟྲི་ཤཱུ་ལ་ཤཾ་ཀ་ར་དྷ་ནྭ་ནོཿ། །དྷེ་ནུ་ཀཱ་ཏུ་ཀ་རེ་ཎྭཱཉྩ་མེ་གྷ་ཛཱ་ལེ་ཙ་ཀཱ་ལི་ཀཱ །ཀཱ་རི་ཀཱ་པཱ་ཏ་ནཱཾ་བྲྀཏྟྱོཿཀརྞྞི་ཀཱ་ཀརྞྞ་བྷ
(ཐོང་ཊི་ཀའི་མིང་། ) ཡི་གེ་འདི་དག་ཐིག་འཕྲེང་འོག་མའི་མགོ་ལ་འཇོག་དགོས།

2018-12-17 12:14 UTC, Sangkhar commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[223b.1]མྲྀ་ཏེ། །ཀལ་དྷཽ་ཏཾ་རཱུ་པྱ་ཧེ་མྣོརྣི་མིཏྟཾ་ཧེ་ཏུ་ལཀྵ་ཎོཿ། །ཤྲུ་ཏཾ་ཤཱསྟྲཱ་བ་དྷྲྀ་ཏ་ཡོར་ག་པརྻཱཔྟ་ཡོཿཀྲྀ་ཏཾ། །ཨ་ཏྱཱ་ཧི་ཏཾ་མ་ཧཱ་བྷཱི་ཏིཿཀརྨ་ཛཱི་བཱ་ན་པེ་ཀྵི་ཙ། །ཡུཀྟེཀྵྨཱ་དཱ་བྲྀ་ཏེ་བྷཱུ་ཏཾ་པྲཱ་ཎྱ་ཏ
(དྷྲྀ་ཏ་ཡོར་ག་པརྻཱཔྟ)  འདི་ན་ཡི་གེ་ཆད་འདུག

2018-12-17 12:14 UTC, Sangkhar commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[224a.1]མཱུརྩྪི་ཏཽ་མཱུ་ཌྷ་སོཙྪྭ་ཡཽ། །དྭཽ་ཙཱམྦུ་པ་རུ་ཥཽ་ཤུཀྟཽ་ཤཱི་ཏི་དྷ་བ་ལ་མེ་ཙ་ཀཽ །ས་ཏྱེ་སཱ་དྷཽ་བིདྱ་མཱ་ནེ་བྲ་ཤསྟེཉབྷྱརྷི་ཏེ་ཙ་སཏ། །པུར་སྐྲྀ་ཏཿ་པཱུ་ཛི་ཏེཉརཱ་ཏྱ་བྷི་ཡུཀྟེཉགྲ་ཏཿ་ཀྲྀ་ཏེ། །ནི་བཱ་ཏཱ་བཱ་ཤ
(པུར་སྐྲྀ་ཏཿ་པཱུ་ཛི་)  འདིའི་གོར་ཐིག་གཉིས་རྗེས་ལ་ཚེག་ཤོར་འདུག  བསུབ་རོགས།

2018-12-17 12:14 UTC, Sangkhar commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[224b.6]སྱཱ་དཾ། །ཡིད་འོང་སྦྲང་རྩི་སྭཱ་དཱུའོ། །མྲྀ་དུ་རྣོ་དང་འཇམ་པ་དག །རྨོངས་དང་ཉུང་དང་མི་གསལ་དང་། །སྐལ་བངན་རྣམས་མནྡའོ། །ཤ་རཱ་དཽ་ནི་རྩེ་མོ་གཉེན། །བི་ཤཱ་ར་དཽ་སྤོབས་ཅན་མཁས། །ད་མཐའོ། །འདོམ་དང་ཤིང་ལ་ནྱ་གྲ
སྐལ་བ་ངན་ཞེས་འབྲི་རོགས།

2018-12-17 12:14 UTC, Sangkhar commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[228b.1]རདྒ་ག་རུ་ཌཽ་ཏཱ་་ནི་ལ་ཡཱ་ཡ་ཙ་པཽ་ཀྵ་ཡོ། །ཤྭ་ཤུརྻོ་དེ་བ་ར་ཤྱཱ་ལོ་བྷྲཱ་ཏྲྀ་བྱཽ་དྷྲཱ་ཏྲྀ་ཛ་དྭི་ཥཽ། །པཪྻ་ནྱཽ་ར་ས་དབྡེནྡྲ་སྱཱཪྻཿ་སྭཱ་མི་བཻ་ཤྱ་ཡོཿ། །ཏི་ཥྱཿཔུ་ཥྱེ་ཀ་ལི་ཡུ་གེ་པཪྻ་ཡོ྅བ་ས་རེ་ཀྲ་མཻ། །པྲ་ཏ
འདི་ལ་ཡི་གེ་གཅིག་བསུབ་འདུག

2018-12-17 12:14 UTC, Sangkhar commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[231a.2]༄༅། །དབྱི་མགོ་ཟེར། མ་ཆུ། །རིགས་དང་སྣོད་ནི་པཱ་ཏྲཾ་ངོ་། །པ་ཏྲཾ་བཞོན་པ་འདབ་མའོ། །ཤཱསྟྲཾ་ངེས་བསྟན་དང་ནི་གཞུང་། །ཤསྟྲ་མཚོན་དང་ལྤགས་དག་ལའོ། །རྩ་པྲན་གོས་མིག་ནེ་ཏྲཾའོ། །ཀྵེ་ཏྲཾ་ཆུང་མ་ལུས་དག་གོ། །ཕག་ས
(དབྱི་མགོ་ཟེར། །མ་ཆུ།)འདི་ལ་ཕལ་ཆེར་ཤད་ཞིག་དགོ་བ་འདུག

2018-12-18 04:09 UTC, kungagyaltsen approved these changes

2018-12-18 04:09 UTC, merged