ཞུ་དག 2018.12.17
Esukhia/derge-tengyur-old pull request #222
Opened 2018-12-17 11:21 UTC by tibetanboy

2018-12-17 11:54 UTC, Sangkhar requested changes
བསྐྱར་བཟོ།

2018-12-17 11:54 UTC, Sangkhar commented on derge-tengyur-tags/068_རྒྱུད་འགྲེལ།_ཇུ.txt
>  [202a.6]མཁའ་རླུང་དང་ཆུ་དཀྱིལ་འཁོར། །ས་གཞི་མེ་དཔུང་རིན་ཆེན་རི། །བྷྲཱུཾ་ལས་བསྐྱེད་པའི་གཞལ་ཡས་ཁང་། །ཉི་ཟླ་པདྨའི་གདན་དང་བཅས། །མ་སྐྱེས་པ་ཡི་རང་བཞིན་ལས། །སྐྱེད་པའི་བྱང་ཆུབ་ཟླ་བའི་སྟེང་། །བཾ་ཧཱུཾ་ཏྲཾ་བྲུཾ་ར
ཤད་གཅིག་དཀྱིལ་མ་ལ་འདུག

2018-12-17 11:54 UTC, Sangkhar commented on derge-tengyur-tags/169_སྐྱེས་རབས།_ཨུ.txt
> +[227a.7]སྙན་དག་གིས་རྣམ་པར་གཞག་པ་འཛིན་བྱེད་པ། །བུང་བའི་སྒྲ་བཞིན་ངེས་པར་ཡིད་འཕྲོག་རྒྱུད་མངས་དག་གི་རྒྱུད་མངས་སྒྲ་དང་ལྡན་པ་ཡིས། །གསལ་ཞིང་རོལ་སྒེག་ཚིག་ལྡན་གྲུ་ནི་ཀུན་དུ་འཁྱོག་པའི་ལུས་ཅན་རི་དྭགས་འདི་དག་རྣམ
རི་དྭགས།  འདིའི་ཝ་ཟུར་བསུབ་འཇོག་རོགས

2018-12-17 11:54 UTC, Sangkhar commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> -ཱ[158a.3]པ་རསྨཻའི་ཚིག་ཅན་གྱི་ཤཱ་བ་གཟུང་གི་དེ་ལས་གཞན་ནི་མ་ཡིན་ནོ། །ཨ་ཤཱ་སིཥྚ། པ་སྠ་ཏ། ཁྱ་ནི་བ་ཙི་ཞེས་པར་བསྒྱུར་བ་དང་མ་བསྒྱུར་བ་གཉི་ག་གཟུང་ངོ་། །ཨ་ཁྱཱཏ། ཨ་བོ་ཙ་ཏ། ཧྭཱ་ལི་པ་སི་ཙ་ལས་སོ། །ཧྭ་ཡ་ཏི་དང་ལི་བ་
འདི་ལ་སང་ཉིན་མིག་ལྟ་ཞིག་བྱེད་དགོས། ཡི་གེ་འ་ཆུང་ཞིག་སྔོན་ལ་བཞུག་འདུག ག་རེ་ཡིན་མིན་མ་ཤེས་ཐ།

2018-12-17 11:54 UTC, Sangkhar commented on derge-tengyur-tags/196_སྒྲ་མདོ།_ཤེ.txt
>  [70a.3]ཞེས་པ་ལ་སོགས་པ་སྟེ། བདུན་པའི་མང་པོའི་ཚིག་ལ་སྒྲ་མེད་པ་ལ་དང་པོའོ་ཞེས་པས་ཀ་ཡིག་ཏུ་འགྱུར་ཞིང་། ནཱ་མི་དང་ཀ་དང་ར་ཕ་རོལ་ཞེས་པ་ལ་སོགས་པས་ཥ་ཉིད་དོ། །ཝཱཀྵུ། ཀུན་དུ་བོད་པ་ལ་ནི། ཧེ་ཝཱཀ ། ཧེ་ཝཱག །ཧེ་ཝཱ་ཙཽ།
ཤད་དཀྱིལ་མ་ལ་འདུག

2018-12-17 11:54 UTC, Sangkhar commented on derge-tengyur-tags/196_སྒྲ་མདོ།_ཤེ.txt
>  [71b.4]པས་ཀ་ཡིག་གམ་ག་ཡིག་དག་གོ། །དིཀ །དིག །དི་ཤཽ། དི་ཤཿ། དི་ཤཾ། དི་ཤཽ། དི་ཤཿ། དི་ཤཱ། དིགྦྷྱཱཾ། དིགྦྷིཿ། ཞེས་པ་ལ་སོགས་པ་སྟེ། སུ་པ་ལ་ཥ་ཉིད་དུ་བྱས་པ་ན། སྒྲ་མེད་པ་ལ་དང་པོའོ་ཞེས་པས་ཀ་ཡིག་གོ། །དིཀྵུ། ཀུན་ད
ཤད།

2018-12-18 04:13 UTC, kungagyaltsen approved these changes

2018-12-18 04:14 UTC, merged