ཞུ་དག 2019.01.14
Esukhia/derge-tengyur-old pull request #290
Opened 2019-01-14 11:18 UTC by tibetanboy

2019-01-14 12:48 UTC, kungagyaltsen requested changes
བསྐྱར་བཟོ་གནང་རྒྱུ།

2019-01-14 12:48 UTC, kungagyaltsen commented on derge-tengyur-tags/012_རྒྱུད་འགྲེལ།_ད.txt
> +[133b.1]གྱི་ཟླ་བའི་ཉ་དང་གནམ་སྟོང་དག་གིབྼྀ་བོཾ་མོ། །དབང་ལྡན་དུ་རིང་པོའི་དབྱེ་བས་ཚོགས་ཀྱི་ཞེས་པ་ལོག་འདྲེན་གྱི་སྟེ་ལྟེ་བ་ལ་ཁྲུམས་ཀྱི་ཟླ་བའི་ཉ་དང་གནམ་སྟོང་དག་གི་བྼཱྀམཿའོ། །དེ་བཞིན་དུ་ཆུར་བརྒྱ་བྱིན་གྱི་ཏ་
[133b.1] ཚག་ཞིག་དགོས་འདུག། བྼཱྀ་མཿའོ།

2019-01-14 12:48 UTC, kungagyaltsen commented on derge-tengyur-tags/012_རྒྱུད་འགྲེལ།_ད.txt
> +[138b.7]བུ་དཀྲོལ་ནས་དབང་དུ་བྱའོ། །འདིར་མཆོད་ཡོན་དབུལ་བར་བྱ་སྟེ་ཨོཾ་པྲ་ཝ་ར་སཏ་ཀཱ་རཾ་མ་ཧཱ་ར་སྨཱིན་པྲ་ཏཱི་ཙྪ་སྭཱ་ཧཱ་ཞེས་པ་ནི་མཆོད་ཡོན་དབུལ་བའི་སྔགས་སོ། །དེ་ནས་མཆོད་པ་ནི་དེ་བཞིན་དུ་བཛྲ་གན་དྷཾ་པྲ་ཏཱི་ཙྪ་ས
[138b.7] ་ཏཱི་ཙྪ་ འདིའི་བར་ཚག་དེ་སུབ་རོགས། ་ཏཱིཙྪ་

2019-01-16 04:22 UTC, tseringwa approved these changes

2019-01-16 04:22 UTC, merged