ཞུ་དག་ཁ་ཤས་ཡོད།
Esukhia/derge-tengyur-old pull request #39
Opened 2018-09-20 11:00 UTC by Sangkhar

update

2018-09-21 08:00 UTC, rekongrabten requested changes
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/002_རྒྱུད་འགྲེལ།_ཀ.txt
> +[82a.7]རྣམས། །མི་ཡི་བུ་མོ་རྣམ་པ་བཞི། །སྔགས་ཀྱིས་ཀུན་ནས་བཀུག་ནས་ནི། །ས་ཡི་དཀྱིལ་འཁོར་ཀུན་དུ་སྤྱད། །དེ་ཡིས་སྐལ་ལྡན་རྣལ་འབྱོར་པ། །ཕྱག་རྒྱ་གྲུབ་པར་གདོན་མི་ཟ། །མི་གཙང་རུལ་པ་(དྲིམ་,བྲིམ་)པའི། །མི་མོའི་ལུས་
གུག་རྟགས་ནང་གི་ཡི་གེ་དེ་གཉིས་ལ་ཡང་བསྐྱར་གཟིགས་རོགས། དྲི་མ་ཡིན་ས་རེད།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/010_རྒྱུད་འགྲེལ།_ཏ.txt
> +[344a.3]མ་ཧཱ་མ་ཡུ་ར་རཱ་ཛཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་མ་ཧཱ་དྷྭ་ར་རྩྭ་ཡེ་སྭཱ་ཧཱ། ཨོཾ་མནྟྲ་པ་ཏཱ་ཛྭ་སྭཱ་ཧཱ། ཨོཾ་མ་ཧཱ་མ་ཡུ་རི་བིརྱ་ར་རྙི་ཡེ་སྭཱ་ཧཱ། ཨོཾ་མ་ཡུ་ར་ཀ་ཏཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་ནནྡ་ནཱ་ག་རཱ་ཛཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་ཨུ་པ་ནནྡ་ན
ཐིག་ཕྲེང་འདིའི་སྔགས་ཡིག་ཀུན་ལ་ཞིབ་གཟིགས་གནང་རྒྱུ་དང། ཁྱེད་ཀྱིས་བཟོས་པ་དེ་ཡང་ནོར་འདུག

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/014_རྒྱུད་འགྲེལ།_པ.txt
> +[267a.3]ཀ་རས་མཛད་པ་རྫོགས་སོ།། །།པཎྜི་ཏ་ཇོ་བོ་རི་པ་དང་། སྒྲ་སྒྱུར་གྱི་ལོ་ཙཱ་བ་ཁེའུ་(བགད་,བརྒད་)འཁོར་ལོ་གྲགས་ཀྱིས་བསྒྱུར་བའོ། །{T1381}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཤྲཱི་ཀཱ་ལ་ཙཀྲ་དཎྜ་ཀ་སྟུ་ཏི་ནཱ་མ། བོད་སྐད་དུ། ད
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/015_རྒྱུད་འགྲེལ།_ཕ.txt
> +[216b.5]རྫོགས་པའི་སྐུའོ། །དར་བ་ཆེན་པོ་ནི་སྐུ་བཞི་ལས་གཟུགས་སྐུར་སྣང་བ་དར་ཕྱར་བར་རིན་པོ་ཆེའི་ཏོག་(གཙུགས་,གཙུག་)པ་ལྟ་བུའོ། །དེ་ལྟར་ཡེ་ཤེས་ཀྱི་སྐུ་མངོན་སུམ་དུ་བསྒོམ་པ་ལ་སྔོན་དུ་དབང་དགོས་པས་དབང་བསྟན་པ་ལ།
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/019_རྒྱུད་འགྲེལ།_ཚ.txt
> +[231a.6]ཅེས་པ་ནི། ་དསྶ་ཏིཎྞ་ཛྷ་ཨ་ཨི་ཞེས་པ་ལ་སོགས་པའི་སྔགས་ཀྱིས་སོ། །ཀ་ར་བཱི་རའི་ལྕུག་མ་ལ་ལག་པའི་ཚད་ཙམ་བླངས་ཏེ། ཆོ་ག་བཞིན་སྔགས་པས་རླུང་དང་ཆར་པ་དང་སེར་བ་ལ་སོགས་པ་ཟློག་པར་བྱེད་དེ། འདིའི་ཆོ་གས་རྟོགས་པར་བ
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/026_རྒྱུད་འགྲེལ།_ར.txt
> +[314b.6]མཛེས་ཤིང་། རང་འོད་ཀྱི་རིག་མ་དང་འཁྲིལ་བའི་ཚུལ་གྱིས་ཞལ་སྦྱོར་ཏེ་འགྱིང་བག་གི་རྣམ་པས་བཞུགས་པའོ། །མེ་མཚམས་ཀྱི་རེའུ་མིག་ལ་རྡོ་རྗེ་གླིང་བུ་མ་བཻཌཱུ་རྱའི་མདོག་ཅན་རྡོ་རྗེས་མཚན་པའི་གླིང་བུ་སྒྲོགས་པའོ། །
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/027_རྒྱུད་འགྲེལ།_ལ.txt
> +[104b.3]སྐུ་མདོག་དཀར་པོ་བྱང་ཆུབ་མཆོག་གི་ཕྱག་རྒྱ་ཅན། དཔྲལ་བའི་སྟེང་དུ་མི་བསྐྱོད་པ། སྐུ་མདོག་དཀར་པོ་ས་གནོན་གྱི་ཕྱག་རྒྱ་ཅན་གྱིས་བརྒྱན་པ། གཡས་སུ་རིན་ཆེན་འབྱུང་ལྡན་བཻཌཱུ་རྱའི་མདོག་ཅན་མཆོག་སྦྱིན་གྱི་ཕྱག་རྒ
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/050_རྒྱུད་འགྲེལ།_ཛི.txt
> +[70a.3]#ཀྱི་ཞལ་སྔ་ནས་མཛད་པ་རྫོགས་སོ།། །།{T2191}༄༅༅། །ཕྱག་ན་རྡོ་རྗེའི་ལམ་ཡན་ལག་བརྒྱད་པ་ཞེས་བྱ་བ།#༄༅༅། །རྒྱ་གར་སྐད་དུ། བཛྲ་པཱ་ཎི་མཱརྒཱཥྚཱཾ་བ#། བོད་སྐད་དུ། ཕྱག་ན་རྡོ་རྗེའི་ལམ་ཡན་ལག་བརྒྱད་པ། འཕགས་པ་ལག་ན་
འདིར་གཟིགས་རོགས། འདིར་བཞི་ཤད་མེད་ལ་མཚན་བྱང་ཡང་མི་འདུག

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/050_རྒྱུད་འགྲེལ།_ཛི.txt
> +[78b.3]བྲིས་པ། གླ་རྩི། ག་པུར། མུ་ཟི། བཙན་དུག །གུ་གུལ། ཙནྡན་གོ་ཤིཪྵ། སྨན་གི་སྦང་། བྱ་རྒོད་ཀྱི་ཚིལ་བུ། སྦྲེའུའི་པགས་པ་ལ་གཏུམ།། {T2196}༄༅༅། །ཀླུ་གཏོར་རྒྱས་པ་ནི། རིན་པོ་ཆེའི་སྣོད་མཛེས་པའི་ནང་དུ་འབྲུ་སྣ་ཚ
འདིར་གཟིགས་རོགས། ཡི་གེ་ཞིག་ཆད་འཇུག

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/052_རྒྱུད་འགྲེལ།_ཞི.txt
> +[191a.5]འགག་དང་ཤོག་མ་མེད་པ་ཡིས། །མིག་གིས་མཐོང་བའི་ལམ་ལ་འགྲོ་བར་གྱིས། །པ་ཌ་ཧ་མཉྫ་རི་ཞེས་བྱ་བའི་གླུ་དབྱངས་ཊེ་ཎ་ཊེ་ཎ་པའི་ཞབས་ཀྱིའོ། །གྲོང་ཁྱེར་དབུས་ན་བདག་གི་ཁྱིམ་སྟེ་ཁྱིམ་ཚེས་མེད། །ཁྲུ་བ་ལ་ནི་ཟན་མེད་རྟག
དོན་གཅིག་ཡིན་པ་དག་གུག་རྟགས་སུ་མ་བཞག་ཀྱང་ཆོག

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/057_རྒྱུད་འགྲེལ།_ལི.txt
> +[79a.1]མི་བྱད་པའི་ཏིང་ངེ་འཛིན་གང་ལ་མིང་དེ་སྐད་ཅེས་བྱ་བ་དེ་ལ་སྙོམས་པར་འཇུག་པ་ནི། ཕྲིན་ལས་ཀྱི་འོད་ཟེར་ལ་སོགས་པ་བསྐྱེད་པའི་རྣམ་པར་ཐུགས་རྩེ་གཅིག་ཏུ་མཛད་ཅེས་བྱ་བའི་བར་དུའོ། །དེ་བཞིན་གཤེགས་པ་ཐམས་ཅད་ཀྱི་ཕྲི
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[19b.1]རྣལ་འབྱོར་སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2551}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་རྣལ་འབྱོར་བས་འབྱུང་པོའི་གཏོར་མ་སྦྱིན་པ་ནི་གཏོར་མའི་དངོས་པོ་དཔག་བསམ
འདིར་གཟིགས་རོགས། ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་མེད།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
>  [19b.6]ལ་ཡེ་ཤེས་མེ་ཏོག་གི་ཚོམ་བུ་ཡང་ཚུལ་དང་མཐུན་པར་མཛེས་པར་བཀྲམ་སྟེ། དྲི་དང་ལྡན་པར་བྱས་ནས་གང་མཁོ་བའི་ཡོ་བྱད་དང་། མེ་ཏོག་གི་ཚོམ་བུ་དང་། པདྨའི་གདན་ལ་སོགས་པར་བྱིན་གྱིས་བརླབས་ཏེ། གདན་དང་བཅས་པར་དབུལ་བར་བྱ
འདིར་གཟིགས་རོགས། ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་མེད།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[20b.1]མོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་བསྐོར་བ་བྱ་བའི་ཐབས་སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2554}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་ཡན་ལག་བདུན་པས་ཚོགས་བསགས་པའི་
འདིར་གཟིགས་རོགས། ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་མེད།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[23a.3]བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2559}༄༅༅། །འཇམ་དཔལ་གཞོན་ནུར་གྱུར་པ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་རྣལ་འབྱོར་པས་ཤེས་པ་དུག་གསུམ་ལས་བཟློག་པའི་མན་ངག་ནི། དེ་ཡང་རིག་པ་བྱང་ཆུབ་ཀྱི་སེམས་འོད་ག
འདིར་གཟིགས་རོགས། ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་མེད།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[23b.2]འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2560}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །དེ་ལ་སྐྱབས་སུ་འགྲོ་བ་ནི་མཎྜལ་དང་མཆོད་པ་བཤམས་ཏེ། བླ་མ་དང་སངས་རྒྱས་དང་བྱང་ཆུབ་སེམས་དཔའ་ལ་སོགས་པ་རང་གི་མདུན་དུ་ད
འདིར་གཟིགས་རོགས། ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་མེད།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[24b.4]བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2562}༄༅༅། །འཇམ་དཔལ་གཞོན་ནུར་གྱུར་པ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་རྣལ་འབྱོར་བས་བྱང་ཆུབ་ཀྱི་སེམས་བསྒོམ་པ་ནི་རང་གི་ཡི་དམ་གང་ཡིན་པར་བསམས་ལ། དེའི་སྙིང་གར་ཟ
འདིར་གཟིགས་རོགས། ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་མེད།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[27a.6]པ་ལ་བརྟེན་ནས་བྱས་པའོ། །སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ། མཚན་ཡང་དག་པར་བརྗོད་པའི་སྒོ་ནས་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བའི་ཡན་ལག་བཅུ་གཉིས་བསྒོམ་པའི་མན་ངག་རྫོགས་སོ། །{T2567}༄༅༅། །འཇམ་དཔལ་གཞོན་ནུར
འདིར་གཟིགས་རོགས། ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་མེད།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[39b.6]བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །རྒྱ་གར་གྱི་མཁན་པོ་སུ་བཛྲ་དང་། བོད་ཀྱི་ལོ་ཙཱ་བ་ཆོས་ཀྱི་ཤེས་རབ་ཀྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པ། །{T2575}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཨཱརྱ་མཉྫུ་ཤྲཱི་ནཱ་མ་སཾ་གཱི་ཏི་སརྦ་པ
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[43b.5]བསྒྱུར་བའོ། །{T2577}༄༅༅། །ངན་སོང་སྦྱོང་བ་འགྲོ་བ་རིགས་དྲུག་གི་ཆོ་ག་བཞུགས། ། ༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །ངན་སོང་སྦྱོང་བ་འགྲོ་བ་རིགས་དྲུག་གི་ཆོ་ག །ངན་སོང་ཐམས་ཅད་རྣམ་སྦྱོང་བ། །ཚེ་འདས་ལས་སུ
འདིར་གཟིགས་རོགས། ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་མེད།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[107b.1]བྱས་མིན་ཏེ། །སྒྱུ་འཕྲུལ་དྲ་བའི་རྒྱུད་ལས་འོངས། །ཀུན་གྱིས་འཇམ་དབྱངས་ཐོབ་པར་ཤོག། །སློབ་དཔོན་ཤཱནྟིཾ་གརྦྷས་མཛད་པ་རྫོགས་སོ། །{T2584}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཨཱཪྻ་མཉྫུ་ཤྲཱི་ནཱ་མ་ཨཾ་གའི་ཏི་གུ་ཧྱ་བཱནྣོ་པོ
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[150b.1]འགྲེལ་པ་ཡེ་ཤེས་གསལ་བ་ཞེས་བྱ་བ། རྒྱ་གར་གྱི་མཁན་པོ་སྨྲྀ་ཏི་ཛྙཱ་ན་ཀཱི་རྟིས་མཛད་ཅིང་དེ་ཉིད་ཀྱིས་བསྒྱུར་བ་རྫོགས་སོ། །{T2585}༄༅༅། །ཐིག་ག་དབ་པའི་རིམ་པ། འཇམ་དཔལ་ཡེ་ཤེས་སེམས་དཔའ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཉིད
འདིར་གཟིགས་རོགས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/139_མངོན་པ།_ཨི.txt
> +[29b.5]བྱས་པ་དང་། བཻ་ཌཱུརྱ་ལས་བྱས་པ་དང་། ཤེལ་ལས་བྱས་པ་རྣམས་སོ། །ཁང་བཟངས་རྣམ་པར་རྒྱལ་བའི་ཀ་བ་རྣམ་པ་བཞི་(གཙུགས་བཙུགས་)པ་ལ་འདི་ལྟ་སྟེ། གསེར་ལས་བྱས་པ་དང་། དངུལ་ལས་བྱས་པ་དང་། བཻ་ཌཱུརྱ་ལས་བྱས་པ་དང་། ཤེལ་ལས
འདིར་གཟིགས་རོགས། ,མི་འདུག

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/150_འདུལ་བ།_དུ.txt
> +[164b.5]ལེན་བྱེད་དུ་གཞུག་པར་བྱའོ། །ཁྱིམ་པ་དག་ཀྱང་(འདྲིམ་,འབྲིམ་)དུ་གཞུག་པར་བྱ་ཞིང་། དགེ་སློང་གིས་དང་པོར་གཟུང་ཞིང་ཁྱིམ་པས་ཕྱིས་གཟུང་བར་བྱ་བའོ། །དགེ་སློང་དག་ལས་བླངས་པ་གང་ཡིན་པ་དེ་དག་གི་བྱིན་ལེན་ནི་དེ་ཉ
པོད་གཅིག་གི་ནང་དུ་དོགས་གཞི་པ་མང་པོ་ཡོད་ན་གཅིག་ལས་དོགས་རྟགས་མ་བརྒྱབས་ཀྱང་ཆོག

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/157_འདུལ་བ།_ཚུ.txt
> +[143b.7]མཁས་པའི་མཁས་པ་དང་། བསྟན་བཅོས་མ་ཐོས་ཀྱང་སྔོན་གོམས་པའི་ཤེས་པ་དང་ལྡན་པ་མཛངས་པ་དག་གིས་རིག་པར་བྱ་བའི་ཐ་ཚིག་གོ། །སྨས་པ་ཞེས་བྱ་བ་ནི་སེམས་རབ་ཏུ་བསྔངས་སྙེ(བསྡངས་,སྡང་)པའོ། །ལོ་ཞེས་བྱ་བའི་སྒྲ་ནི་མི་གནས
འདིར་གཟིགས་རོགས། འདིར་ཡི་གེ་གཅིག་ལྷག་མ་ཡིན་པ་དང་དོགས་རྟགས་དེ་མི་དགོས།

2018-09-21 08:00 UTC, rekongrabten commented on derge-tengyur-tags/195_སྒྲ་མདོ།_ལེ.txt
> +[262b.2]ཤུགས་སོ། །སྱདཿ། དངོས་པོ་ལ་གྷཉའོ། །ལྔ་པ་དབྱིའོ། །ཨའི་ཨུ་བ་དྷཱ་ཞེས་པས་རིང་པོར་མི་འགྱུར་ཏེ། མིང་སྔ་མ་ཅན་གྱི་ཆོ་ག་ནི་རྟག་ཏུ་མ་ཡིན་ནོ་ཞེས་པའི་ཚིག་གི་ར་རོ། །རྒྱུག་པ་ལ་ཞེས་པ་ཅི་ཞེ་ན། ཏཻ་ལ་སྱ་སྱནྡཿ།
འདིར་གསུབ་ཉེས་ཤོར་འདུག

2018-09-21 09:27 UTC, Sangkhar commented on derge-tengyur-tags/010_རྒྱུད་འགྲེལ།_ཏ.txt
> +[344a.3]མ་ཧཱ་མ་ཡུ་ར་རཱ་ཛཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་མ་ཧཱ་དྷྭ་ར་རྩྭ་ཡེ་སྭཱ་ཧཱ། ཨོཾ་མནྟྲ་པ་ཏཱ་ཛྭ་སྭཱ་ཧཱ། ཨོཾ་མ་ཧཱ་མ་ཡུ་རི་བིརྱ་ར་རྙི་ཡེ་སྭཱ་ཧཱ། ཨོཾ་མ་ཡུ་ར་ཀ་ཏཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་ནནྡ་ནཱ་ག་རཱ་ཛཱ་ཡ་སྭཱ་ཧཱ། ཨོཾ་ཨུ་པ་ནནྡ་ན
སྔགས་ཡིག་མང་པོ་ཞིག་ནོར་བ་བཟོས་ཡོད།

2018-09-21 09:53 UTC, Sangkhar commented
ཚང་མ་བཟོས་ཚར་ཡོད།

2018-09-24 02:21 UTC, rekongrabten requested changes

2018-09-24 02:21 UTC, rekongrabten commented on derge-tengyur-tags/026_རྒྱུད་འགྲེལ།_ར.txt
> +[314b.6]མཛེས་ཤིང་། རང་འོད་ཀྱི་རིག་མ་དང་འཁྲིལ་བའི་ཚུལ་གྱིས་ཞལ་སྦྱོར་ཏེ་འགྱིང་བག་གི་རྣམ་པས་བཞུགས་པའོ། །མེ་མཚམས་ཀྱི་རེའུ་མིག་ལ་རྡོ་རྗེ་གླིང་བུ་མ་བཻཌཱུ་རྱའི་མདོག་ཅན་རྡོ་རྗེས་མཚན་པའི་གླིང་བུ་སྒྲོགས་པའོ། །
འདི་འདི་འདྲ་ཡིན་ནམ།

2018-09-24 02:21 UTC, rekongrabten commented on derge-tengyur-tags/027_རྒྱུད་འགྲེལ།_ལ.txt
> +[104b.3]སྐུ་མདོག་དཀར་པོ་བྱང་ཆུབ་མཆོག་གི་ཕྱག་རྒྱ་ཅན། དཔྲལ་བའི་སྟེང་དུ་མི་བསྐྱོད་པ། སྐུ་མདོག་དཀར་པོ་ས་གནོན་གྱི་ཕྱག་རྒྱ་ཅན་གྱིས་བརྒྱན་པ། གཡས་སུ་རིན་ཆེན་འབྱུང་ལྡན་བཻཌཱུ་རྱའི་མདོག་ཅན་མཆོག་སྦྱིན་གྱི་ཕྱག་རྒ
འདིར་གཟིགས་རོགས།

2018-09-24 02:21 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[19b.1]རྣལ་འབྱོར་སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2551}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་རྣལ་འབྱོར་བས་འབྱུང་པོའི་གཏོར་མ་སྦྱིན་པ་ནི་གཏོར་མའི་དངོས་པོ་དཔག་བསམ
འདིར་གཟིགས་རོགས།

2018-09-24 02:21 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[19b.7]པའི་མཎྜལ་གྱི་ཆོ་ག །སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2553}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །སྒྲུབ་པ་པོ་དད་པ་དང་ལྡན་པའི་གང་ཟག་གིས་མཚན་ཡང་དག་པར་བརྗོད་པའི་སྒོ་ནས་བསྐོར་བ་བྱེད་
འདིར་གཟིགས་རོགས།

2018-09-24 02:21 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[20b.1]མོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་བསྐོར་བ་བྱ་བའི་ཐབས་སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2554}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་ཡན་ལག་བདུན་པས་ཚོགས་བསགས་པའི་
འདིར་གཟིགས་རོགས།

2018-09-24 02:21 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
>  [22b.6]པས་མི་གཙང་བའི་ངོ་བོ་ཡིན་ཏེ། ཆུ་སེར་དང་། བད་ཀན་དང་། ཀླད་པ་དང་། བཤང་གཅི་དང་། རྣག་ཁྲག་དང་། སྣབས་ལུད་དང་། ཀེང་རུས་ལ་སོགས་པས་ཡོངས་སུ་གང་བ། དེ་ཡང་འགྱུར་བའི་ཆོས་ཅན། དེ་ཡང་ཡིད་བརྟན་དུ་མི་རུང་བ།
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten requested changes
ཁྱེད་ལ་དྲི་བ་དང་ཡང་བསྐྱར་བལྟ་དགོས་པ་ཁག་ང་དགུ་བཏང་ཡོད། ད་དུང་སཾ་སྐྲྀ་ཏ ཡོད་ཚད་སཾསྐྲྀཏ  ཞེས་པར་བཟོས་ཡོད་པ་ཁག་གཅིག་ལ་རྟགས་བཀོད་མེད། ཡང་བསྐྱར་སཾསྐྲྀཏ བྲིས་ནས་འཚོལ་ཞིབ་ཀྱིས་ཡང་བསཀྻར་གཟིགས་རོགས་མཁྱེན།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/014_རྒྱུད་འགྲེལ།_པ.txt
> +[139b.4]ཅེས་པས་བཅོམ་ལྡན་འདས་དང་པོའི་སྐྱེས་བུ་གོ་བར་བྱས་ཏེ། ཨོ་ཨ་ཨཱ་ཨེ་ཨེ་ཨར་ཨཱར་ཨོ་ཨཽ་ཨལ་ཨཱལ་ཨཾ་ཨཿབིཥ་ཡ་ཨིནྡིྲཡ་བི་ཤོདྷ་ནི་སྭཱ་ཧཱ། ཞེས་པའི་སྔགས་ཀྱིས་དེ་ཁོ་ནའི་རང་བཞིན་རྡོ་རྗེ་བྱིན་ལ་དེ་ནས་ལྔར་དབང་བསྐ
འདི་ཨིནྡྲི་ཡ་རེད་འདུག

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/014_རྒྱུད་འགྲེལ།_པ.txt
> +[224a.4]བ་བཞེས་ནས་མཛད་པ་རྫོགས་སོ།། །།པཎྜི་ཏ་སོ་མ་ནཱ་ཐ་དང་། ལོ་ཙཱ་བ་འབྲོ་ཤེས་རབ་གྲགས་ཀྱིས་བསྒྱུར་པའོ། {T1372}༄། །སྦྱོར་བ་ཡན་ལག་དྲུག་གི་མན་ངག་བཞུགས།། ༄༅༅། །དཔལ་ལྡན་བླ་མ་དམ་པ་རྣམས་དང་དཔལ་དུས་ཀྱི་འཁོར་ལོ
འདི་བསྒྱུར་བའོ།། འདི་འདྲ་རེད་འདུག

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/016_རྒྱུད་འགྲེལ།_བ.txt
> +[246b.1]རྒྱུད་འགྲེལ་བསྒྱུད། {T1404}༄༅༅། །རྒྱ་གར་སྐད་དུ། རཏྣ་ཚ་ད་ནཱ་མ་པཉྩི་ཀཱ། བོད་སྐད་དུ། རིན་པོ་ཆེའི་ཚོགས་ཞེས་བྱ་བའི་དཀའ་འགྲེལ། དཔལ་རྡོ་རྗེ་མཁའ་འགྲོ་ལ་ཕྱག་འཚལ་ལོ། །སྣ་ཚོགས་པདྨའི་གེ་སར་རྡུལ་གྱིས་སྐུ་
རྒྱུད་འགྲེལ་བསྒྱུར།། འདི་འདྲ་རེད།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/018_རྒྱུད་འགྲེལ།_ཙ.txt
> +[136a.3]བཞིའི་ཁྱད་པར་དང་། ཡུལ་གྱི་སྤྱོད་པ་སྒྲ་ཉམས་དང་སཾསྐྲྀཏའི་སྐད་དང་། སངས་རྒྱས་སྤྱན་གྱི་རྒྱུད་མཉམ་སྦྱོར་དང་། མཱ་མ་ཀཱིའི་རྒྱུད་དགྱེས་རྡོར་དང་། གོས་དཀར་མོའི་རྒྱུད་བདེ་མཆོག་དང་། སྒྲོལ་མའི་རྒྱུད་སྒྲོལ་
འདིར་མ་དཔེར་ནང་སཾ་སྐྲྀ་ཏའི་  ཞེས་གསལ།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/023_རྒྱུད་འགྲེལ།_ཟ.txt
> +[78b.7]ཤེས་རབ་སྣང་བས། །ཕྱོགས་བཅུར་གསལ་བར་བྱེད་པར་ཤོག །རང་བྱིན་གྱིས་བརླབ་པའི་རིམ་པའི་མན་ངག་གི་སྒྲུབ་ཐབས་རྣལ་འབྱོར་གྱི་དབང་ཕྱུག་ཆེན་པོ་ཀུ་མཱ་ར་ཤྲཱི་དཔལ་ན་ལེནྡྲའི་གཙུག་ལག་ཁང་དུ་སཾསྐྲྀཏའི་སྐད་དུ་མཛད་པ་རྫ
སཾ་སྐྲྀ་ཏའི  མ་དཔེར་འདི་ལྟར་གསལ།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/026_རྒྱུད་འགྲེལ།_ར.txt
> +[44b.1]བར་ཞེས་པའོ། །སེན་མོ་རྗེས་དང་ཆགས་པའི་སྐུ། །ཞེས་པ་ནི་བདེ་བ་ཆེན་པོ་བསྐྱེད་པར་བྱ་བའི་དོན་དུ་ལྷ་མོ་རྣམས་ཀྱིས་བཅོམ་ལྡན་འདས་ཀྱི་སྐུ་ལ་སེན་མོས་བཏབ་པའོ། །དེ་དང་འདྲ་བའི་རྡོ་རྗེ་བདུད་རྩི་ལ་ཕྱག་འཚལ། །ཞེས་
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/026_རྒྱུད་འགྲེལ།_ར.txt
> +[127a.6]འགྱུར་བའི་སྔགས་བྲི་བར་བྱ་ཞེས་སྦྱར་རོ། །སྔགས་གསུངས་པ། ཨོཾ་བུདྡྷ་ཀ་པཱ་ལི་ཞེས་པ་ལ་སོགས་པ་སཾསྐྲྀཏ་དང་། ཕལ་པ་བསྲེས་པའི་སྔགས་མུ་ར་དྷཱ་པྲ་ན་ཛ་ཨིའི་མཐར་ཐུག་པར་བྲི་བར་བྱའོ། །རི་སྐེགས་ཀྱི་སྙིང་པོའི་སྔག
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/026_རྒྱུད་འགྲེལ།_ར.txt
> +[314b.6]མཛེས་ཤིང་། རང་འོད་ཀྱི་རིག་མ་དང་འཁྲིལ་བའི་ཚུལ་གྱིས་ཞལ་སྦྱོར་ཏེ་འགྱིང་བག་གི་རྣམ་པས་བཞུགས་པའོ། །མེ་མཚམས་ཀྱི་རེའུ་མིག་ལ་རྡོ་རྗེ་གླིང་བུ་མ་བཻཌཱུ་རྱའི་མདོག་ཅན་རྡོ་རྗེས་མཚན་པའི་གླིང་བུ་སྒྲོགས་པའོ། །
འདིར་མ་དཔེར་ཚེག་མི་འདུག

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/027_རྒྱུད་འགྲེལ།_ལ.txt
> +[104b.3]སྐུ་མདོག་དཀར་པོ་བྱང་ཆུབ་མཆོག་གི་ཕྱག་རྒྱ་ཅན། དཔྲལ་བའི་སྟེང་དུ་མི་བསྐྱོད་པ། སྐུ་མདོག་དཀར་པོ་ས་གནོན་གྱི་ཕྱག་རྒྱ་ཅན་གྱིས་བརྒྱན་པ། གཡས་སུ་རིན་ཆེན་འབྱུང་ལྡན་བཻཌཱུ་རྱའི་མདོག་ཅན་མཆོག་སྦྱིན་གྱི་ཕྱག་རྒ
འདིར་ཡང་ཚེག་མི་གསལ།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/028_རྒྱུད་འགྲེལ།_ཤ.txt
> +[102b.7]ཕྱོགས་ཀྱི་པཎ་ཆེན་དཱ་ན་ཤཱི་ལ་ལས། ཤཱཀྱའི་དགེ་སློང་རིག་པ་འཛིན་པ་ཁུ་རྣལ་འབྱོར་པས་འོན་དམར་སཾསྐྲྀཏའི་སྐད་ལས་རང་འགྱུར་དུ་གསུངས་སོ།། {T1736}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཏཱ་ར་དེ་བ་པཉྩ་སཱ་དྷ་ནཾ། བོད་སྐད་དུ། སྒ
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/031_རྒྱུད་འགྲེལ།_ཨ.txt
> +[33b.1]ཚུལ་གྱིས་སོ། །བརྗོད་པའི་རྣམ་པ་གསུམ་པོ་འཛིན་པའི་དོན་རྣམ་པ་གསུམ་གསུངས་པ་རྣམས་མངོན་པར་རྗོད་པར་བྱེད་པ་ཡིན་པ་ཉིད་ཀྱིས་གཞུང་ལ་ཡང་དམ་པའི་ཆོས་སོ། །ཡོན་ཏན་སྨྲ་བ་ནི་ཡོན་ཏན་བརྗོད་པ་སྟེ། དེ་རྣམས་སྨྲ་བ་ནི་
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/049_རྒྱུད་འགྲེལ།_ཚི.txt
> +[226a.1]ཨོཾ་ཧྲཱིཿབྷྲཱུཾ་བཛྲ་ཨཱ་ཡུ་རྫྙཱ་ན་ཨཱ་བེ་ཤ་ཡ་ཨཱཿཞེས་མང་དུ་བརྗོད་པས། ལུས་ངག་ཡིད་གསུམ་ལ་ཕེབས་པར་འགྱུར་རོ། །དེའི་རྟགས་ནི་འཕར་བ་དང་གར་བྱེད་པ་དང་། །སཾསྐྲྀཏའི་སྐད་དང་རྡོ་རྗེའི་གླུ་དང་། རྟོག་མེད་ཏིང་འ
འདིར་ཡང་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/063_རྒྱུད་འགྲེལ།_ཁུ.txt
> +[193a.6]སཾསྐྲྀཏ་དང་། སྐད་ཐ་མལ་པ་དང་། ཟུར་བཅག་པ་དང་། ཤ་ཟའི་སྐད་དང་། མ་ག་དྷཱ་པའི་སྐད་དང་། ཟུང་དུ་འཇུག་པའི་སྐད་དང་། ཐ་དད་པ་ལ་སོགས་པའི་སྐད་ཐམས་ཅད་ལ་མཁས་ཤིང་ཐམས་ཅད་དུ་ཚིག་གིས་སྟོན་པས་ན་ཚིག་ལ་དབང་བའོ། །དེ་
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[68b.1]པར་བཅོམ་ལྡན་འདས་ཀྱིས་རྡོ་རྗེའི་མགུར་བཞེས་པ་སྟེ། སཾསྐྲྀཏའི་སྐད་དུ་མ་བཞེས་པར་རྡོ་རྗེའི་ཚིག་ཏུ་བསྒྱུར་བས་དེ་དབང་པོ་རྟུལ་པོའི་འཁོར་རྣམས་ཀྱིས་མ་གོ་ནས་དབང་པོ་རྟུལ་བའི་འཁོར་ཉེ་བར་བཟུང་བའི་ཕྱིར་དེ་མ་ཐ
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[19b.1]རྣལ་འབྱོར་སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2551}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་རྣལ་འབྱོར་བས་འབྱུང་པོའི་གཏོར་མ་སྦྱིན་པ་ནི་གཏོར་མའི་དངོས་པོ་དཔག་བསམ
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> -[19b.7]པའི་མཎྜལ་གྱི་ཆོ་ག །སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། ། {T2553}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །སྒྲུབ་པ་པོ་དད་པ་དང་ལྡན་པའི་གང་ཟག་གིས་མཚན་ཡང་དག་པར་བརྗོད་པའི་སྒོ་ནས་བསྐོར་བ་བྱེད
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[19b.7]པའི་མཎྜལ་གྱི་ཆོ་ག །སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2553}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །སྒྲུབ་པ་པོ་དད་པ་དང་ལྡན་པའི་གང་ཟག་གིས་མཚན་ཡང་དག་པར་བརྗོད་པའི་སྒོ་ནས་བསྐོར་བ་བྱེད་
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[20b.1]མོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་བསྐོར་བ་བྱ་བའི་ཐབས་སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2554}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་ཡན་ལག་བདུན་པས་ཚོགས་བསགས་པའི་
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[22b.5]མཛད་པ་རྫོགས་སོ། །{T2558}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། འཁོར་བ་ལས་ཡིད་བྱུང་བ་ནི་དེ་བཞིན་དུ་ནང་བཅུད་ཀྱི་སེམས་ཅན་དང་། བདག་གི་གཟུགས་ཀྱི་ཕུང་པོ་ཡང་སྤྱི་བོ་ནས་རྐང་པའི་མཐིལ་ཡན་ཆད་དུ་བརྟགས་
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[23a.3]བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2559}༄༅༅། །འཇམ་དཔལ་གཞོན་ནུར་གྱུར་པ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་རྣལ་འབྱོར་པས་ཤེས་པ་དུག་གསུམ་ལས་བཟློག་པའི་མན་ངག་ནི། དེ་ཡང་རིག་པ་བྱང་ཆུབ་ཀྱི་སེམས་འོད་ག
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[23b.2]འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2560}༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །དེ་ལ་སྐྱབས་སུ་འགྲོ་བ་ནི་མཎྜལ་དང་མཆོད་པ་བཤམས་ཏེ། བླ་མ་དང་སངས་རྒྱས་དང་བྱང་ཆུབ་སེམས་དཔའ་ལ་སོགས་པ་རང་གི་མདུན་དུ་ད
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[24b.4]བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །{T2562}༄༅༅། །འཇམ་དཔལ་གཞོན་ནུར་གྱུར་པ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་རྣལ་འབྱོར་བས་བྱང་ཆུབ་ཀྱི་སེམས་བསྒོམ་པ་ནི་རང་གི་ཡི་དམ་གང་ཡིན་པར་བསམས་ལ། དེའི་སྙིང་གར་ཟ
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[27a.6]པ་ལ་བརྟེན་ནས་བྱས་པའོ། །སློབ་དཔོན་འཇམ་དཔལ་བཤེས་གཉེན་གྱིས་མཛད་པ། མཚན་ཡང་དག་པར་བརྗོད་པའི་སྒོ་ནས་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བའི་ཡན་ལག་བཅུ་གཉིས་བསྒོམ་པའི་མན་ངག་རྫོགས་སོ། །{T2567}༄༅༅། །འཇམ་དཔལ་གཞོན་ནུར
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[30b.1]གཏན་ལ་ཕབ་པའོ། {T2570}༄། །མཉམ་པར་བཞག་པའི་རིམ་པའི་མན་ངག་བཞུགས། ༄༅༅། །འཕགས་པ་འཇམ་དཔལ་གཞོན་ནུར་གྱུར་པ་ལ་ཕྱག་འཚལ་ལོ། །མཚན་ཡང་དག་པར་བརྗོད་པའི་རྣལ་འབྱོར་བས། ནམ་གྱི་ཆ་སྨད་རང་གི་རྒྱུད་ལ་བརྟག་པ་ནི་རང་ཉི
འདིར་ཤད་གཉིས་ཡོད།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[39b.6]བཤེས་གཉེན་གྱིས་མཛད་པ་རྫོགས་སོ། །རྒྱ་གར་གྱི་མཁན་པོ་སུ་བཛྲ་དང་། བོད་ཀྱི་ལོ་ཙཱ་བ་ཆོས་ཀྱི་ཤེས་རབ་ཀྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པ། །{T2575}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཨཱརྱ་མཉྫུ་ཤྲཱི་ནཱ་མ་སཾ་གཱི་ཏི་སརྦ་པ
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[43b.5]བསྒྱུར་བའོ། །{T2577}༄༅༅། །ངན་སོང་སྦྱོང་བ་འགྲོ་བ་རིགས་དྲུག་གི་ཆོ་ག་བཞུགས། ། ༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །ངན་སོང་སྦྱོང་བ་འགྲོ་བ་རིགས་དྲུག་གི་ཆོ་ག །ངན་སོང་ཐམས་ཅད་རྣམ་སྦྱོང་བ། །ཚེ་འདས་ལས་སུ
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[106a.3]གིས་ཀྱང་ཞུས་ནས་གཏན་ལ་ཕབ་སྟེ་འགྱུར་ཕྱི་མ་ཡང་ཡིན་ནོ། །{T2583}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཨཱ་ཪྻ་མཉྫུ་ཤྲཱི་པྲ་ཏི་ཥཋ་བི་དྷིཿ། བོད་སྐད་དུ། འཕགས་པ་འཇམ་དཔལ་གྱི་རབ་ཏུ་གནས་པའི་ཆོ་ག །འཇམ་དཔལ་གཞོན་ནུར་གྱུར་པ་ལ་
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[107b.1]བྱས་མིན་ཏེ། །སྒྱུ་འཕྲུལ་དྲ་བའི་རྒྱུད་ལས་འོངས། །ཀུན་གྱིས་འཇམ་དབྱངས་ཐོབ་པར་ཤོག། །སློབ་དཔོན་ཤཱནྟིཾ་གརྦྷས་མཛད་པ་རྫོགས་སོ། །{T2584}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཨཱཪྻ་མཉྫུ་ཤྲཱི་ནཱ་མ་ཨཾ་གའི་ཏི་གུ་ཧྱ་བཱནྣོ་པོ
འདིའི་ཤད་གཉིས་སྦྲེལ་ནས་སྟོང་པ་འཇོག་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/075_རྒྱུད་འགྲེལ།_ཕུ.txt
> +[202b.2]ཇི་སྲིད་དུ་ཟླ་བ་དྲུག་གི་བར་དུ་བཟླས་པར་བྱ་བའི་སྔགས་ཀྱང་འདི་དག་ཡིན་ཏེ། ཨོཾ་བཛྲ་ཏཱིཀྵྞ་ཧཾ་ཉི་མ་རེ་རེ་ཞིང་ཁྲི་ཕྲག་རེ་བཟླས་པར་བྱ་བའོ། །དེ་དག་གིས་བླུན་པོ་ཡང་དག་གི་བདག་པོར་འགྱུར་རོ། །བློ་རྣོ་བ་དང་གཞ
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/076_རྒྱུད་འགྲེལ།_བུ.txt
> +[48a.2]སོགས་སྒྲིབ་ཟད་སྔགས་པའི་ཆོས་ལྡན་སྐད་ཐབས་གང་གིས་འདུལ་བས་རྟག་ཏུ་ཆོས་ནི་སྟོན་གྱུར་ཅིག །མོས་པའི་ཁྱད་པར་གྱིས་རྒྱ་གར་ན་སྒྲུབ་ཐབས་བསྡུས་པ་འགའ་ཞིག་སྲིད་ན་ཡང་གཞུང་སྙན་དངགས་དང་ལྡན་པས་སཾསྐྲྀཏ་མཆོག་ཏུ་གྱུར
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/086_ཤེར་ཕྱིན།_ཇ.txt
> +[164b.2]སུན་འབྱིན་པར་བརྗོད་པར་མི་བྱ་ཞིང་སངས་རྒྱས་ཀྱི་བཀའ་མ་ཡིན་ནོ། །ཞེས་བརྒལ་བར་མི་བྱ། བདག་ཅག་གི་སྡེ་སྣོད་གསུམ་དུ་ཁྱེད་ཀྱི་ཐེག་པ་མི་སྣང་བ་དང་སཾསྐྲྀཏའི་སྐད་ཀྱིས་མ་གསུངས་པ་ཉིད་ཡིན་པའི་ཕྱིར་སངས་རྒྱས་ཀྱི
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/090_ཤེར་ཕྱིན།_ད.txt
> +[92b.4]ཞེས་པ་ནི་ཆུང་ངུའི་ཆེན་པོའོ། །དེ་ལྟ་བས་ན་ཞེས་པ་ལ་སོགས་པ་སྟེ། གསེར་དང་། དངུལ་དང་། ་དང་། སྤུག་དང་། རྡོའི་སྙིང་པོ་དང་། མུ་ཏིག་དམར་པོ་དང་། ཀརྐེ་ཏ་ན་སྟེ་རིན་པོ་ཆེ་སྣ་བདུན་ནོ། །དེའི་གཞི་ནི་དེའི་རྒྱུས
འདིར་རྦད་དེ་གསུབ་འདུག

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/108_དབུ་མ།_ཧ.txt
> +[91a.1]ཕྱེ་བ་དང་ནང་ན་སྙིང་པོར་གྱུར་པའི་དངོས་པོ་ཆུང་ཟད་མེད་པར་ཤེས་ནས་གུས་པ་མ་ཡིན་པ་ཆེན་པོས་འདོར་བ་དེ་བཞིན་དུ་ཇི་སྲིད་བརྡའི་ཐ་སྙད་ཀྱི་དོན་ཡོངས་སུ་ཤེས་པ་མ་སྐྱེས་པ་དེ་སྲིད་དུ་སཾསྐྲྀཏའི་སྐད་ལ་གུས་པར་བྱེད་
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/108_དབུ་མ།_ཧ.txt
> +[92a.2]ཅི་ཞིག་བྱ་སྟེ། དེ་ལ་དགོས་པ་ཅི་ཞིག་ཡོད་ཅེས་བྱ་བ་ཡིན་ནོ། །དོན་དེ་ཉིད་གསལ་བར་བྱ་བའི་ཕྱིར། གླང་པོ་དང་ནི་ཞེས་བྱ་བ་ལ་སོགས་པ་སྨོས་ཏེ། ཚིག་ལ་སོགས་པ་དང་ལྡན་པའི་སཾསྐྲྀཏས་ས་སྲུང་གི་བུ་དང་ལྷའི་བུ་མོ་ཁྱད་པ
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/108_དབུ་མ།_ཧ.txt
> +[109a.1]{T3897}༄༅༅། །རྒྱ་གར་སྐད་དུ། སཾསྐྲྀཏ་ཨ་སཾསྐྲྀཏ་བི་ནི་ཥྩ་ཡ་ནཱ་མ། བོད་སྐད་དུ། འདུས་བྱས་དང་འདུས་མ་བྱས་རྣམ་པར་ངེས་པ་ཞེས་བྱ་བ། སངས་རྒྱས་ལ་ཕྱག་འཚལ་ལོ། །ཆོས་རྣམས་སྤྲོས་དང་བཅས་པ་ནི། །དཔལ་ལྡན་རང་ཉིད་ཀུ
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/125_སེམས་ཙམ།_མི.txt
> +[203b.1]སེམས་དཔའ་ཚོལ་བར་བྱེད་དེ། བདག་ཉིད་སཾསྐྲྀཏའི་སྐད་ལ་མཁས་པའི་སྒོ་ནས་བདག་ལ་མཁས་པ་གཞན་དག་ཡིད་ཆེས་པར་བྱ་བ་དང་། སྒྲའི་གཙུག་ལག་ཤེས་པར་རློམ་པའི་མུ་སྟེགས་པ་དག་ཚར་གཅད་པར་བྱ་བ་དང་། དོན་གཅིག་ལ་ངེས་པའི་ཚིག་
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/146_མངོན་པ།_ཇུ.txt
> +[82b.1]སྨྲས་པ། མ་བདག་ཅག་བཀྲེས་ཀྱིས་ཟན་བྱིན་ཅིག །དེ་གཉེན་རྣམས་ལ་ཡོངས་སུ་(འདྲིམ་,འབྲིམ་)པས་ངལ་བས་ཁྱོད་ཅག་རང་གཉིས་ལོང་ལ་ཟོ་ཞིག་ཅེས་སྨྲས་སོ། །བུས་སྨྲས་པ། ཁྱོད་གསལ་ཤིང་ལ་བསྐྱོན་ནམ་ཞེས་སྨྲས་སོ། །བུ་མོས་སྨྲ
འདི་གཉིས་དོན་གཅིག་ཡིན་པས་དོགས་རྟགས་མ་བཞག་ན་འགྲིག

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/149_མངོན་པ།_ཐུ.txt
> +[77a.5]སོ། །དེ་དག་གིས་ཚིག་རྐང་རེ་རེ་ཐོས་པས་རྒྱུན་དུ་ཞུགས་པའི་འབྲས་བུ་ཐོབ་པར་གྱུར་ཏོ། །གཞན་དག་ནི་མགོན་མེད་ཟས་སྦྱིན་ཡན་ལག་བརྒྱད་པའི་གསོ་སྦྱོང་གི་དུས་སུ་ཟས་(འདྲིམ་,འབྲིམ་)པས་བྲེལ་ཏེ་དུས་ཡོལ་ནས་ཟས་ཆད་པ་ལ
འདི་གཉིས་དོན་གཅིག་ཡིན་པས་དོགས་རྟགས་མ་བཞག་ན་འགྲིག

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/149_མངོན་པ།_ཐུ.txt
> +[82b.7]ཇི་ལྟར་རྗེས་སུ་མཐུན་པར་འབྲེལ་པ་བཀོད་པས་ནི་འདི་དང་མ་དང་ཞེས་བྱ་བ་ལ་སོགས་པའི་ཚིག་བཞིས་གོ་རིམས་བཞིན་དུ་བདེན་པ་བཞི་བསྟན་ཏོ། །དེ་ལས་སཾསྐྲྀཏའི་ཚུལ་གྱིས་ནི་ཨེ་ལས་འདི་ཞེས་བྱ་བ་སྟེ་འགོ་བའི་ནད་ལ་བྱའོ། །ད
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/150_འདུལ་བ།_དུ.txt
> +[164b.2]ཁྲི་དང་། ཁྲིའུ་དང་། ཐུ་བ་དང་། ལྷུང་བཟེད་བཞི་ཉིད་ལྔ་པའོ། །མེས་རུང་བར་བྱ་བ་ནི་ཕུང་པོར་བྱས་ཏེ། མེས་གནས་པ་གཉིས་སམ། གསུམ་དུ་རེག་པར་བྱས་ནས་ཐམས་ཅད་རུང་བར་འགྱུར་རོ། །མཚོན་དང་སེན་མོས་ནི་རེ་རེ་ནས་སོ། །
འདི་ཡང་གཅིག་པ་རེད།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/151_འདུལ་བ།_ནུ.txt
> +[1b.3]ནི་སྔ་མ་བཞིན་ནོ། །སོ་སོར་བཤགས་པར་བྱ་བའི་ཆོས་ནི་བཞི་སྟེ། དགེ་སློང་མ་ལས་ཟས་ལེན་པའི་སོ་སོར་བཤགས་པར་བྱ་བ་དང་། གྲལ་རིམས་སུ་མ་ཕེབས་པར་(འདྲིམ་,འབྲིམ་)དུ་འཇུག་པ་མ་བཟློག་པར་ཟ་བའི་
འདི་ཡང་གཅིག་པ་རེད།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/151_འདུལ་བ།_ནུ.txt
> +[4a.1]པོ་ཆེ་ན་འདུག་པས། དགེ་སློང་མ་ཉེ་དུ་མ་ཡིན་པ་ལ་དེར་འདུ་ཤེས་པས། དགེ་སློང་མ་དེ་རང་གི་ལག་གིས་མི་(འདྲིམ་,འབྲིམ་)པའི་རྣམ་པས་བསྒྲུབས་ཤིང་ཕུལ་བའི་བཅའ་བའམ། བཟའ་བ་དགེ་སློང་དེས་རང་གི་ལག་གིས་བླངས་ཏེ། གནས་གང་
འདི་ཡང་གཅིག་པ་རེད།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/151_འདུལ་བ།_ནུ.txt
> +[201a.3]པ་ལྔ་སྟེ། གཙུག་ལག་ཁང་འདི་རེ་ཞེས་བྱ་བ་དང་། གཙུག་ལག་ཁང་ལྟོས་ཤིག་ཅེས་བྱ་བ་དང་། གནས་མལ་འདི་རེ་ཞེས་བྱ་བ་དང་། གནས་མལ་ལོང་ཤིག་ཅེས་བྱ་བ་དང་། ལྡེ་མིག་ཀྱོག་པོ་སྦྱིན་པའོ། །བཅོལ་བར་མི་བྱ་བ་རྣམ་པ་ལྔ་སྟེ།
འདིར་བསྐྱར་དུ་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/153_འདུལ་བ།_ཕུ.txt
> +[59a.4]བཅུག་ནས་ཞེས་བྱ་བ་ནི་གཞན་ནོ། །མ་བསྡུས་སམ་ཞེས་བྱ་བ་ནི་རང་གིས་སོ། །སྡུད་དུ་མ་བཅུག་གམ་ཞེས་བྱ་བ་ནི་གཞན་ནོ། །དགེ་སློང་འཁོད་བ་ལ་ཞེས་བྱ་བ་ནི་དེ་ན་དགེ་སློང་གང་འདུག་པ་ལའོ། །མ་བཅོལ་བར་ཞེས་བྱ་བ་ནི་བཅོལ་བ་
འདིར་བསྐྱར་དུ་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/153_འདུལ་བ།_ཕུ.txt
> -[60a.5]རྫོགས་པ་མ་གཏོགས་པ་དགེ་སློང་བསྙེན་པར་རྫོགས་པ་རང་བཞིན་དུ་གནས་པ། ལྟ་བ་དང་མཚན་མཐུན་པ་ལ་བཅོལ་བ་རྣམ་པ་ལྔ་པོ་གཙུག་ལག་ཁང་འདེ་རེ་ཞེས་བྱ་བ་དང་། གཙུག་ལག་ཁང་ལྟོས་ཤིག་ཅེས་བྱ་བ་དང་། གནས་མལ་འདེ་རེ་ཞེས་བྱ་བ་ད
འདིར་བསྐྱར་དུ་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/153_འདུལ་བ།_ཕུ.txt
> +[60b.5]བཅས་པ་དང་། རྒས་པ་དང་། ན་བ་དང་། བསྙེན་པར་མ་རྫོགས་པ་རྣམས་ལ་བཅོལ་བ་ལ་ཉེས་བྱས་སོ། །བཅོལ་བ་རྣམ་པ་ལྔ་པོ་གཙུག་ལག་ཁང་འདི་རེ་ཞེས་བྱ་བ་དང་། གཙུག་ལག་ཁང་ལྟོས་ཤིག་ཅེས་བྱ་བ་དང་། གནས་མལ་འདེ་རེ་ཞེས་བྱ་བ་དང་།
འདིར་བསྐྱར་དུ་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/153_འདུལ་བ།_ཕུ.txt
> +[68a.5]བྱ་བ་དང་། གཙུག་ལག་ཁང་ལྟོས་ཤིག་ཅེས་བྱ་བ་དང་། གདིང་བ་འདི་རེ་ཞེས་བྱ་བ་དང་། གདིང་བ་སྡུས་ཤིག་ཅེས་བྱ་བ་དང་། སྒོ་ལྕགས་ཆུག་ཤིག་ཅེས་བྱ་བ་དག་ལས་གང་ཡང་རུང་བ་མ་བྱས་པ་ལ་ན་སྨད་པ་མེད་དོ། །བསོད་སྙོམས་ཀྱི་དོན་
འདིར་བསྐྱར་དུ་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/153_འདུལ་བ།_ཕུ.txt
> +[68a.4]ཡུལ་ནི་དགེ་སློང་ངོ་ཚ་མེད་པ་དང་། ནད་དང་བཅས་པ་དང་། རྒས་པ་དང་། ན་བ་དང་། བསྙེན་པར་མ་རྫོགས་པ་མ་གཏོགས་པ་དགེ་སློང་བསྙེན་པར་རྫོགས་པ་རང་བཞིན་དུ་གནས་པ་ལྟ་བ་དང་མཚན་མཐུན་པ་ལ། བཅོལ་བ་རྣམ་པ་ལྔ་པོ་གཙུག་ལག་ཁང
འདིར་བསྐྱར་དུ་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/163_འདུལ་བ།_ཡུ.txt
> +[49b.4]དགའ་མོ་དགེ་སློང་མ་རྣམས་ལ་སྟོན་པར་བྱེད་ཅིང་དེས་དགེ་སློང་མ་འོངས་ཤིང་ལྷགས་པ་རྣམས་ལ་ཁོ་མོའི་ཕྱིར་ཕྱོགས་ག་གེ་མོ་ཞིག་ཏུ་ཁྲིའུ་ཤོམས་ལ་འདུག་ཏུ་ཆུ་(གཤིག་,ཤིག་)ཅེས་བསྒོ་ཞིང་ཡང་ཕྱོགས་ག་གེ་མོ་ཞིག་དང་གནས་ཁ
འདིར་ཡང་བསྐྱར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/165_འདུལ་བ།_ལུ.txt
> +[326b.5]པའི་སྤྱོད་ཡུལ་སྤངས་ཏེ་ཁ་ཏོན་ནོ། །ཁ་ཏོན་སློབ་པ་མཁན་པོས་མི་#ཐོས་པའི་ལམ་ཙམ་ན་འདུག་སྟེ་བསླབ། མིག་ལམ་དུ་གནས་ཏེའོ། །ཁ་ཏོན་སློབ་པ་མཁན་པོ་རྣ་བ་མི་ན་བ་ཙམ་དུ་མིག་ལམ་དུ་སྣང་བར་བྱས་ཏེ་#འདུག །ཆ་མ་ནོས་ནས་ཕ
འདིར་མ་དཔེར་ཆ་མནོས་ཡིན།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/183_ཚད་མ།_ཕེ.txt
> +[195a.2]བཅོས་བྱེད་པ་ལ་ནི། སཾསྐྲྀཏ་ཙམ་གྱིས་ངེས་པ་ཉིད་ངེས་པར་སྒྲུབ་པ་ཡིན་ནོ། །དེས་ན་གལ་ཏེ་གོམས་པ་ལས་སྡེབ་སྦྱོར་ཉམས་པའི་ཚིག་བཀོད་པས་ཅི་དེ་ཉིད་ལ་མངོན་པར་ཞེན་ནམ། ཡང་ན་རང་གིས་བྱས་པ་ཕྱིར་ཞུ་ཐུག་མ་བྱས་པའི་ཕྱ
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/183_ཚད་མ།_ཕེ.txt
> +[195a.6]འདི་ལ་བཅོམ་ལྡན་འདས་ལ་བསྟོད་པ་མངོན་པར་བརྗོད་པ་གང་ཡིན་པ་ནི། བསྟན་བཅོས་ཀྱི་དོན་ཡིན་པའི་ཕྱིར་ཏེ། རང་གི་ལྷ་ཡིན་པ་ཙམ་གྱིས་ནི་མ་ཡིན་ནོ་ཞེས་བྱ་བའི་དོན་ཏོ། །གལ་ཏེ་འདིར་འདོད་པའི་ལྷ་ཙམ་ལ་བསྟོད་པ་མངོན་པར
འདིའི་བར་གྱི་པ་ཞིག་གསུབ་འདུག

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[34b.6]ཡི་གེའི་མདོ། །སློབ་དཔོན་ཆེན་པོ་ཙནྡྲ་གོ་མིས་མཛད་པ་ཡོངས་སུ་རྫོགས་སོ།། །།ལེགས་པར་སྦྱར་བ་སཾསྐྲྀཏའི་ཚུལ་ཅུང་ཟད་ཁོང་དུ་ཆུད་པའི་ཤཱཀྱའི་དགེ་སློང་ཉི་མ་རྒྱལ་མཚན་དཔལ་བཟང་པོས། དཔལ་འབྱོར་དུ་མ་ལ་དབང་ཐོབ་ཅིང
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[91a.2]དོན་གཞན་གྱི་ཚིག་གི་བསྡུ་བའོ། །ཙུཉྩུ་པ་ནི། དཔེར་ན། སྒྲ་རིག་པ་ནི། ཤ་བྷ་ཙུཉྩུཿ། བ་ཁྱཱ་ཙུཉྩུཿ། ཙོདཱ་ཉྩུཿ། སཾསྐྲྀཏ་ཙུཉྩུཿ། ཨ་ཁ་ར་ཙུཉྩུཿ། ཙ་ན་ས་ནི། དཔེར་ན། སྐྲ་ཚུགས་མཁས་པ་ནི་ཀེ་ཤ་ཙ་ནཿ། ནྲྀ་ཏྱ་ཙ་ནཿ།
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[91a.3]སཾསྐྲྀཏ་ཙ་ནཿ། ཙོ་དྱ་ཙནཿམ་ཁ་ར་ཙ་ན་རྣམས་ཏེ། དེའི་རིགས་ལ། ཙུཉྩུ་པ། ཙ་ཎས་དག་གོ་ཞེས་པས་ཙུཉྩུ་པ་དང་ཅ་ན་ས་དག་འགྱུར་བའོ། །ཨིཥྛན་ནི། དཔེར་ན། ཐམས་ཅད་ལས་ཕུལ་དུ་བྱུང་བར་མཁས་པ་ནི། པ་ཊིཥྛཿ། ཐམས་ཅད་ལས་ཕུལ་དུ
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[93a.2]ཋཀའོ། །དདྷྒཱསཾསྐྲྀཏཾ་དཱ་དྷི་ཀཾ །དདྷི་ལས་ཋ་ཀའོ་ཞེས་པས་ཋཀའོ། །འོད་ཟེར་རྣམས་ཀྱིས་འདུས་བྱས་པ་ནི། མཱ་རཱི་ཙི་ཀཾ ། ཤྲིངྒ་བེ་རས་འདུས་བྱས་པ་ནི། ཤྲིངྒཱ་བ་རི་ཀཾ ། འདུས་བྱས་ལའོ་ཞེས་པས་ཋཀའོ། །ཀིཏ་ལའང་ཞེས་པ
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[225a.1]སཾ་བསྐྲི་ཏ་ལ་བྷཀྵ་ལའོ། །འདུས་བྱས་ཀྱི་དོན་ལ་བདུན་པའི་མཐའ་ལས་ཨཎ་འགྱུར་ཏེ། དེ་གལ་ཏེ་བཅོས་པའི་བཟའ་བ་ཡིན་ནའོ། །བྷཱཥྚེ་སཾ་སྐྲི་ཏཱ་བྷཱཥྚཱ་མོད་ཀཱཿ། བཟའ་བ་ཞེས་པ་ཅི་ཞེ་ན། ཕ་ལ་ཀེ་སཾསྐྲྀཏཱ་མཱ་ལཱ། ཁ་ར་པི་
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[126b.3]ཏཱ་མ་ཀྵ་ཡོ་དྷཱི་བློ་རཱ་སྶ་ཤྲི་ཡེ་ཙཱ་མྲྀ་ཏཱ་ཡ་ཙ། ༡ ༈ །ས་མཱ་ཧྲྀ་ཏྱཱ་ནྱ་ཏ་ནྟྲཱ་ཎི་སཾ་ཀྵིཔྟཻཿ་པྲ་ཏི་སཾསྐྲྀཏཻཿ། །སཾ་པཱུརྞྞ་མུ་ཙྱ་ཏེ་བརྒྒེརྣྣཱ་མ་ལིངྒཱ་
འདིར་གཟིགས་རོགས།

2018-09-26 14:27 UTC, rekongrabten commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[182a.3]བྲྀ་ཏིཿ། །ཡཱུ་པ་གྲནྟརྨྨ་ནརྨྨནྠྱ་ད་རུ་ཎི་ཏྭ་ར་ཎིརྡྭ་ཡོཿ། །དཀྵི་ཎཱགྣིརྒཱརྷ་པ་ཏྱཱ་ཧ་བ་ནཱི་ཡཽ་ཏྲ་ཡོགྣ་ཡཿ། །ཨགྣི་ཏྲ་ཡ་མི་དཾ་ཏྲེ་ཏཱ་པྲ་ཎཱི་ཏཿསཾསྐྲྀཏོཉན་ལཿ། །ས་མཱུ་ཛྱཿཔ་རི་ཙཱ་ཡྻོ་པ་ཙཱ་ཛྱཱ་བགྣཽཔྲ་ཡོ་
འདིར་ནན་གྱིས་གཟིགས་རོགས།

2018-09-26 14:40 UTC, merged

2018-09-26 14:42 UTC, rekongrabten reviewed
ཁྱེད་ལ་དྲི་བ་དང་ཡང་བསྐྱར་བལྟ་དགོས་པ་ཁག་ང་དགུ་བཏང་ཡོད། ད་དུང་སཾ་སྐྲྀ་ཏ ཡོད་ཚད་སཾསྐྲྀཏ  ཞེས་པར་བཟོས་ཡོད་པ་ཁག་གཅིག་ལ་རྟགས་བཀོད་མེད། ཡང་བསྐྱར་སཾསྐྲྀཏ བྲིས་ནས་འཚོལ་ཞིབ་ཀྱིས་ཡང་བསཀྻར་གཟིགས་རོགས་མཁྱེན།