update
Esukhia/derge-tengyur-old pull request #44
Opened 2018-10-06 03:42 UTC by Sangkhar

2018-10-15 14:54 UTC, rekongrabten requested changes

2018-10-15 14:54 UTC, rekongrabten commented on derge-tengyur-tags/121_མདོ་སྡེ།_ནི.txt
> +[64b.5]ཀྱི་རྣམ་པའི་རྣམ་པར་ཤེས་པ་ཐམས་ཅད་དོན་དམ་པའི་བདེན་པ་མི་གཉིས་པའི་ཤེས་པ་ལས་ལྡོག་པ་སྟེ།་་ དེས་ན་ཡི་གེའི་ཚིག་ནི་ཡི་གེ་མེད་པའི་ཚིག་ཅེས་འཕགས་པ་བློ་གྲོས་ཆེན་པོས་དྲི་བ་བརྒྱ་རྩ་བརྒྱད་གསོལ་བའི་ལན་ཐམས་ཅད་མ
འདི་ལ་ཚེག་གཉིས་ཤོར་འདུག

2018-10-15 14:54 UTC, rekongrabten commented on derge-tengyur-tags/074_རྒྱུད་འགྲེལ།_པུ.txt
> +[54a.6]བྱས་ཏེ། མར་རྙིང་པ་ལོ་གསུམ་ལོན་པ་ཕུལ་བཞི་དང་། བ་དམར་མོའི་འོ་མ་ཕུལ་བཞི་དང་། སྦྲང་རྩི་ཕུལ་བཞི་རྣམསཏེ། མེ་ཆུང་བས་བཙོས་ལ་ནད་པ་ཁྲུས་ལ་སོགས་པ་བྱས་ལ། སྔ་མའི་སྔགས་དང་འདྲ་བར་བྱས་པས་སྨྱོ་བྱེད་ཀྱི་གདོན་ལས
འདི་ལ་གཟིགས་རོགས།

2018-10-15 14:54 UTC, rekongrabten commented on derge-tengyur-tags/074_རྒྱུད་འགྲེལ།_པུ.txt
> +[177a.6]པའི་གཟུངས་ཀྱི་ཆོ་ག་རྫོགས་སོ།། {T3082}༄་། །གཙུག་ཏོར་དྲི་མེད་ཀྱི་གཟུངས་ཆོག་བཞུགས།།# ༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །གཙུག་ཏོར་དྲི་མ་མེད་པའི་གཟུངས་ཀྱི་ཆོ་ག །དང་པོར་བའི་ལྕིབ་ས་ལ་མ་ལྷུང་བས་དཀྱི
འདིར་གཟིགས་རོགས།

2018-10-15 14:54 UTC, rekongrabten commented on derge-tengyur-tags/076_རྒྱུད་འགྲེལ།_བུ.txt
> +[117b.4]བཛྲི་ཛཿ་ཧཱུཾ་གཟུགས་རྡོ་རྗེ་མའོ། །ཨོཾ་ཨཱ་ཤ་བྟ་བཛྲེ་ཧཱུཾ་ཧཱུཾ་སྒྲ་རྡོ་རྗེ་མའིའོ། །ཨོཾ་ཨཱཿ་ག་ནྡྷ་བ་ཛྲེ་བཾ་ཧཱུཾ་དྲི་རྡོ་རྗེ་མའི་འོ། །ཨོཾ་ཨཱཿ་ར་ས་བཛྲེ་ཧོཿ་ཧཱུཾ་རོ་རྡོ་རྗེ་མའི་འོ། །ཨོཾ་ཨཱཿ་སྤཪྴེ་བཛ
འདིར་གཟིགས་རོགས།

2018-10-15 14:54 UTC, rekongrabten commented on derge-tengyur-tags/121_མདོ་སྡེ།_ནི.txt
> +[64b.5]ཀྱི་རྣམ་པའི་རྣམ་པར་ཤེས་པ་ཐམས་ཅད་དོན་དམ་པའི་བདེན་པ་མི་གཉིས་པའི་ཤེས་པ་ལས་ལྡོག་པ་སྟེ།་་ དེས་ན་ཡི་གེའི་ཚིག་ནི་ཡི་གེ་མེད་པའི་ཚིག་ཅེས་འཕགས་པ་བློ་གྲོས་ཆེན་པོས་དྲི་བ་བརྒྱ་རྩ་བརྒྱད་གསོལ་བའི་ལན་ཐམས་ཅད་མ
འདི་ལ་ཚེག་གཉིས་ཤོར་འདུག

2018-10-15 14:54 UTC, rekongrabten commented on derge-tengyur-tags/164_འདུལ་བ།_རུ.txt
> +[234b.6]སུ་ལ་བཤགས་ཤེ་ན། གཅིག་ལའོ་ཞེས་པ་དང་།གཞན་དུ་མི་ལྟ་བ་དེ་ལའོ་ཞེས་པ་དང་། ཉེས་པ་མི་འདྲ་ལ་ཞེས་པ་དང་། སྡེ་ཡང་ཞེས་པ་ཡིན་ཏེ། གང་ཟག་གཅིག་ལ་བཤགས་པ་དང་། དེའང་གཞན་དུ་མི་ལྟ་བ་དང་། ཉེས་པ་མི་འདྲ་བ་དང་། ལྟུང་བ
ཤེད་ཀྱི་སྟོང་པ་གསུབ་མི་ཉན།

2018-10-15 14:54 UTC, rekongrabten commented on derge-tengyur-tags/171_འཁྲི་ཤིང།_ཁེ.txt
>  ར། །བཱ་ད་སཾ་བཱ་ཧ་ནཱ་སཀྟཱ་སནྡྷྱཱ་ཏ་སྱཱནྟི་ཀེ་བ་བྷཽ། །ཏ་ཏཤྩ་པཤྩི་མཱཾ་བྷོ་དྷིཾ་པྲ་བིཥྚེ་བཱ་ས་རེ་ཤྭ་རེ། །ཁ་མ་པཱུཪྻ་ཏ་ན་ཀྵ་ཏྲཻསྟ་དུཏྠཻ་རི་བ་ཤཱི་ཀ་རེཿ། །ཤ་ནཻསྟོ་ཀ་ཏ་མཿཥྱཱ་མཱ་ནི་ཤ་བྷུ་
འཁྲི་ཤིང་ཀེའི་ནང་དུ་HEAD ཡོད་ས་རེད།

2018-10-18 01:59 UTC, rekongrabten requested changes

2018-10-18 01:59 UTC, rekongrabten commented on derge-tengyur-tags/049_རྒྱུད་འགྲེལ།_ཚི.txt
> +[133b.2]སེམས་དཔའི་ཡིད་འཇུག་པའི་བསམ་གཏན་གྱི་འཁོར་ལོ་ཞེས་བྱ་བ། རྒྱ་གར་གྱི་མཁན་པོ་དཔལ་ལྡན་གཉིས་སུ་མེད་པས་མཛད་པ་རྫོགས་སོ།། །།རྣལ་འབྱོར་པ་བསོད་སྙོམས་པ་པྲཛྙཱ་ཤྲཱི་ཛྙཱ་ན་ཀཱི་རྟིས་རང་འགྱུར་དུ་མཛད་པའོ།། {T210
འདིར་གཟིགས་རོགས།

2018-10-18 01:59 UTC, rekongrabten commented on derge-tengyur-tags/052_རྒྱུད་འགྲེལ།_ཞི.txt
> +[263b.3]སངས་རྒྱས་དང་། །རྫས་གཅིག་རྙེད་པས་དོན་ཡོད་འགྲུབ། །སྔགས་#གཅིག་བཟླས་པས་ནུས་པ་འབྱུང་། །མཉམ་ཉིད་གཞིའི་སྒྲོན་མ་རྫོགས་སོ།།{T2320}#༄༅༅། །རྒྱ་གར་སྐད་དུ། ཀོ་ཊི་ནིཥྛ་ཕ་ལ་པྲ་#དཱི་པ་ནཱ་མ། བོད་སྐད་དུ། མཐར་ཐ
འདི་ལ་གཟིགས་རོགས།

2018-10-18 14:12 UTC, rekongrabten requested changes

2018-10-18 14:12 UTC, rekongrabten commented on derge-tengyur-tags/123_སེམས་ཙམ།_ཕི.txt
> +[188b.3]རྟོག་ལ་རྣམ་ཀུན་ཏུ། །གཉིས་པོ་རྟག་ཏུ་མེད་ཀྱང་སྣང་བར་འགྱུར། །ཇི་ལྟར་ཆུ་རྙོག་#པ་ལས་དངས་པ་ན#། །དངས་པ་ཉིད་དེ་དེ་ལས་སྐྱེ་མིན་གྱི#། །དེ་ནི་དེ་ལ་དྲི་མ་བྲལ་བར་ཟད། །དེ་བཞིན་རང་སེམས་དག་ལ་ཚུལ་དེ་ཉིད། །སེམ
འདི་ལ་དོགས་རྟགས་འབྲི་རོགས།

2018-10-18 14:12 UTC, rekongrabten commented on derge-tengyur-tags/123_སེམས་ཙམ།_ཕི.txt
> +[188b.6]འགོག་པར་བྱེད་དོ། །དེ་བཞིན་དུ་རི་མོའི་མཐོན་དམན་དང་འདྲ་བ་དང་། ཆུ་རྙོག་#པ་ལས་དངས་པ་དང་འདྲ་བར་ཡང་#གོ་རིམས་བཞིན་ནོ། །ཚིགས་སུ་བཅད་པ་གསུམ་#པས་ནི། སེམས་ཆུ་དང་འདྲ་བར་བསྒྲུབ་#སྟེ། ཇི་ལྟར་ཆུ་རང་བཞིན་གྱི
དོགས་རྟགས་འབྲི་རོགས།

2018-10-18 14:12 UTC, rekongrabten commented on derge-tengyur-tags/201_གསོ་རིག_ཁོ.txt
> +[184b.2]ཟས་དང་སྤྱོད་ལམ་སྣུམ་པ་དང་རྩུབ་པས་ཞི་ཞིང་བདེ་བར་མི་འགྱུར་བ་ཡིན་ནོ། །གཞན་ཡང་གཡའ་བ་ལ་སོགས་པ་དང་ལྡན་ནོ། །མཁྲིས་གྱུར་ཚ་ཞིང་རྨོངས་བག་དང་། །རྔུལ་ཞིང་བརྒྱལ་རྨྱོས་སྐོམ་དད་ཆེ། །རེག་མི་བཟོད་ཅིང་ན་ལ་དམར།
འདིར་མ་དཔེ་མྱོས་ཞེས་གསལ།

2018-10-19 06:49 UTC, Sangkhar commented
འདི་དག་བཟོས་ཚར་ཡོད།

2018-10-19 14:06 UTC, rekongrabten approved these changes

2018-10-19 14:06 UTC, rekongrabten commented on derge-tengyur-tags/074_རྒྱུད་འགྲེལ།_པུ.txt
> +[8a.1]ལས་མཛད་པའི་རྡོ་རྗེ་རྣམ་པར་འཇོམས་པའི་ཁྲུས་ཀྱི་ཆོ་ག་གཞན་ལ་ཕན་པར་བྱེད་པ་ཞེས་བྱ་བ་རྫོགས་སོ།། །།རྒྱ་གར་གྱི་མཁན་པོ་བཛྲ་བོ་དྷི་དང་། ལོ་ཙཱ་བ་ཚུལ་དགེ་རིན་ཆེན་གྱིས་བསྒྱུར་བའོ།། M{T2938}༄༅༅། །རྒྱ་གར་སྐད་ད
འདི་ལ་M ཞིག་ཤོར་འདུག

2018-10-19 14:06 UTC, merged