update
Esukhia/derge-tengyur-old pull request #47
Opened 2018-10-12 03:58 UTC by tashikuncok

2018-10-12 06:04 UTC, tashikuncok commented
ཚོད་ལྟ།

2018-10-15 14:34 UTC, rekongrabten requested changes

2018-10-15 14:34 UTC, rekongrabten commented on derge-tengyur-tags/146_མངོན་པ།_ཇུ.txt
> +[163b.2](ལྟན་ལྡན་)པ་དག་འདི་ནི་ཆོས། འདི་ནི་འདུལ་བ་འདི་ནི་སྟོན་པའི་བསྟན་པའོ་ཞེས་བདག་གིས་བཅོམ་ལྡན་འདས་ལས་མངོན་སུམ་དུ་གཟུང་བའི་ཕྱིར་རོ་ཞེས་སྨྲ་ན། དགེ་སློང་དེས་བཤད་པ་ལ་སྤྲོ་བར་ཡང་མི་བྱ་སྐྱོན་གདགས་པར་ཡང་མི
རྟགས་བཀོད་སྟངས་ནོར་འདུག

2018-10-15 14:34 UTC, rekongrabten commented on derge-tengyur-tags/146_མངོན་པ།_ཇུ.txt
> +[163b.4]པ་ཆོས་འདི་ནི་བཅོམ་ལྡན་འདས་ཀྱིས་བཤད་ཅིང་། ཚེ་དང་ལྡན་པས་ལེགས་པར་བཟུང་བ་སྟེ། འདི་ལྟར་མདོ་(སྟེ,་སྡེ་)དང་བསྟུན་ཅིང་འདུལ་བ་ལ་བལྟས་པ་ན་མདོ་སྡེ་ལ་འཇུག་འདུལ་བ་ལ་སྣང་། ཆོས་ཉིད་དང་མི་འགལ་ཏེ། འདི་ནི་ཆོས།
ཚེག་རྟགས་ཀྱི་ནང་ལ་འཇོག་རོགས།

2018-10-15 14:34 UTC, rekongrabten commented on derge-tengyur-tags/051_རྒྱུད་འགྲེལ།_ཝི.txt
> +[211a.7]ལ་རྣམ་པར་རྟོག་པའི་སྐྱོན་གྱིས་དེ་ཁོ་ན་ཉིད་ལ་མི་འཇུག་ཅིང་ཞུགས་པ་དག་ཀྱང་ཕྱིར་ཟློག་པར་བྱེད་ལ་ཐེ་ཚོམ་སྐྱེད་པ་སྟེ། དེ་ལ་སོགས་པ་དྲི་མས་གོས་པར་བྱེད་ཅིང་འདི་ནི་(ཆོསངས་,སངས་)རྒྱས་ཀྱི་ཆོས་མ་ཡིན་ནོ། །འདི
ཆོ་ཞེས་པ་དེ་གསུབ་ནས་དོགས་རྟགས་དེ་མི་དགོས།

2018-10-15 14:34 UTC, rekongrabten commented on derge-tengyur-tags/191_ཚད་མ།_ཟེ.txt
> +[202b.5]ནོ་སྙམ་ན། གལ་ཏེ་དེ(་ལྟན,་དེ་ལྟ་ན་)བདག་གི་སྒྲ་འཇུག་པ་ཡང་ཁོ་བོ་ཅག་གི་#ང་རྒྱལ་གྱི་རྟེན་སེམས་ཡིན་པར་འདོད་པ་ཉིད་ཡིན་པས་སྤྱིར་བདག་གྲུབ་པོ། །གང་ཡང་ཅི་#སྟེ་བདག་གི་སྒྲ་ནི་མི་རྟག་པའི་ཡུལ་ཅན་ཡིན་ཏེ་ཞེས་
འདིའི་དོགས་རྟགས་རྒྱག་སྟངས་ནོར་འདུག

2018-10-19 09:44 UTC, Sangkhar commented
གོང་གི་འདི་དག་ཀྱང་བཟོས་ཚར་ཡོད།

2018-10-22 03:43 UTC, tashikuncok commented
update

2018-10-25 13:46 UTC, merged