ཚོད་་་་
Esukhia/derge-tengyur-old pull request #52
Opened 2018-10-20 05:45 UTC by drakpagyamtso

2018-10-20 11:11 UTC, drakpagyamtso commented
2018-10-20

2018-10-21 13:10 UTC, rekongrabten requested changes
འདི་དག་ལ་ཞིབ་ནན་གྱིས་ཡང་བསྐྱར་གཟིགས་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/028_རྒྱུད་འགྲེལ།_ཤ.txt
> +[148b.2]ཀླུ་རྣམས་ཀྱི་གཏོར་མ་གསུམ་གྱི་སྣོད་གསུམ་སྦྱིན་པར་དེ་ལ་རིམ་པ་ནི། ལོ་ཏོག་ནས། གྲོ། སོ་བ། འབྲས། མ་ཤ། །མོན་སྲན་སྡེའུ། སྲན་ཆེན་ཨོ་སྐྱ་ཀ། སྲན་ཆུང་མ་སྡུ་ར་བདུན་དང་། ཆང་དང་ཤ་དང་ཉ་ལ་སོགས་པ་བླངས་ནས་སྣོད་
འདིར་མ་དཔེར་ཤད་གཅིག་ལས་མི་འདུག

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/028_རྒྱུད་འགྲེལ།_ཤ.txt
> +[169a.3]བསྒྲུབ་པར་བྱ་སྟེ་དེ་ཡང་དུར་ཁྲོད་ཀྱི་ས་ལས་དཀྱིལ་འཁོར་ཟུར་གསུམ་པར་བྱས་ཏེ། རའི་ཁྲག་གིས་མེའི་དཀྱིལ་འཁོར་གྱི་དབྱིབས་སུ་བྱ་སྟེ། དེར་མེའི་ས་བོན་གྱིས་མཚན་པའི་སྒྱེད་(བུ་,པུ་)བཙུགས་ཏེ། དེའི་སྟེང་དུ་ཐོད
འདིར་མ་དཔེ་པུ་གསལ་པོ་འདུག་པས་དོགས་རྟགས་མི་དགོས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/028_རྒྱུད་འགྲེལ།_ཤ.txt
> +[245b.4]མས་གཏུམས་ལ་བསྲེག་གོ། །དེའི་སྟེང་དུ་ནིམ་པའི་ཤིང(་བཙིགས་,བཙུགས་)ལ་སྨན་རྣམས་ས་འོག་ཏུ་སྦས་ཏེ། ཤིང་པ་ལ་ཤའི་མེ་ཏོག་བཏགས་པའི་ཁུ་བ་སྲང་བཞི། མར་དང་སྦྲང་རྩི་སྦགས་ཏེ། སྣོད་སྣུམ་ཅན་གྱི་ནང་དུ་འབྲས་ཀྱི་ཕུང
འདིར་དོགས་རྟགས་ཀྱི་ནང་དུ་ཤིང་གི་ཚེག་ཤོར་འདུག་པས་དེ་བཟོ་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/033_རྒྱུད་འགྲེལ།_ཁི.txt
> +[138b.7]གོ། །དེ་ནས་ཞེས་བྱ་བ་ནས་འདའ་བར་མི་བྱའོ་ཞེས་པའི་བར་དུ་ནི་སེམས་ཅན་ཐམས་ཅད་དང་བདག་ཉིད་ཀྱང་རང་གི་ཡི་དམ་གྱི་ལྷའི་རྣམ་པར་བསྒོམས་ལ་མཆོད་པར་བྱའོ་ཞེས་བསྟན་ཏོ།#།དེ་ལྟར་ཉིན་རེའི་དམ་ཚིག་ནི་རྣལ་འབྱོར་པ་ཐམས་
འདིའི་སྟོང་པ་དགོས་པས་མ་གསུབ་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/042_རྒྱུད་འགྲེལ།_དི.txt
> +[14a.7]དམ་སོམ(སྡོམ)་བཅས་པ་རུ། །བུམ་པ་ལ་སོགས་རབ་ཐོབ་སྟེ། །བླ་མའི་ཞལ་ལས་རྙེད་པ་ཡི། །དེ་བཞིན་ཉིད་ནི་རབ་ཐོབ་ཅིང་། །གསང་དང་མཆོག་ཏུ་གསང་རིགས་པས། །ཇི་སྐད་བཤད་པའི་བྱ་བ་ཡིས། །ཡང་དག་བསྒོམ་ནི་མི་ནུས་པས། །ཇི་བཞི
འདིའི་རྟགས་འདི་གང་ཡིན་ནམ། མ་དཔེར་དམ་སྡོམ་བཅས་པ་རུ། །ཞེས་གསལ་བས་ཁ་ཐུག་བཟོ་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/052_རྒྱུད་འགྲེལ།_ཞི.txt
> +[89b.4]པའི་སེམས་ཉིད་མ་མཐོང་ལ། །སེམས་ཉིད་ལ་གནས་པའི་སངས་རྒྱས་ཀྱི་སྐུ་གསུང་ཐུགས་ཀྱི་ཡོན་ཏན་དཔག་ཏུ་མེད་པ་མ་རྟོགས་པ་ནི། དཔེར་ན་དབུལ་མོའི་ལྟོ་ན་འཁོར་ལོས་སྒྱུར་བའི་རྒྱལ་པོའི་མ་ནོར་བུ་རིན་པོ་ཆེའི་སྒྱེད(་པོའམ
འདིའི་དོགས་རྟགས་ཀྱི་ནང་ལ་ཚེག་ཤོར་འདུག་པ་དང་དོགས་རྟགས་བཀོད་སྟངས་ཀྱང་ཅུང་ནོར་འདུག   (པོའམ,པུའམ)།  འདི་ལྟར་བཀོད་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/065_རྒྱུད་འགྲེལ།_ངུ.txt
> +[31a.6]དག་པར་བརྗོད་པའི་མཉམ་པར་གཞག་པའི་རིམ་པའི་མན་ངག་རྫོགས་སོ། །རྒྱ་གར་གྱི་མཁན་པོ་སུ་བཛྲ་དང་། བོད་ཀྱི་ལོ་ཙཱ་བ་ཆོས་ཀྱི་ཤེས་རབ་ཀྱིས་བསྒྱུར་བའོ།། ༄། །འཇམ་དཔལ་དཔའ་བོ་གཅིག་པའི་སྒྲུབ་ཐབས་བཞུགས།། {T2571}༄༅།
ཆོས་ཚན་གྱི་ཨང་གྲངས་དེ་ཆོས་ཚན་གྱི་ཁ་བྱང་གི་མདུན་ལ་འཇོག་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/073_རྒྱུད་འགྲེལ།_ནུ.txt
>  131.	བཞག་ནས་ཚོན་སྣ་ལྔའི་སྐུད་པས་རྒྱ་གྲམ་དུ་བཅིངས་ཏེ། ཡང་བརྒྱ་རྩ་བརྒྱད་བཟླས་ན་དངོས་གྲུབ་གསུམ་འགྲུབ་པར་འགྱུར་ཏེ། དེ་ཡང་མི་སྣང་བ་ནི་མཆོག་གོ །སའི་འོག་ན་གནས་པའི་གཏེར་མཐོང་བ་ནི་འབྲིང་ངོ༌། །རྒྱལ་པོའི་བུ་མོ་
འདིར་ནོར་འདུག

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/155_འདུལ་བ།_མུ.txt
> +[195b.3]པ་ཞེས་བྱ་བ་ནི་སྦྱིན་པར་བྱེད་པའི་མིང་སྟེ། དེས་ནི་ལོངས་སྤྱོད་ཀྱི་འབྲས་བུ་ཅན་གྱི་བསོད་ནམས་ཀྱི་ལས་རབ་ཏུ་(འཕལ་,འཕེལ་)་བར་འགྱུར་རོ། །ཚུལ་ཁྲིམས་ལེགས་པར་བསྡམས་པས་ནི་དགྲ་སོགས་མི་འགྱུར་ཏེ་ཚུལ་ཁྲིམས་དགྲ
འདིར་དོགས་རྟགས་ཀྱི་གུག་རྟགས་ཀྱི་ཕྱི་ལ་ཚེག་ཅིག་འདུག་པས་དེ་གསུབ་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[117a.6]བཧྣིཿ། པཱཪྵྞི་ལ་སོགས་པ་རྣམས་སོ། །པྲྀ་ཥུ་བྲྀ་ཥུ་བཀྲུ་བ་ལའོ། །སྲྀ་འགྲོ་བ་ལའོ། །བྷཱུ་ཡོད་པ་ལའོ། །བྷྲྀ་ཉ་འགེངས་པ་ལའོ། །ཙུ་ར་རྐུ་བ་ལའོ། །ཏུ་ར་མྱུར་བར་བྱེད་པ་ལའོ། །ཛྲྀཥ་རྒས་པ་ལའོ། །འདི་རྣམས་ལས་ནི་ཕ
འདིར་མ་དཔེ་རྐེད་པ་ཞེས་གསལ་བས་དེ་ལྟར་བཟོ་བ་དང་སྔ་ཕྱིའི་ཚིག་དང་བརྗོད་པ་དག་ལ་ཞིབ་ནན་གྱིས་གཟིགས་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/202_གསོ་རིག_གོ.txt
> +[76b.6]དང་སྐྱེར་ཁ་ཎྜ། །བཏགས་པ་དང་ནི་བསྲེས་པ་ཡི། །འཇམ་རྩི་དྲོ་འཇམ་བཏང་ན་ནི། །ཤ་དང་མེ་དྲོད་ལུས་ཀྱི་སྟོགས། །ཁུ་བ་འཕེལ་བར་བྱེད་པ་ཡིན། །དྲེག་ནད་རྨོངས་བག་གཅིན་སྙི་དང་། །གཞང་འབྲུམ་སྐྲན་དང་བཤང་གཅི་འགགས། །མི་
སྟོགས་ཞེས་པ་དེ་སྟོབས་བཟོ་རང་འཇགས་འཇོག་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/212_སྣ་ཚོགས།_པོ.txt
> +[146a.2]དང་གནས་བྱེད་པ། །ཐབ་ཁ་བ་ཞེས་བྱ་བའོ། །ཕྱག་ཚང་བ་དང་ཟས་གཉེར་བ། །ཟས་བྱེད་པ་ཞེས་བྱ་བ་རྣམས། །ཚང་མང་དང་ནི་རོ་ལྡན་དང་། །མཆོད་པའི་གནས་དང་གཡོས་ཁང་ངོ་། །ཐབ་དང་སྒྱེད་(བུ་,པུ་)མེ་ཐབ་དང་། །ཙུ་ལི་དང་ནི་གཡོས་
འདིར་མ་དཔེ་སྐྱེད་བུ་ཞེས་གསལ་བས་གཉིས་ཀ་དོགས་རྟགས་ནང་དུ་བཀོད་རོགས། (སྐྱེད་བུ་,སྒྱེད་པུ་)འདི་བཀོད་རོགས།

2018-10-21 13:10 UTC, rekongrabten commented on derge-tengyur-tags/212_སྣ་ཚོགས།_པོ.txt
> +[186b.1]གྷརཾ་ཏཾ་གསལ་དང་། སྣང་བ་ཆུ། །ཙི་ཏི་ཚོགས་དང་། བསགས་པ་ལ། །ཙི་ཏི་འདུས་དང་། །ཚོགས་པ་དང་། སྐབས་དང་སྒྱེད་(བུ་,པུ་)ལ་ཡང་ངོ་། །ཛ་ཙཾ། སྐྱེ་པ་ཚོགས་དང་སྐྱེ། །ཛ་ཏི་སྤྱི་དང་ཕྲེང་བ་ཅན། །སྡེབ་སྦྱོར་དབྱེ་བ་རི
འདིར་མ་དཔེ་སྒྱེད་པུ་ཞེས་གསལ་བས་དོགས་རྟགས་མི་དགོས།

2018-10-22 12:39 UTC, rekongrabten approved these changes

2018-10-22 12:40 UTC, merged