ནང་འདྲེན
Esukhia/derge-tengyur-old pull request #53
Opened 2018-10-20 11:19 UTC by tibetanboy

2018-10-20 11:19 UTC, tibetanboy commented
ཞུ་དག

2018-10-20 11:24 UTC, tibetanboy commented
༢༠༡༨།༡༠།༢༠

2018-10-20 15:50 UTC, rekongrabten requested changes
འདི་དག་ཞིབ་ཅིང་ཕྲ་བར་གཟིགས་རོགས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/011_རྒྱུད་འགྲེལ།_ཐ.txt
> +[52b.3]མཚན་མར་འགྱུར་ཏེ་ཡོན་ཏན་དབང་གིས་ཨུཏྤལ་འམ་ཐོང་གཤོལ་ལོ། །རྒྱལ་རིགས་མ་ཡི་རིན་ཆེན་དར་དཔྱངས་སུ་འགྱུར་མི་ཡི་བདག་པོ་སྨྱུ་གུ་རིན་ཆེན་ཕྲེང་བ་ནི། །རྗེ་རིགས་མ་ཡི་དེ་བཞིན་དུ་སྟེ་དེ་བཞིན་ཆུ་ན་རྒྱུ་བ་དང་བཅས་
འདིའི་མ་དཔེར་སེར་པོའི་ནང་དུ་   ཨུཏྤ་ལ་འམ་  ཞེས་གསལ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/014_རྒྱུད་འགྲེལ།_པ.txt
> +[283a.4]པ། །རྒྱ་གར་ཁ་ཆེའི་པཎྜི་ཏ་ཆེན་པོ། །ཤཱཀྱ་ཤྲའི་བྷ་དྲས་མཛད་པ་རྫོགས་སོ།།{T1386}༄༅༅། །རྒྱ་གར་སྐད་དུ། །པཉྩ་གྲ་ཧ་པྲ་ཏི་ག་ཎོ་པ་དེ་ཤ་ནཱ་མ། བོད་སྐད་དུ། །གཟའ་ལྔ་སོ་སོའི་རྩིས་ཀྱི་མན་ངག་ཅེས་བྱ་བ། དཔལ་དུས་ཀ
འདིར་སྟོང་པ་དགོས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/016_རྒྱུད་འགྲེལ།_བ.txt
> +[175b.5]ནའོ། །དེའི་འོག་དང་ཡང་དག་ལྡན་པ་ནི་ཡི་གེ་བཅོ་ལྔ་པ་གའོ། །དབྱངས་ཡིག་རྣམས་ཀྱི་གསུམ་པ་ནི། །དབྱངས་ཨིའོ། །དེ་ཡིས་མཚོན་པར་མཁས་པས་སོ། །དེས་ནྒིའི་གཟུགས་སུ་འགྱུར་རོ། །ཉིད་ནི་རིང་པོ་དགག་པའི་དོན་ཏོ། །དབྱངས
འདི་མ་དཔེར་   གྣིའི་   ཞེས་གསལ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/022_རྒྱུད་འགྲེལ།_ཞ.txt
> +[78a.1]འཁྱུད་པའོ། །གཉིས་པའི་ཕྱག་གཉིས་ན་ཁྲག་འཛག་པའི་གླང་པོ་ཆེའི་པགས་པ་རྒྱབ་ཏུ་བསྣམས་པའོ། །གཡས་པའི་ཕྱག་བཞི་ན་རྩེ་གསུམ་དང་གྲི་གུག་དང་དགྲ་སྟ་དང་རྡེའུ་ཆུང་བསྣམས་པའོ། །གཡོན་པའི་ཕྱག་བཞི་ན་རྡོ་རྗེས་མཚན་པའི་ཁ
འདི་ཕལ་ཆེར་རྔེའུ་ཆུང་ཡིན་པ་འདྲ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/022_རྒྱུད་འགྲེལ།_ཞ.txt
> +[311a.7]གླང་པོ་ཆེས་ནི་དེའི་འམ་རྔ་མོའིའོ། །མ་ཧེའམ་ཤ་བས་ནི་ཅེ་སྤྱང་གིའོ། །དོམ་གྱིས་ནི་དེའི་རུས་པའོ། །ཕག་གིས་ནི་སྟག་གིའོ། །སྟག་གིས་ནི་གླང་པོ་ཆེའིའོ། །བྱི་བས་ནི་དེའིའོ། །སྦྲུལ་གྱིས་ནི་དེའིའོ། །རུས་སྦལ་གྱ
འདིར་མ་དཔེར་ཚེག་མི་འདུག

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/041_རྒྱུད་འགྲེལ།_ཐི.txt
> +[2a.3]ཅེས་བྱའོ། །ཅིའི་ཕྱིར་སྙོམས་པར་འཇུག་པར་མཛད་ཅེ་ན། དེའི་འམ་དེ་ལ་སྡུག་པའི་རྣལ་འབྱོར་གྱིས་དེ་དག་གི་སྔགས་ཀྱི་སྦྱོར་བ་ཤིན་ཏུ་ལེགས་པ་ཡིན་ནོ་ཞེས་ཤེས་པར་བྱ་བའི་ཕྱིར་རོ། །འདི་ཉིད་ཀྱི་ཞེས་བྱ་བ་ནི་སྔགས་ཀྱི་
འདིར་ཚེག་མི་འདུག

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/052_རྒྱུད་འགྲེལ།_ཞི.txt
> +[268a.1]གང་འཐུང་བར་བྱེད་པ། དེ་ཤེས་རབ་ཆེན་པོ་དང་ལྡན་པར་འགྱུར་རོ། །ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྒྲུབ་ཐབས། །རྗེ་བཙུན་ཀ་མ་ལ་ཤཱི་ལས་#མཛད་པ་རྫོགས་སོ།།༄༅། །རྗེ་བཙུན་མ་འཕགས་མ་སྒྲོལ་མའི་སྒྲུབ་ཐབས།#{T2327}༄༅༅
མ་དཔེར་འདིའི་ཁ་བྱང་མི་འདུག་པས་གསུབ་རོགས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/058_རྒྱུད་འགྲེལ།_ཤི.txt
> +[77b.5]དབང་ཕྱུག་གམ། དེའི་རིགས་ཀྱི་ལྷ་རྣམས་ཀྱི་ལས་ཀྱི་ཕྱག་རྒྱ་བཅིངས་ལ། དེའི་ང་རྒྱལ་གྱིས་གནས་ཏེ། སངས་རྒྱས་དང་བྱང་ཆུབ་སེམས་དཔའ་ཐམས་ཅད་ཅེས་བྱ་བ་ལ་སོགས་པ་སྔ་མ་བཞིན་དུ་བརྗོད་ཅིང་། །ཨོཾསརྦྦ་ཀརྨྨཱ་ཨཱབར་ཎ་བི་
འདིར་མ་དཔེར་ཨོཾ་སརྦྦ་ཞེས་གསལ་བས་ཚེག་རྒྱག་རོགས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/095_ཤེར་ཕྱིན།_མ.txt
> +[250a.1]བར་བྱའོ། །འདིས་ནི་རྣམ་པར་གཡེང་གཡིང་བ་ཚར་གཅད་#པ་བསྟན་ཏོ། །མངོན་པར་རྟོགས་པ་བཤད་ཟིན་ཏོ།། །།#འདི་མན་ཆད་ནི་སངས་རྒྱས་ཀྱི་ཡོངས་སུ་བཙལ་བ་ཡིན་ཏེ། སངས་རྒྱས་ཀྱི་དེ་ཡང་ཕུན་སུམ་ཚོགས་པ་བདུན་གྱིས་ཡོངས་སུ་བས
འདིར་མ་གཡིང་ཞེས་གསལ་བས་(གཡིང་,གཡེང་) ཞེས་འབྲི་དགོས། ཁྱེད་ཀྱི་གཡེང་གཡིང་བྲིས་པ་ནོར་འདུག

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/096_དབུ་མ།_ཙ.txt
> +[27a.1]༄༅། །བྱས་པ་ཞེས་བྱ་བ། སློབ་དཔོན་འཕགས་པ་ཀླུ་སྒྲུབ་ཀྱིས་མཛད་པ་རྫོགས་སོ།། །།ལོ་ཙྪ་#བ་གཞོན་ནུ་མཆོག་དང་། སྙན་དར་མ་#གྲགས་དང་ཁུའི་འགྱུར་དག་ལས་དོན་དང་ཚིག་བཟང་དུ་བྲིས་པའོ།། {T3828}༄༅། །རྩོད་པ་བཟློག་པའི་
བྱས་པ་ཞེས་བྱ་བ། ཞེས་པའི་མདུན་གྱི་དབུ་ཁྱུད་མི་དགོས། ད་དུང་རྩོད་པ་བཟློག་པའི་ཚིག་ལེའུར་བྱས་བ་ཞེས་བྱ་བ། ཞེས་པའི་མཚན་བྱང་མེད་པས་གསུབ་རོགས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/105_དབུ་མ།_ལ.txt
> +[313b.2]ཐད་དེ། འདི་དང་འདི་ལྟར་བྱའོ་ཞེས་བྱ་བ་མ་ཡིན་པ་བསྡོགས་པར་ཡང་ཤེས་པར་བྱའོ། །འོན་ཏེ་དེ་ལྟར་བརྟགས་ནས་ཇི་ལྟར་བསྲུང་བར་བྱ་སྙམ་པ་ལ། འཇིགས་པ་ལ་སོགས་པ་ཞེས་བྱ་བ་ལ་སོགས་པ་སྨོས་སོ། །དཔེར་ན་སྐབས་འགའ་ཞིག་ཏུ་ག
འདི་མ་དཔེར་  གཤད་ཅེས་གསལ་བས་(གཤད་,གཤེད་) འདི་ལྟར་འབྲི་རོགས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/115_མདོ་སྡེ།_ཆི.txt
> +[128b.1]གསུངས་ཏེ། དེ་བས་འདི་བསྟན་པ་དགོངས་པ་ཅན་ཡིན་པར་བརྟག་པར་ནུས་པ་མ་ཡིན་ཞེས་སྟོན་ཏོ། །ཞལ་ནས་གསུངས་པའི་མདོ་སྡེ་ཡང་ཕལ་ཆེར་ནུབ་ལ་ཞེས་བྱ་བ་འདིས་ནི་གང་དུ་ཡང་མ་གསུངས་སོ་ཞེས་བྱ་བར་མི་རུང་བའི་གཏན་ཚིགས་སྟོན་
འདིར་མ་དཔེར་སེར་པོ་མེད་ཀྱང་དཀར་པོའི་ནང་དུ་རིུང་འདི་ལྟར་གསལ་བས་དོགས་རྟགས་བཀོད་ན་བཟང།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/116_མདོ་སྡེ།_ཇི.txt
> +[47b.3]ཅད་ཅེས་བྱ་བའི་ཐ་ཚིག་གོ། །མཉན་པར་འོས་པའི་སྤྱོད་ལམ་གྱིས་གནས་པ་རྣམས་ལ་ཞེས་བྱ་བ་ནི་མདོ་ལས་དུས་སུ་ཞེས་འབྱུང་བའི་ཕྱིར་རོ། །གླེང་བསླང་བ་དང་བཅས་པ་ཞེས་བྱ་བ་ནི་མདོ་ལས་{རྨེང་}དང་བཅས་པ་ཞེས་འབྱུང་བའི་ཕྱིར་
རྟགས་འདི་ག་རེ་ཡིན་ནམ། འདིའི་ཐིག་ཕྲེང་བཞི་པའི་ནང་དུ་(གླེང་) ཞེས་གསལ་བ་དེ་(གླིང་,གླེང་) ཞེས་བཀོད་རོགས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/120_མདོ་སྡེ།_དི.txt
> +[131a.7]པ་དེ་དག་ནི་བསྟན་བཅོས་ཐེག་པ་ཆེན་པོ་བསྡུས་པའི་འགྲེལ་པ་སློབ་དཔོན་དབྱིག་གཉེན་དང་། ངོ་བོ་ཉིད་མེད་ཀྱིས་#མཛད་པ་དང་། ལང་#གི་ཚེ་བསྒྱུར་བ་དང་། མདོ་སྡེའི་རྒྱན་དང་། ཆོས་མངོན་པ་ཀུན་ལས་བཏུས་པ་དང་། ཆོས་མངོན
འདིར་མ་དཔེར་ལ་དབྱེག་གཉིན་ཞེས་གསལ་བས་(དབྱེག་གཉིན་,དབྱིག་གཉེན་)ཞེས་དོགས་རྟགས་བཀོད་པ་ལས་ཁ་ཐུག་མ་བཟོ་རོགས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/147_མངོན་པ།_ཉུ.txt
> +[26b.6]བཞིན་ཉིན། །སྔ་མ་ཇི་བཞིན་དེ་བཞིན་ཕྱིས། །ཕྱི་མ་ཇི་བཞིན་དེ་བཞིན་སྔར། །ཇི་ལྟར་འོག་ཏུ་དེ་ལྟར་སྟེང་། །སྟེང་དུ་ཇི་ལྟར་དེ་བཞིན་འོག །རྟག་ཏུ་དབང་པོ་བསྡམས་ཤིང་སྤྱོད། །ཚད་མེད་པ་ཡི་ཏིང་འཛིན་གྱིས། །ཕྱོགས་ཀུ
འདིར་མ་དཔེར་བསློབ་ཅེས་གསལ་བས་(བསློབ་,སློབ་)ཅེས་འབྲི་རོགས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/158_འདུལ་བ།_ཛུ.txt
> +[183a.4]གཙང་སྦྱོར་བ་ནི་ཟས་ཀྱི་ཞལ་ཏ་པའོ། །འབྲུ་མར་གྱི་སྣོད་ཅེས་བྱ་བ་ནི་པགས་པ་ལས་བྱས་པ་འབྲུ་མར་གྱི་སྣོད་ཀྱི་ཀོ་སྐུའོ། །ཁ་ཏོན་ཀློགས་ཤིག་ཅེས་བྱ་བ་ནི་ཀློག་ཏུ་བཅུག་པ་ཡིན་ནོ། །ཨུཏྤལ་འམ་ཞེས་བྱ་བའམ་གྱི་སྒྲ་ནི
འདིར་མ་དཔེར་ཨུཏྤ་ལ་འམ་  ཞེས་གསལ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/160_འདུལ་བ།_ཞུ.txt
> +[176a.7]འདི་ལྟུང་བ་འབྱིན་པར་བྱེད་པ་ལས་གང་ཟག་གཞན་ལ་བསྔོས་པ་ལ་སྟེ་དེ་ཉིད་ལ་ནི་མ་ཡིན་ནོ། །རང་གིས་#བསྔོས་པ་ལ་བདག་ཉིད་ལ་བསྔོས་པ་ནི་འགོད་པ་མ་ཡིན་ནོ། །དེ་ལ་ཡང་ཉེས་བྱས་སུ་འབྱུང་བར་འགྱུར་ཏེ། དེ་བས་ན་གཞན་གྱིས་
མ་དཔེར་འགེད་ཅེས་གསལ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/166_འདུལ་བ།_ཤུ.txt
> +[227a.4]པ། ཕྱིར་མི་འོང་བའི་འབྲས་བུ་དང་ལྡན་པར་འགྱུར་རོ། །ད་ལྟར་ཏེ་ང་དེ་སྐད་དུ་སྨྲས་ན་གཞན་ཡིད་ཆེས་པར་འགྱུར་རོ། །འོན་ཀྱང་ཕྱིར་མི་འོང་བ་ཡིན་པས་རང་ཉིད་ཀྱང་བདག་དང་མཉམ་པ་ཉིད་དུ་ཀུན་དུ་བསྟན་པའི་ཕྱིར་དེ་ལས་གཞ
འདིར་མ་དཔེར་ཏེང་ཞེས་གསལ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/172_སྐྱེས་རབས།_གེ.txt
> +[181b.1]པའོ།། །།དྲི་ཞིམ་སྣ་ཚོགས་ཀྱིས་བསྒོས་པས། །བདེ་བར་གཤེགས་ལ་ཁྲུས་གསོལ་བ། །མེ་ཏོག་དྲི་ཡིས་ཡན་ལག་མཛེས། །རབ་ཏུ་དགའ་བའི་ཡིད་ཀྱིས་སུ། །རོལ་མོའི་སྒྲ་ནི་སྙན་པ་ཡིས། །དལ་གྱིས་འབབ་དང་སྟེགས་{འགྲུན}་བརྗིད། །ག
འདིའི་རྟགས་ག་རེ་ཡིན་ནམ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/184_ཚད་མ།_བེ.txt
> +[254b.1]དུ་མཐོང་བའི་རྒྱུད་ཀྱང་གཅིག་ཏུ་འཛིན་པའི་འབྲས་བུ་ཉིད་ཀྱིས་དེ་ལྟར་མངོན་པར་རློམ་པའི་{སྤྲལ}་ཡིན་ནོ་ཞེས་བརྗོད་པ་ནི། གཅིག་པ་ཉིད་ཀྱིས་ཐ་སྙད་འདི་ཞེས་བྱ་བའོ། །འདི་ནི་དབང་པོ་དུ་མ་ལས་བྱུང་བའི་མཐོང་བ་རྣམས
འདི་ག་རེ་ཡིན་ནམ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/186_ཚད་མ།_ཙེ.txt
> +[30a.2]ཡང་མྱུ་གུའི་སྐྱེད་བྱེད་དུ་འགྱུར་བ་མ་ཡིན་ནོ། །དངོས་པོ་ལ་ཅིའི་ཕྱིར་ཚད་མ་མ་ཡིན་ཞེ་ན། དེ་ལས་ཐེ་ཚོམ་དག་ཅེས་བྱ་བའོ། །དེར་ཞེས་བྱ་བ་ནི་དོན་ལའོ། །དེ་ལྟ་མ་ཡིན་ན་ཞེས་བྱ་བ་ནི་དམ་བཅའ་བའི་ཚིག་དོན་དང་མ་འབྲེལ
རྟགས་འདི་ཚོ་ག་རེ་ཡིན་ནམ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/186_ཚད་མ།_ཙེ.txt
> +[95b.2]བར་བྱ་བ་ཉིད་དུ་གྲུབ་ཀྱི། སྤྱི་ནི་མ་ཡིན་ནོ་ཞེས་བྱ་བའི་དོན་ཏོ། །འདི་ཡན་ཆད་ཀྱིས་ནི། རྣམ་ཀུན་བརྗོད་བྱའི་དངོས་མིན་ཕྱིར། །ཞེས་བྱ་བ་བཤད་པ་ཡིན་ནོ། །ཚད་མས་ཞེས་བྱ་བ་ལ་སོགས་པས་ནི། གྲུབ་པ་དེ་ལ་བརྟེན་པའི་ཕ
འདི་ཡང་ག་རེ་ཡིན་ན།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/186_ཚད་མ།_ཙེ.txt
> +[206b.6]ཉིད་དུ་ཞེས་བྱ་བའོ། །འོ་ན་ཞེས་བྱ་བ་ནས་ཞེ་ནའི་བར་ནི་རྩོད་པའོ། །སྔོན་པོའི་སྒྲ་བརྗོད་མ་ཐག་ཏུ་ནི་ཅི་ཨུཏྤལ་འམ་དེ་སྟེ་གཞན་ཡིན་ཞེས་ཐེ་ཚོམ་ཟ་བ་ནི་སྒྲ་གཞན་ལས་ཏེ། ཨུཏྤལ་བཟློག་པ་ཡིན་ནོ། །བསྡུ་བས་རྟོགས་པ་
འདིར་ཡང་མ་དཔེར་ཨུཏྤ་ལ་འམ་  ཞེས་གསལ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/186_ཚད་མ།_ཙེ.txt
> +[244a.4]པ་གང་ཡིན་ཞེ་ན་འོན་ཀྱང་ཞེས་བྱ་བའོ། །འོ་ན་དངོས་པོའི་འཇིག་པ་ཞེས་ཐ་དད་པའི་ཐ་སྙད་དུ་ཅི་ལྟར་འགྱུར་ཞེ་ན། {མཚི་}གུའི་ཞེས་བྱ་བའོ། །གཞན་ཡང་ཞེས་བྱ་བ་ལ་སོགས་པས་ནི་དེས་ན་དཔེ་དེས་ཞེས་བྱ་བ་ལ་སོགས་པ་སུན་འབྱི
རྟགས་འདི་ག་རེ་ཡིན་ནམ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/189_ཚད་མ།_ཝེ.txt
> +[123a.7]འགྱུར་གྲང་ཞེས་བརྟག་པ་རྣམ་པ་གཉིས་སོ། །དེ་ལ་བརྟག་པ་དང་པོའི་དབང་དུ་བྱས་ནས་གལ་ཏེ་དངོས་པོ་རང་གི་ངོ་བོས་འཇིག་པ་ཡིན་ན་ཞེས་བྱ་བ་ལ་སོགས་པ་སྨོས་ཏེ། གལ་ཏེ་དངོས་པོ་རང་གི་ངོ་བོ་ཁོ་ནས་འཇིག་པ་ཡིན་ན་འཇིག་པའི
རྟགས་་་་་་

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[131a.6]ད་ཡང་དག་པར་བསྔགས་པ་ལའོ། །རུ་དིར་{མཚི}་མ་འཛག་པ་ལའོ། །མ་དཱི་དགའ་བ་ལའོ། །མ་དི་བླུན་པ་ལའོ། །ཙ་དི་ཀུན་དུ་ཚིམ་པ་ལའོ། །འདི་རྣམས་ལས་རཀ་ཕ་རོལ་ཏུ་འགྱུར་རོ། །ཀ་ཡིག་ཀིཏུ་ལའོ་ཞེས་པའི་རྟགས་དོན། ཀཏ྄་ལ་ཧལ་གྱ
རྟགས་་་

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[61a.7]བར་བཤད་པས་སོ། །ཨཱམྲ། ཨཱམྲ། མ་རྣམས་ཀྱི་དྲུག་རྣམས་ཁྱི་བུ། །ཚིག་སྦྱོར་དེ་བཞིན་དུ་བྱས་པས། མ་གཉིས་ཀྱི་བུ། དྭཻ་མཱ་ཏུ་རཿ མ་དྲུག་གི་བུ་སྟེ་གཞོན་ནུ་གདོང་དྲུག། ཏྲཻ་མ་ཏུ་རཿ མ་གསུམ་གྱི་བུ། ༈ དྲང་སྲོང་མ་ཡི
དྲུག་རྣམས་ཀྱི་བུ། ཞེས་གསལ།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/198_གསོ་རིག_ཧེ.txt
> +[29a.3]ཛེ་དང་། ཏི་ཏ་ཕེ་ནེེ་དང་། ཕེ་ནི་ལོ་དང་། གྷརྦ་ཏ་ན་དང་། དེ་དག་ནི་པུང་ཏ་གི་མིང་ངོ་། །སུ་ཏ་ཛི་བ་དང་། བ་བཻ་ཏྲ་དང་། མནྟྲ་སིདྡྷ་ཀྲ་དང་། དེ་དག་ནི་པོ་དོ་{ཅེའི་}མིང་ངོ་། །ཀུ་སྨན་ཏ་ཀི་དང་། ཕོཥྚ་ཕ་ལ་དང་། པ
རྟགས་་་་

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/202_གསོ་རིག_གོ.txt
> +[298b.3]བ་སློབ་མ་རྣམས་ཀྱི་ནང་ན་བསྔགས་ལ། །མེ་བཞིན་འཇུག་ཅེས་བྱ་བས་བློ་ལ་ངེས་རྙེད་པའི་ཐེ་ཚོམ་འདི་རྒྱུན་ཤེས་ཀྱི་བུ་ལ་དྲིས་པར་གྱུར་ཏོ། །སྐལ་ལྡན་ཁ་ཅིག་བདག་ཉིད་མཁས། །སྨན་དང་ནད་གཡོག་ཕུན་སུམ་ཚོགས། །སྨན་པ་རྒན་
འདིར་མ་དཔེར་བསློབ་ཅེས་གསལ་བས་(བསློབ་,སློབ་) ཅེས་འབྲི་རོགས།

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/204_སྣ་ཚོགས།_ཅོ.txt
> +[160a.6]ནོ། །ཕོ་བྲང་འོན་ཅང་དོར་བོད་དང་རྒྱ་གར་གྱི་མཁན་པོ་ཐམས་ཅད་ཀྱིས་ཆོས་སྐད་གཏན་ལ་ཕབ་སྟེ། རྗེ་བློན་མོལ་ནས་རེག་{ཟིད་}དུ་མཛད་པ་སྐད་གསར་གྱི་མིང་སྔོན་མ་ཐོགས་པ་དང་། གཏན་ལ་མ་ཕབ་པ་ལ་མཁས་པ་རྣམས་འཚོགས་ཏེ་མིང་
རྟགས་་་་་་

2018-10-20 15:50 UTC, rekongrabten commented on derge-tengyur-tags/212_སྣ་ཚོགས།_པོ.txt
> +[143b.4]ངེས་ཟིན་སླར་ཡང་བསྐོར་བའོ། །བརྒྱལ་དང་མྱོས་དང་འབོག་པ་དང་། །མནར་བ་དང་ནི་{མཚིར་}བའོ། །རྨས་པ་ལུས་ཉམས་ལྟུང་བའོ། །འགྲས་དང་རྩེན་དང་སླར་བྱེད་དང་། །འཁོན་ཞུགས་པ་དང་ཤ་འཁོན་ཞུགས། །འཇིགས་དང་བྷོ་ལོ་སྙིང་སྟོ
རྟགས་་་་་

2018-10-22 07:18 UTC, tibetanboy commented
༢༠༡༨།༡༠།༢༢

2018-10-22 07:19 UTC, tibetanboy commented
༢༠༡༨།༡༠།༢༢

2018-10-22 08:36 UTC, tibetanboy commented
༢༠༡༨།༡༠།༢༢

2018-10-22 08:37 UTC, tibetanboy commented
བསྐྱར་བཅོས་བྱས་ཡོད།

2018-10-22 08:38 UTC, tibetanboy commented
བསྐྱར་བཅོས་བྱས་ཡོད།

2018-10-22 08:43 UTC, closed without merging

2018-10-22 08:45 UTC, tibetanboy commented
༢༢

2018-10-22 08:45 UTC, tibetanboy commented
༢༢