25
Esukhia/derge-tengyur-old pull request #6
Opened 2018-08-31 09:49 UTC by tibetanboy

2018-08-31 09:57 UTC, ngawangtrinley requested changes
བར་སྟོང་མ་གསུབ་རོགས།
དབུ་འཁྱུད་དང་{}བར་ལ་བར་སྟོང་མ་བཞག་རོགས།
གཉིས་ཤད་དམ་བཞི་ཤད་ཡོད་སར་ཤད་ཀྱི་ནང་དུ་མ་འཇོག་རོགས།

2018-09-01 05:17 UTC, tibetanboy commented
update

2018-09-01 05:25 UTC, rekongrabten requested changes
བཟོ་རོགས་གནོངས།

2018-09-01 05:25 UTC, rekongrabten commented on derge-tengyur-tags/001_བསྟོད་ཚོགས།_ཀ.txt
> +[61a.3]སྔ་ནས་དང་། ཞུ་ཆེན་གྱི་ལོ་ཙཱ་བ་དགེ་སློང་རིན་ཆེན་བཟང་པོས་བསྒྱུར་ཅིང་གཏན་ལ་ཕབ་པའོ།།{T1114} ༄༅༅། །རྒྱ་གར་སྐད་དུ། བུདྡྷ་སྱ་སྟོ་ཏྲ་ནཱ་མ། བོད་སྐད་དུ། སངས་རྒྱས་ཀྱི་བསྟོད་པ་ཞེས་བྱ་བ། འཇམ་དཔལ་གཞོན་ནུར་ག
སྟོང་པ་དེ་མདུན་ལ་འཇོག་རོགས།

2018-09-01 05:25 UTC, rekongrabten commented on derge-tengyur-tags/001_བསྟོད་ཚོགས།_ཀ.txt
> +[68b.4]མཛད་པ་རྫོགས་སོ།། །།རྒྱ་གར་གྱི་མཁན་པོ་ཀྲྀཥྞ་nཔཎྜི་ཏ་དང་། ལོ་ཙཱ་བ་དགེ་སློང་nཚུལ་ཁྲིམས་རྒྱལ་བས་བསྒྱུར་བའོ།། {T1120}འཇིག་རྟེན་ལས་འདས་པར་བསྟོད་པ།n༄༅༅། །རྒྱ་གར་སྐད་དུ། ལོ་ཀཱ་ཏཱི་ཏ་སྟ་བཾn། བོད་སྐད་དུ
ཆོས་མཚན་གྱི་མགོ་ལ་དབུ་ཁྱུད་ཅིག་འབྲི་རོགས།

2018-09-01 08:29 UTC, ngawangtrinley approved these changes

2018-09-01 08:36 UTC, merged