2018-10-26-
Esukhia/derge-tengyur-old pull request #62
Opened 2018-10-26 11:18 UTC by tashikuncok

update

2018-10-29 11:21 UTC, tashikuncok commented
བཏང་ཚར་ཡིན།

2018-10-30 11:13 UTC, tashikuncok commented
དེ་རིང་ལས་ཀ་བཏང་ཚར་ཡིན།

2018-10-31 14:07 UTC, rekongrabten requested changes
འདི་དག་བསྐྱར་དུ་གཟིགས་རྒྱུ་དང་ནོར་འཁྲུལ་གང་བཟོ་ཡང་མ་དཔེ་ལ་ནན་གྱིས་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/006_རྒྱུད་འགྲེལ།_ཅ.txt
> +[188a.3]ནི་དབང་པོ་ཐམས་ཅད་དེ། །ཤིན་ཏུ་ཚིམ་པ་ཡིས་ནི་གཞོམ། །ཉན་ཐོས་སྤྱོད་པ་བསྐྱང་བའི་ཕྱིར། །དབང་ཕྱུག་ཉིད་ནི་རྟག་ཏུ་འབྱུང་། །ཐམས་ཅད་སྐྲག་པར་མི་བྱེད་དེ། །སྲོག་ཆགས་རྣམས་ཀྱི་དངོས་པོ་རྣམས། །བསྐྱང་བ་དང་ནི་ཐར་
འདི་ལ་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/020_རྒྱུད་འགྲེལ།_ཛ.txt
> +[73b.3]རབ་བསྒོམས་པས་ཨ་ཝ་དྷཱུ་ཏཱིའི་མཚན་ཉིད་བྱ་བ་སྟེ་རྒྱུན་དུ་དེ་ལྟར་རོ། །འཁྲུལ་འཁོར་གྱི་འཁོར་ལོ་དགུ་པའོ། །ད་ནི་འཁྲུལ་འཁོར་གྱི་འཁོར་ལོ་བཅུ་བ་དེའི་ཕྱི་རོལ་དུ་གསུངས་པ། ཧ་ས་ཧ་ཞེས་བྱ་བ་ལ་སོགས་པ་སྟེ། ཧ་ས་ཧ
འདི་ལ་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/042_རྒྱུད་འགྲེལ།_དི.txt
> +[208a.7]ཡིན་ལ་མི་(བསྤྱོད་,བསྐྱོད་)པ་ལ་སོགས་པའི་རང་གི་དཀྱིལ་འཁོར་པ་ཡང་ཡིན་པས་མ་ལུས་པའི་དཀྱིལ་འཁོར་པ་སྟེ། དེ་རྣམས་ཀྱི་གཟུགས་སུ་རང་གི་སྙིང་པོ་ལས་བྱུང་བ་སྟེ། རང་གི་ས་བོན་ལས་སྐྱེས་པར་བསམ་མོ། ཆོ་ག་ཞེས་བྱ་བ
འདིར་མ་དཔེ་བསྐྱོད་ཅེས་གསལ།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/061_རྒྱུད་འགྲེལ།_ཨི.txt
> +[67b.7]དང་། ཕྱག་གཡོན་གྱི་སོར་མོ་དབུས་མའི་རྩེ་མོས་རྡོ་རྗེ་འཁོར་ལོ་བསྟོད་པ་ལ་བརྩོན་པ། ཕྱག་གཡས་པས་(གདེན,གདན་)ལ་བརྟེན་པ་དང་བཅས་པས་བཞུགས་པའོ། །དེའི་གཡོན་ལོགས་སུ་དྲི་མ་མེད་པའི་གསེར་གྱི་སྐུ་མདོག་ཅན། རྡོ་རྗེ
འདིའི་དོགས་རྟགས་ཀྱི་ནང་ལ་ཚེག་ཆད་འདུག

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/061_རྒྱུད་འགྲེལ།_ཨི.txt
> +[280b.7]ཟླ་བའི་དཀྱིལ་འཁོར་ལ་སོགས་པ་བཀོད་ལ། སྙིང་གར་མི་(བསྤྱོད་,བསྐྱོད་)པ་རྣམ་པར་བསམ་མོ། །དཔྲལ་བར་ནི་རིན་ཆེན་འབྱུང་ལྡན། །ལྐོག་མ་ནི་འོད་དཔག་ཏུ་མེད་པ། སྤྱི་བོར་དོན་ཡོད་པར་གྲུབ་པ། མིག་གཉིས་སུ་སངས་རྒྱས་སྤ
འདིར་ཡང་མ་དཔེ་བསྐྱོད་ཅེས་གསལ།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/061_རྒྱུད་འགྲེལ།_ཨི.txt
> +[313b.1]ཉམ་ཐག་སེལ་ཅིང་རབ་ཏུ་འདོད་པའི་བདེ་བ་ལྡན་པར་སྒྲུབ་ལ་བརྩོན། །ཁྱབ་བདག་རྣམས་སངས་རྒྱས་ལ་རྟག་པར་རབ་ཏུ་ཕྱག་བགྱི་བདག་གི་བློ་གྲོས{་འདམུན་,འདི། མུན་}པ་ལྟ་བུས་བརྩོན་པས་རྒྱུད་ཀྱི་དོན་ཆེན་སོ་སོར་དབྱེ་བར་ག་
འདི་ཡང་ནོར་འདུག་པས་ཡང་བསྐྱར་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/076_རྒྱུད་འགྲེལ།_བུ.txt
> +[39a.4]དུ་བྱ་བའི་ཆོ་ག་བཤད་པར་བྱ་བའོ། །དེ་ནི་སྔོན་བཤད་པའི་རིམ་པས་བཅོམ་ལྡན་འདས་མ་ཡོངས་སུ་རྫོགས་པར་བྱ་བ་ལས། གཞན་ཡང་ས་བོན་དང་ཕྱག་མཚན་དམར་པོ་ཡོངས་སུ་གྱུར་པ་ལས་སྒུ་མདོག་དམར་མོར་རྣམ་པར་བསྒོམས་ཤིང་ལེགས་པར་མཆ
འདི་ཡང་ནོར་འདུག

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/130_སེམས་ཙམ།_ཞི.txt
> +[36a.1]པའི་སྡོམ་པ་ནི་བསམ་པ་ཉམས་པ་ཁོ་ནས་ལེན་པར་མི་འགྱུར་བར་ཁོང་དུ་ཆུད་པར་བར་བྱ་སྟེ། གང་ལ་ལ་དག་གཞན་གྱི་རྗེས་སུ་འཇུག་པའམ། རྙེད་པ་དང་བཀུར་སྟིའི་ཕྱིར་བསྙེན་གནས་པའི་སྡོམ་པ་ཡང་དག་པར་ལེན་པར་དམ་འཆའ་བ་དེ་དག་ཀྱ
འདིར་ཡང་བསྐྱར་དུ་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/157_འདུལ་བ།_ཚུ.txt
> +[151a.5]པའི་ཡ་མཚན་བླ་ན་མེད་པའོ། །ཚར་གཅད་ཅེས་བྱ་བ་ནི་བསྡིགས་པའོ། །ཀུན་དུ་དགའ་བར་མཛད་ཅེས་བྱ་བ་ནི་རབ་ཏུ་དད་པར་མཛད་པའོ། །རངས་པར་མཛད་ཅེས་བྱ་བ་ནི་ཐ་མལ་པར་བར་གནས་པར་མཛད་པའོ། །ཆོས་ཐོབ་པར་གྱུར་ཅིག་ཅེས་བྱ་བ་ནི
འདི་ཡང་བསྐྱར་དུ་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/157_འདུལ་བ།_ཚུ.txt
> +[156b.4]ལ་སོགས་པ། སློང་བ་དང་ཟ་བ་གཉིས་ཀའི་དུས་སུ་མི་ན་པ་ཡིན་ན་སྦྱོར་བ་ལ་ཉེས་བྱས་སུ་འགྱུར་ལ། དངོས་གཞི་ལ་ལྟུང་བྱེད་དུ་འགྱུར་ལ། གཅིག་མི་ན་པ་ཡིན་ན་ཉེས་བྱས་སུ་འགྱུར་རོ། །གཉིས་ཀ་ན་བ་ཡིན་ན་ལྟུང་བ་མེད་དོ། །བས
འདིར་ཡང་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/162_འདུལ་བ།_འུ.txt
> +[102a.7]སྡེ་ཚན་དེ་ལ་གལ་ཏེ་དངོས་གཞིའི་ཡིན་ན་སྦོམ་པོའོ་ཞེས་བྱ་བ་སྨྲས་ཏེ། ཕམ་པར་བར་འགྱུར་བའི་སྡེ་ཚན་དེ་ལ་སྦྱོར་བ་དེ་གལ་ཏེ་དངོས་གཞིའི་ཡིན་ན་སྦྱོར་བ་དེ་ལ་སྦོམ་པོའོ། །ཇི་སྟེ་སྦྱོར་བའི་སྦྱོར་བ་ཡིན་ན་དེ་ལ་ནི
འདིར་ཡང་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/162_འདུལ་བ།_འུ.txt
> +[105a.2]སྐད་བསྟན་ཏེ། གང་ནས་མི་སྣང་བར་འགྲོ་བའི་རྐང་པ་བཏེག་པའི་རྐང་པ་བཏེག་པ་དེ་ནི་སྦྱོར་པ་ཉིད་ཡིན་ནོ། །རྐང་པ་བཏེག་པ་སྔ་མ་གཞན་དག་ལ་ནི་སྦྱོར་བ་ཐ་དད་པ་ཉིད་ཡིན་ནོ། །དེས་ན་མི་སྣང་བར་འགྲོ་བའི་ཕྱིར་རྐང་པ་བཏེག
འདིར་ཡང་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/162_འདུལ་བ།_འུ.txt
> +[161b.4]ནི་ཉེས་བྱས་སུ་འགྱུར་རོ་ཞེས་བྱ་བའི་ཐ་ཚིག་གོ། །བྱེད་པ་པོ་ཉིད་བུད་མེད་དོ་ཞེས་སྨྲས་ན་ཅི་ཐམས་ཅད་ཀྱིའམ་འོན་ཏེ་བྱེ་བྲག་འགའ་ཞིག་ཡོང་ཅེ་ན། དེའི་ཕྱིར་འོག་མ་གསུམ་ལ་ལེགས་པར་སྨྲས་པ་དང་ཉེས་པར་སྨྲས་པ་དག་གི་
འདིར་ཡང་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/164_འདུལ་བ།_རུ.txt
> +[82a.1]འདྲའོ། །ལན་ཅིག་ཆུར་བསུབས་ན་ཡང་དེ་བཞིན། བྱས་ན་བྱེད་དུ་བཅུག་པའོ་ཞེས་པ་ནི་བཅོལ་བ་ཙམ་#གྱིས་མ་ཡིན་གྱི། དགེ་སློང་མས་བཀྲུ་བ་ལ་སོགས་པའི་ལས་བྱས་ན་གདོད་བྱེད་དུ་བཅུག་པར་བར་ཆུད་པའོ། །ཟིན་གྱི་བར་དུ་གཅིག་གོ
འདིར་ཡང་གཟིགས་རོགས།

2018-10-31 14:07 UTC, rekongrabten commented on derge-tengyur-tags/197_སྒྲ་མདོ།_སེ.txt
> +[273b.6]([ཧྲ],ཀྲྀ)ཤཱ་ནུ་ཆུང་གྱེད་ལུས་ངན་གྱི་ནི་ཀུ་མུད་མཚུངས། །མེ་ལྷའི་ཀི་མ་ཤུ་སྨིན་བྱེད་པཱ་བཱཀ་ག་ཡི་འོད། །དེ་བཞིན་རླུང་ལྷའི་སྣ་ཚོགས་མདོག། །ཅེས་བཤད་དོ། །རླུང་གི་འཚོ་བྱེད་ཨན་ལ་གྲོགས་པོ་འདི་ཡིན་པས་རླུང་
འདིར་ཡང་གཟིགས་རོགས།

2018-11-02 00:40 UTC, rekongrabten requested changes

2018-11-02 00:40 UTC, rekongrabten commented on derge-tengyur-tags/001_བསྟོད་ཚོགས།_ཀ.txt
> +[28a.4]གྱུར་ན། འདི་རྒྱས་པར་གྱུར་ན་དེ་རྒྱས་པར་འགྱུར་རོ། །དེ་ཡང་ཞུམ་པ་ནི་འདུས་པར་གྱུར་པ་སྟེ། དེ་གང་ལ་ཡོད་པ་དང་། ཆོས་པ་ནི་བརྐྱང་པར་བར་གྱུར་པ་སྟེ། དེ་ནི་སྲོག་དང་། འཚོ་བ་དང་། བདག་ཅེས་བྱ་བ་ཡིན་ནོ་ཞེས་ཟེར་ཏ
འདི་ལ་གཟིགས་རོགས།

2018-11-02 00:40 UTC, rekongrabten commented on derge-tengyur-tags/006_རྒྱུད་འགྲེལ།_ཅ.txt
> +[188a.3]ནི་དབང་པོ་ཐམས་ཅད་དེ། །ཤིན་ཏུ་ཚིམ་པ་ཡིས་ནི་གཞོམ། །ཉན་ཐོས་སྤྱོད་པ་བསྐྱང་བའི་ཕྱིར། །དབང་ཕྱུག་ཉིད་ནི་རྟག་ཏུ་འབྱུང་། །ཐམས་ཅད་སྐྲག་པར་མི་བྱེད་དེ། །སྲོག་ཆགས་རྣམས་ཀྱི་དངོས་པོ་རྣམས། །བསྐྱང་བ་དང་ནི་ཐར་
འདི་ལ་གཟིགས་རོགས།

2018-11-02 00:40 UTC, rekongrabten commented on derge-tengyur-tags/020_རྒྱུད་འགྲེལ།_ཛ.txt
> +[73b.3]རབ་བསྒོམས་པས་ཨ་ཝ་དྷཱུ་ཏཱིའི་མཚན་ཉིད་བྱ་བ་སྟེ་རྒྱུན་དུ་དེ་ལྟར་རོ། །འཁྲུལ་འཁོར་གྱི་འཁོར་ལོ་དགུ་པའོ། །ད་ནི་འཁྲུལ་འཁོར་གྱི་འཁོར་ལོ་བཅུ་བ་དེའི་ཕྱི་རོལ་དུ་གསུངས་པ། ཧ་ས་ཧ་ཞེས་བྱ་བ་ལ་སོགས་པ་སྟེ། ཧ་ས་ཧ
འདིར་ཡང་གཟིགས་རོགས།

2018-11-02 00:40 UTC, rekongrabten commented on derge-tengyur-tags/076_རྒྱུད་འགྲེལ།_བུ.txt
> +[223b.6]མཀྲྀ་ཏེ། ཡེ་ན་ཀེ་ན་ཙི་ཏ་ཀྲྀ་ཏཾ། སརྦནྟུ་ཚིནྡ་ཚིནནྡ་བྷི་ནྦྷ་བྷིནྡྷ་ཙི་རི་ཙི་རི་གི་རི་གི་རི་མ་ར་མ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཧཱུཾ་ཕཊ་ཕཊ་ཕཊ། ཨོཾ་སུམྦྷ་ནི་སུམྦྷ་ཧཱུཾ། ག
འདི་ལ་ཡང་བསཀྻར་དུ་གཟིགས་རོགས།

2018-11-02 00:40 UTC, rekongrabten commented on derge-tengyur-tags/157_འདུལ་བ།_ཚུ.txt
> +[151a.5]པའི་ཡ་མཚན་བླ་ན་མེད་པའོ། །ཚར་གཅད་ཅེས་བྱ་བ་ནི་བསྡིགས་པའོ། །ཀུན་དུ་དགའ་བར་མཛད་ཅེས་བྱ་བ་ནི་རབ་ཏུ་དད་པར་མཛད་པའོ། །རངས་པར་མཛད་ཅེས་བྱ་བ་ནི་ཐ་མལ་པར་བར་གནས་པར་མཛད་པའོ། །ཆོས་ཐོབ་པར་གྱུར་ཅིག་ཅེས་བྱ་བ་ནི
འདི་ཡང་གཟིགས་རོགས།

2018-11-02 00:40 UTC, rekongrabten commented on derge-tengyur-tags/162_འདུལ་བ།_འུ.txt
> +[161b.4]ནི་ཉེས་བྱས་སུ་འགྱུར་རོ་ཞེས་བྱ་བའི་ཐ་ཚིག་གོ། །བྱེད་པ་པོ་ཉིད་བུད་མེད་དོ་ཞེས་སྨྲས་ན་ཅི་ཐམས་ཅད་ཀྱིའམ་འོན་ཏེ་བྱེ་བྲག་འགའ་ཞིག་ཡོང་ཅེ་ན། དེའི་ཕྱིར་འོག་མ་གསུམ་ལ་ལེགས་པར་སྨྲས་པ་དང་ཉེས་པར་སྨྲས་པ་དག་གི་
འདི་ལ་ཡང་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-02 00:40 UTC, rekongrabten commented on derge-tengyur-tags/164_འདུལ་བ།_རུ.txt
> +[82a.1]འདྲའོ། །ལན་ཅིག་ཆུར་བསུབས་ན་ཡང་དེ་བཞིན། བྱས་ན་བྱེད་དུ་བཅུག་པའོ་ཞེས་པ་ནི་བཅོལ་བ་ཙམ་#གྱིས་མ་ཡིན་གྱི། དགེ་སློང་མས་བཀྲུ་བ་ལ་སོགས་པའི་ལས་བྱས་ན་གདོད་བྱེད་དུ་བཅུག་པར་བར་ཆུད་པའོ། །ཟིན་གྱི་བར་དུ་གཅིག་གོ
འདི་ཡང་བསྐྱར་དུ་བཟོ་རོགས།

2018-11-02 22:59 UTC, rekongrabten approved these changes
ནོར་འཁྲུལ་དག་ངས་བཟོས་ནས་ནང་འདྲེན་བྱས་ཡོད།

2018-11-02 23:08 UTC, rekongrabten approved these changes
ནོར་འཁྲུལ་དག་ངས་བཟོས་ནས་ནང་འདྲེན་བྱས་ཡོད།

2018-11-03 13:17 UTC, rekongrabten approved these changes

2018-11-03 13:18 UTC, merged