ཞུ་དག 2018/10/26
Esukhia/derge-tengyur-old pull request #63
Opened 2018-10-26 11:22 UTC by Sermig

2018-10-28 12:40 UTC, rekongrabten requested changes
ཚིག་དྲུག་ལས་བཟོས་མེད་པ་ལས་ལྔ་ནོར་འདུག་པས་ནན་ཏན་གྱིས་གཟིགས་ཞིབ་གནོངས་རོགས།

2018-10-28 12:40 UTC, rekongrabten commented on derge-tengyur-tags/195_སྒྲ་མདོ།_ལེ.txt
> +[190b.4]མཱི་ཞེས་པ་མཱི་ཉ་འཚེ་བ་ལའོ། །ཌུ་མིཉ་འཕེན་པ་ལའོ་ཞེས་པས་ཡང་ནའོ། །ཌུ་མཱི་ཉ་ལས་ཀྱང་དབྱངས་མཐའ་རྣམས་ཀྱི་སནྲ་ལའོ་ཞེས་པས་རིང་པོ་བྱས་པ་མཱི་ཞེས་པའི་གཟུགས་སུ་འགྱུར་རོ། །མཱ་ཞེས་པ་མཱ་འཇལ་བ་ལའོ། །མཱང་འཇལ་བ་
འདི་ལ་ཚེག་མི་དགོས། རང་འཇགས་འཇོག་རོགས།

2018-10-28 12:40 UTC, rekongrabten commented on derge-tengyur-tags/195_སྒྲ་མདོ།_ལེ.txt
> +[190b.6]ཕ་རོལ་ལ་ཨིས་སུ་བསྒྱུར་བར་འགྱུར་ཏེ། ཨ་བྷྱཱ་ས་དབྱི་བ་འང་ངོ་། །མིཏྶ་ཏི། པྲ་མིཏྶ་ཏི། མིཏྶ་ཏེ། དིཏྶ་ཏི། དྷཏྶ་ཏི། མཱི་ཉ་འཚེ་བ་ལའོ། །པཏླྀ་འགྲོ་བ་ལའོ། །ཌུ་མི་ཉ་ལ་པྲ་སྔོན་དུའོ། །མཱ་འཇལ་བ། ཌུ་དཱཉ། ཌུ་ད
འདི་ཡང་གཅིག་པ་ཡིན།

2018-10-28 12:40 UTC, rekongrabten commented on derge-tengyur-tags/195_སྒྲ་མདོ།_ལེ.txt
> +[230a.3]ཀཱ་ར། ཀཱ་རི། ཨཊའོ། །ཙ་ཀཱ་ས་དང་ཀཱས་དང་རྐྱེན་གྱི་མཐའ་ཞེས་པས་ཨཱམའོ། །ཡོན་ཏན་ནོ། །ཨཱམ་ལས་ཀྲྀཉ་ཞེས་བ་ཀྲྀཉ། །གཉིས་བརྗོད་དོ། །ཨིཊ་ལ། ཀཱ་ར་ཡི་ཏཱ། ཨིཊ་དང་། ཡོན་ཏན་ནོ། །བི་ཀ་ར་ཎ་ལ། ཀཱ་ར་ཡ་ཏི། བུ་རྒྱུད་
འདིའི་འོ་གསུན་འདུག་ཀྱང་མ་གསུབ་རོགས།

2018-10-28 12:40 UTC, rekongrabten commented on derge-tengyur-tags/195_སྒྲ་མདོ།_ལེ.txt
> +[286b.2]མ་ཡིན་ནོ་ཞེས་པས་ཏྲྀཙ་གཟུང་བར་མི་འགྱུར་རོ། །བྷྲཱ་ཛི་ཨ་ལཾ་ཀྲྀཉ་བྷཱུ་ས་ཧི་རུ་ཙི་བྲིཏ་བྲི་དྷ་ཙ་རི་པྲ་ཛན་ཨ་པ་ཏྲ་པ་ཨིན་རྣམས་ཀྱི་ཨིཥྞུའོ། །བྷྲ་ཛྲི་གསལ་བ་ལའོ། །ཨ་ལང་སྔོན་མ་ལས་ཀྲྀཉ། །བྷཱུ་ཡོད་པ་ལའོ། །
འདི་ཡང་མ་གསུབ་རོགས།

2018-10-28 12:40 UTC, rekongrabten commented on derge-tengyur-tags/196_སྒྲ་མདོ།_ཤེ.txt
> +[202a.5]པས་སའི་ཏ་ཡིག་གོ། །མིཏྶ་ཏི། མིཏྶ་ཏེ། དེ་བཞིན་དུ་མིཉ་ཞེས་པ་འདིའི་འང་ངོ་། །མཱིངའི། མིཏྶ་ཏེ། མཱ་འཇལ་བ་ལའོ། །མིཏྶ་ཏི། མིང་། མཱང་། མིཏྶ་ཏེ། ཌུ་དཱཉ། དིཏྶ་ཏི། དིཏྶ་ཏེ། དཱ་ཎི། དོ། །དིཏྶ་ཏི། དེང་། དིཏྶ
འདིའི་ཨ་ཆུང་མ་གསུབ་རོགས།

2018-10-30 11:14 UTC, Sermig commented on derge-tengyur-tags/196_སྒྲ་མདོ།_ཤེ.txt
> +[202a.5]པས་སའི་ཏ་ཡིག་གོ། །མིཏྶ་ཏི། མིཏྶ་ཏེ། དེ་བཞིན་དུ་མིཉ་ཞེས་པ་འདིའི་འང་ངོ་། །མཱིངའི། མིཏྶ་ཏེ། མཱ་འཇལ་བ་ལའོ། །མིཏྶ་ཏི། མིང་། མཱང་། མིཏྶ་ཏེ། ཌུ་དཱཉ། དིཏྶ་ཏི། དིཏྶ་ཏེ། དཱ་ཎི། དོ། །དིཏྶ་ཏི། དེང་། དིཏྶ
ཚང་མ་བཟོས་ནས་བསྐུར་ཡོད།

2018-10-31 13:33 UTC, rekongrabten approved these changes

2018-10-31 13:33 UTC, merged