ནང་འདྲེན
Esukhia/derge-tengyur-old pull request #67
Opened 2018-11-01 11:17 UTC by drakpagyamtso

2018-11-02 00:14 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-02 00:14 UTC, rekongrabten commented on derge-tengyur-tags/056_རྒྱུད་འགྲེལ།_རི.txt
> +[189b.5]པའི་ཁམས་ཀྱི་འདོད་ཆགས་དང་བྲལ་བས་ན་ཚངས་པའོ། །ལུང་དབོག་པ་མེད་པར་ཡེ་ཤེས་ཐུགས    ་སུ་ཆུད་པར། །མཛད་པས་ན་རང་བྱུང་ངོ་། །སྐལ་བ་དང་ལྡན་པའི་ཕྱིར་བཅོམ་ལྡན་འདས་ཏེ་སྐེལ་བ་ཞེས་བྱ་བའི་སྒྲ་ནི་བསོད་ནམས་དང་ཡེ་ཤ
འདི་ལ་སྟོང་པ་ཞིག་ཤོར་འདུག འདི་བསྐྱར་དུ་གསུབ་རོགས།

2018-11-02 00:14 UTC, rekongrabten commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[30a.4]སྟེ། མཐའ་གཉིས་ལ་མི་གནས་པའོ། །དེ་ལ་བརྟེན་ནས་དུཿ ཁཙྪ་ད་སྟེ། སྡུག་བསྔལ་སེལ་བར་བྱེད་ཅིང་གཅོད་པར་བྱེད་པས་ན་སྙིང་རྗེའོ། །གཅོད་པ་དེ་ཉོན་མོངས་པ་རྩ་བ་ནས་མེད་པ་དེ་ཤེས་རབ་རྩེ་གཅིག་པས་འབིགས་པས་ན་བཛྲ་ཏཱིཀྵ
འདིའི་རྒྱབ་ལ་སྟོང་པ་མི་དགོས། ཡིན་ཡང་སྔ་ཕྱི་ལ་ཡང་ནན་གྱིས་གཟིགས་རོགས། མ་དཔེར་དུཿཁཙྪེ་ད་སྟེ། ཞེས་གསལ།

2018-11-02 00:14 UTC, rekongrabten commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[30b.2]ཤིང་ཁྲོ་ཞལ་དྲུག་པ་རྩེ་ལྔ་པ་འགྲེང་བ་སྟེ། ཆོས་ཉིད་གྲུ་གསུམ་ནང་དུའོ། །བུམ་པ་སྟོང་པར་དྷཱིཿ ལས་བྱུང་བའི་མཆོད་རྟེན། དེའི་བུམ་པར་ཤེས་རབ་གྲུ་གསུམ་དུ་ཐབས་རྟེན་ཅིང་འབྲེལ་པའི་ཚུལ་དུ་བྷྜུཾ་ལས་གཞལ་ཡས་ཁང་ངོ
འདི་ཡང་མེད་ན་འགྲིག

2018-11-02 00:14 UTC, rekongrabten commented on derge-tengyur-tags/202_གསོ་རིག_གོ.txt
> +[97a.2]སྐྱུག་ཏུ་གཞུག་པར་བྱའོ། །དེ་ནས་ཐུག་སོགས་རིམ་པར་སྤྱད། །གླ་སྒང་ལ་སོགས་བསྐོལ་བ་བླུད། །ཅེས་བྱ་བ་ལ། དེ་ནས་དེའི་འོག་ཏུ་མ་མ་ཐུག་བ་བླུད་བ་ལ་སོགས་པའི་རིམ་པ་སྤྱད་ཅིང་གླ་སྒང་ལ་སོགས་པའི་སྡེ་ཚན་གྱི་ནང་ནས་བཤ
འདིར་ཐུག་པ་ཞེས་བཟོ་རོགས།

2018-11-02 23:40 UTC, rekongrabten requested changes
ནོར་འཁྲུལ་གྱི་དྲི་བ་རྣམས་བཟོ་རོགས།

2018-11-02 23:40 UTC, rekongrabten commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[47a.2]ཨཱ་ཨཾ་ཨཿ དེ་སྟོང་པའི་སྔགས་སོ། །པྲ་གྲྀ་ཏི་པ་རི་ཤུདྷཿསརྦ་དྷརྨཱ་ཡ་དུ་ཏ། སརྦ་ཏ་ཐཱ་ག་ཏ་ཛྙཱ་ན་ཀཱ་ཡ། མཉྫུ་ཤྲཱི་པ་རི་ཤུདྡྷི་ཏཱ། མུ་པཱ་དཱ་ཡ་ཏི་ཨཿ དེས་ནི་སྤྱན་འདྲེན་པ་དང་གཤེགས་སུ་གསོལ་བའོ། །ཨོཾ་སརྦ་ཏ་ཐཱ
འདི་རྣམ་བཅད་དམ་ཿརྟགས་ཡོད་པ་ཚང་མའི་རྒྱབ་ཏུ་སྟོང་པ་ཡོད་པ་གཅིག་མཚུངས་མིན། འདི་གཉིས་ལ་སྟོང་པ་མི་དགོས་པས་གསུབ་རོགས།

2018-11-03 13:14 UTC, rekongrabten requested changes
འདི་བསྐྱར་དུ་བཟོ་དགོས་པ་དང། སྔོན་གྱི་ནོར་འཁྲུལ་དག་ངེས་པར་བཟོ་རོགས།

2018-11-03 13:14 UTC, rekongrabten commented on derge-tengyur-tags/202_གསོ་རིག_གོ.txt
> +[101b.5]དཀར་པོ་དང་སྐྱེར་པའི་ཁཎྜ་སྦྲང་རྩི་དང་བཅས་པའི་ལྡེ་གུས་རྨ་བསྐུ་བར་བྱའོ། །རྒྱ་ཤུགས་འབྲས་བུ་གསུམ་བླག་ཤའི། །ཤུན་པ་བསྐོལ་བའིཆུ་བླུགས་བྱ། །ནག་ཚུར་གི་ཝཾ་སྤངས་མ་དང་། །དངུལ་རྡོ་བ་བླ་ལྡོང་རོས་ནི། །སྐྱུར་
འདིའི་བར་གྱི་ཚེག་གཅིག་གསུབ་འདུག

2018-11-05 13:18 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-05 13:18 UTC, rekongrabten commented on derge-tengyur-tags/016_རྒྱུད་འགྲེལ།_བ.txt
> +[267b.6]བྱ་ཞེ་ན་རྣམ་པར་དགྱེ་ཞེས་བྱ་བ་ནི་གདབ་པར་བྱ་བའོ། །ཅི་འདི་རྡུལ་ཚོན་གཉིས་པོ་ཁོ་ནས་བྲིའམ། འོན་ཀྱང་གཞན་དག་ཀྱང་དགྱེ་ཞེ་ན། ཐམས་ཅད་ཅེས་བྱ་བ་ལ་སོགས་པ་སྨོས་ཏེ། གཉིས་པོ་ཁོ་ན་མ་ཡིན་གྱི་གཞན་དག་ཀྱང་སྟེ། ཨིན
འདི་མ་དཔེར་མརྐད་ཅེས་གསལ་བའི་དོགས་རྟགས་བཀོད་ན་(མརྐད་,མརྒད་) ཅེས་འབྲི་དགོས།

2018-11-05 13:18 UTC, rekongrabten commented on derge-tengyur-tags/053_རྒྱུད་འགྲེལ།_ཟི.txt
> +[128b.2]དངོས་འགྱུར། །ཤེས་རབ་ཀྱི་ཕྲིན་ཡིག་སློབ་དཔོན་ཆེན་པོ་པདྨ་རྡོ་རྗེས་མཛད་པ་རྫོགས་སོ།། །།པཎྜི་ཏ་ཆེན་པོ་ཤཱནྟ་བྷ་དྲ་དང་། བོད་ཀྱི་ཞུ་ཆེན་གྱི་ལོ་ཙཱ་བ་འགོས་ལྷ་བཙས་ཀྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ།། ༄༅
འདིའི་ཆོས་ཨང་དེ་དབུ་ཁྱུད་ཀྱི་མདུན་ལ་འཇོག་རོགས།

2018-11-05 13:18 UTC, rekongrabten commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[30a.4]སྟེ། མཐའ་གཉིས་ལ་མི་གནས་པའོ། །དེ་ལ་བརྟེན་ནས་དུཿ ཁཙྪ་ད་སྟེ། སྡུག་བསྔལ་སེལ་བར་བྱེད་ཅིང་གཅོད་པར་བྱེད་པས་ན་སྙིང་རྗེའོ། །གཅོད་པ་དེ་ཉོན་མོངས་པ་རྩ་བ་ནས་མེད་པ་དེ་ཤེས་རབ་རྩེ་གཅིག་པས་འབིགས་པས་ན་བཛྲ་ཏཱིཀྵ
སྟོང་པ་འདི་མི་དགོས།

2018-11-05 13:18 UTC, rekongrabten commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[30b.1]པ་ནི་རང་དང་པོའི་སངས་རྒྱས་སུ་མོས་པས་མདུན་དུ་དཀོན་མཆོག་མཆོད་ཅིང་སྡིག་པ་བཤགས་པ་ལ་སོགས་བྱའོ། །ཨ་བྷཱ་བ་སྭ་བྷཱ་བ་བི་ཤུདྡྷཿ ། བཛྲ་ཙཀྵུ་ཨ་ཨཱ་ཨཾ་ཨཿཞེས་པས་སྟོང་པ་ཉིད་དུ་བསམ་མོ། །དེ་ནས་ས་བོན་ཨ་ལས་ཧཱུཾ། ད
སྟོང་པ་འདི་མི་དགོས།

2018-11-05 13:18 UTC, rekongrabten commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[30b.1]པ་ནི་རང་དང་པོའི་སངས་རྒྱས་སུ་མོས་པས་མདུན་དུ་དཀོན་མཆོག་མཆོད་ཅིང་སྡིག་པ་བཤགས་པ་ལ་སོགས་བྱའོ། །ཨ་བྷཱ་བ་སྭ་བྷཱ་བ་བི་ཤུདྡྷཿ ། བཛྲ་ཙཀྵུ་ཨ་ཨཱ་ཨཾ་ཨཿཞེས་པས་སྟོང་པ་ཉིད་དུ་བསམ་མོ། །དེ་ནས་ས་བོན་ཨ་ལས་ཧཱུཾ། ད
སྟོང་པ་འདི་མི་དགོས།

2018-11-05 13:18 UTC, rekongrabten commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[30b.2]ཤིང་ཁྲོ་ཞལ་དྲུག་པ་རྩེ་ལྔ་པ་འགྲེང་བ་སྟེ། ཆོས་ཉིད་གྲུ་གསུམ་ནང་དུའོ། །བུམ་པ་སྟོང་པར་དྷཱིཿ ལས་བྱུང་བའི་མཆོད་རྟེན། དེའི་བུམ་པར་ཤེས་རབ་གྲུ་གསུམ་དུ་ཐབས་རྟེན་ཅིང་འབྲེལ་པའི་ཚུལ་དུ་བྷྜུཾ་ལས་གཞལ་ཡས་ཁང་ངོ
སྟོང་པ་འདི་མི་དགོས།

2018-11-05 13:18 UTC, rekongrabten commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[47a.2]ཨཱ་ཨཾ་ཨཿ དེ་སྟོང་པའི་སྔགས་སོ། །པྲ་གྲྀ་ཏི་པ་རི་ཤུདྷཿསརྦ་དྷརྨཱ་ཡ་དུ་ཏ། སརྦ་ཏ་ཐཱ་ག་ཏ་ཛྙཱ་ན་ཀཱ་ཡ། མཉྫུ་ཤྲཱི་པ་རི་ཤུདྡྷི་ཏཱ། མུ་པཱ་དཱ་ཡ་ཏི་ཨཿ དེས་ནི་སྤྱན་འདྲེན་པ་དང་གཤེགས་སུ་གསོལ་བའོ། །ཨོཾ་སརྦ་ཏ་ཐཱ
འདི་གཉིས་ལ་སྟོང་པ་འདི་མི་དགོས།

2018-11-05 13:18 UTC, rekongrabten commented on derge-tengyur-tags/159_འདུལ་བ།_ཝུ.txt
> +[201b.6]འདུན་གྱིས་གང་དུ་མཚམས་ཆེན་པོའི་ནང་དུ་དགེ་སློང་རྣམས་ཀྱི་ཆོས་གོས་དག་དང་འབྲལ་བར་མི་འགྱུར་བའི་གནང་བ་བྱིན་པ་དེར་དགེ་སློང་རྣམས་སྟོད་གཡོགས་སྨད་གཡོགས་དང་བཅས་པས་འདོང་བར་བྱ་སྟེ། འདི་ལ་ཱའགྱོད་པར་མི་བྱའོ།
དེ་ལ་འ་ཆུང་ཞིག་ཤོར་འདུག

2018-11-07 04:59 UTC, drakpagyamtso commented on derge-tengyur-tags/056_རྒྱུད་འགྲེལ།_རི.txt
> +[189b.5]པའི་ཁམས་ཀྱི་འདོད་ཆགས་དང་བྲལ་བས་ན་ཚངས་པའོ། །ལུང་དབོག་པ་མེད་པར་ཡེ་ཤེས་ཐུགས    ་སུ་ཆུད་པར། །མཛད་པས་ན་རང་བྱུང་ངོ་། །སྐལ་བ་དང་ལྡན་པའི་ཕྱིར་བཅོམ་ལྡན་འདས་ཏེ་སྐེལ་བ་ཞེས་བྱ་བའི་སྒྲ་ནི་བསོད་ནམས་དང་ཡེ་ཤ
བཟོས་ཚར་ཡིན

2018-11-07 04:59 UTC, drakpagyamtso commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[30a.4]སྟེ། མཐའ་གཉིས་ལ་མི་གནས་པའོ། །དེ་ལ་བརྟེན་ནས་དུཿ ཁཙྪ་ད་སྟེ། སྡུག་བསྔལ་སེལ་བར་བྱེད་ཅིང་གཅོད་པར་བྱེད་པས་ན་སྙིང་རྗེའོ། །གཅོད་པ་དེ་ཉོན་མོངས་པ་རྩ་བ་ནས་མེད་པ་དེ་ཤེས་རབ་རྩེ་གཅིག་པས་འབིགས་པས་ན་བཛྲ་ཏཱིཀྵ
བཟོས་ཚར་

2018-11-07 04:59 UTC, drakpagyamtso commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[30b.2]ཤིང་ཁྲོ་ཞལ་དྲུག་པ་རྩེ་ལྔ་པ་འགྲེང་བ་སྟེ། ཆོས་ཉིད་གྲུ་གསུམ་ནང་དུའོ། །བུམ་པ་སྟོང་པར་དྷཱིཿ ལས་བྱུང་བའི་མཆོད་རྟེན། དེའི་བུམ་པར་ཤེས་རབ་གྲུ་གསུམ་དུ་ཐབས་རྟེན་ཅིང་འབྲེལ་པའི་ཚུལ་དུ་བྷྜུཾ་ལས་གཞལ་ཡས་ཁང་ངོ
བཟོས་ཡིན

2018-11-07 05:00 UTC, drakpagyamtso commented on derge-tengyur-tags/202_གསོ་རིག_གོ.txt
> +[97a.2]སྐྱུག་ཏུ་གཞུག་པར་བྱའོ། །དེ་ནས་ཐུག་སོགས་རིམ་པར་སྤྱད། །གླ་སྒང་ལ་སོགས་བསྐོལ་བ་བླུད། །ཅེས་བྱ་བ་ལ། དེ་ནས་དེའི་འོག་ཏུ་མ་མ་ཐུག་བ་བླུད་བ་ལ་སོགས་པའི་རིམ་པ་སྤྱད་ཅིང་གླ་སྒང་ལ་སོགས་པའི་སྡེ་ཚན་གྱི་ནང་ནས་བཤ
བཟོས་ཡིན

2018-11-07 05:00 UTC, drakpagyamtso commented on derge-tengyur-tags/064_རྒྱུད་འགྲེལ།_གུ.txt
> +[47a.2]ཨཱ་ཨཾ་ཨཿ དེ་སྟོང་པའི་སྔགས་སོ། །པྲ་གྲྀ་ཏི་པ་རི་ཤུདྷཿསརྦ་དྷརྨཱ་ཡ་དུ་ཏ། སརྦ་ཏ་ཐཱ་ག་ཏ་ཛྙཱ་ན་ཀཱ་ཡ། མཉྫུ་ཤྲཱི་པ་རི་ཤུདྡྷི་ཏཱ། མུ་པཱ་དཱ་ཡ་ཏི་ཨཿ དེས་ནི་སྤྱན་འདྲེན་པ་དང་གཤེགས་སུ་གསོལ་བའོ། །ཨོཾ་སརྦ་ཏ་ཐཱ
བཟོས་ཡིན

2018-11-07 05:00 UTC, drakpagyamtso commented on derge-tengyur-tags/202_གསོ་རིག_གོ.txt
> +[101b.5]དཀར་པོ་དང་སྐྱེར་པའི་ཁཎྜ་སྦྲང་རྩི་དང་བཅས་པའི་ལྡེ་གུས་རྨ་བསྐུ་བར་བྱའོ། །རྒྱ་ཤུགས་འབྲས་བུ་གསུམ་བླག་ཤའི། །ཤུན་པ་བསྐོལ་བའིཆུ་བླུགས་བྱ། །ནག་ཚུར་གི་ཝཾ་སྤངས་མ་དང་། །དངུལ་རྡོ་བ་བླ་ལྡོང་རོས་ནི། །སྐྱུར་
བཟོས་ཡིན

2018-11-07 05:00 UTC, drakpagyamtso commented on derge-tengyur-tags/016_རྒྱུད་འགྲེལ།_བ.txt
> +[267b.6]བྱ་ཞེ་ན་རྣམ་པར་དགྱེ་ཞེས་བྱ་བ་ནི་གདབ་པར་བྱ་བའོ། །ཅི་འདི་རྡུལ་ཚོན་གཉིས་པོ་ཁོ་ནས་བྲིའམ། འོན་ཀྱང་གཞན་དག་ཀྱང་དགྱེ་ཞེ་ན། ཐམས་ཅད་ཅེས་བྱ་བ་ལ་སོགས་པ་སྨོས་ཏེ། གཉིས་པོ་ཁོ་ན་མ་ཡིན་གྱི་གཞན་དག་ཀྱང་སྟེ། ཨིན
བཟོས་ཡིན

2018-11-07 05:01 UTC, drakpagyamtso commented
གོང་གི་དེ་དག་བཟོས་ཚར་ཡིན

2018-11-07 14:04 UTC, rekongrabten requested changes
བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-07 14:04 UTC, rekongrabten commented on derge-tengyur-tags/006_རྒྱུད་འགྲེལ།_ཅ.txt
> +[88b.2]མཛུབ་མོ་གཉིས་ལྕགས་ཀྱུ་ལྟར་བཀུག་ནས་མཐེ་བོང་དང་། གུད་མོ་སེ་གོལ་བརྡེབས་པའོ། །རྡོ་རྗེ་ཡི་གེ་ཞེས་བྱ་བ་ནི་ཡཾ་གིས་བོན་གང་ཡིན་ཡང་ངོ་། །རྡོ་རྗི་དཀྱིལ་འཁོར་ཞེས་བྱ་བ་ནི་རླུང་གི་དཀྱིལ་འཁོར་རོ། །རྡོ་རྗེ་སྤ
འདི་ལ་གཟིགས་རོགས།

2018-11-07 14:04 UTC, rekongrabten commented on derge-tengyur-tags/016_རྒྱུད་འགྲེལ།_བ.txt
> +[267b.6]བྱ་ཞེ་ན་རྣམ་པར་དགྱེ་ཞེས་བྱ་བ་ནི་གདབ་པར་བྱ་བའོ། །ཅི་འདི་རྡུལ་ཚོན་གཉིས་པོ་ཁོ་ནས་བྲིའམ། འོན་ཀྱང་གཞན་དག་ཀྱང་དགྱེ་ཞེ་ན། ཐམས་ཅད་ཅེས་བྱ་བ་ལ་སོགས་པ་སྨོས་ཏེ། གཉིས་པོ་ཁོ་ན་མ་ཡིན་གྱི་གཞན་དག་ཀྱང་སྟེ། ཨིན
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས། (མརྐད་,མརྒད་) ཅེས་བཟོ་རོགས། ངས་བྲིས་པ་དེ་ལ་ཞིབ་ནན་གྱིས་གཟིགས་རོགས།

2018-11-07 14:04 UTC, rekongrabten commented on derge-tengyur-tags/050_རྒྱུད་འགྲེལ།_ཛི.txt
> +[182a.6]པས། །རྡོ་རྗེ་འཁོར་ལོ་རལ་གྲི་དང་། །མེ་ཡི་ཁང་པ་ཡོངས་སུ་།བཛྲ་ཙཀྲ་ཧ་ན་དང་། །ཛྭ་ལ་རཾ་ཡང་ཡོངས་སུ་བརྗོད། །གཡས་པའི་རཾ་དང་གཡོན་པའི་ཨ། །སྙིང་རྗེས་བགེགས་གསོས་བྱེར་བར་འགྱུར། །རྒྱུད་འོས་གྱུར་ནས་རང་བྱུང་གི
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-14 22:17 UTC, rekongrabten requested changes
བསྐྱར་དུ་དྲི་བ་བཞི་བཀོད་ཡོད།

2018-11-14 22:17 UTC, rekongrabten commented on derge-tengyur-tags/118_མདོ་སྡེ།_ཏི.txt
> +[68a.5]འགྲེལ་པ་ལས། དེ་ལ་ཤིན་ཏུ་དག་པ་ཞེས་བྱ་བ་ནི་མ་དག་པ་མེད་པའི་ཕྱིར་དང་། གཅིན(་རྐྱག་,སྐྱག་)དང་བྲལ་བའི་ཕྱིར་རོ། །ཤིན་ཏུ་བདེ་བ་ནི་སྡུག་བསྔལ་གྱི་ཚོར་བ་དང་། ཚོར་བ་བར་མེད་པའི་ཕྱིར་རོ། །ཤིན་ཏུ་ཁ་ན་མ་ཐོ་བ་མ
འདིའི་ཚེག་དོགས་ནང་དུ་ཤོར་འདུག

2018-11-14 22:17 UTC, rekongrabten commented on derge-tengyur-tags/158_འདུལ་བ།_ཛུ.txt
> +[226a.3]གང་ཡིན་པ་བཀག་པ་དང་། གང་སྔོན་བཀག་པ་ཡང་རྗེས་སུ་གནང་བ་ཡང་རྗེས་སུ་བཅས་པ་ཡིན་ཏེ། (དཔེན་,དཔེར་)ན་མཆིལ་ལྷམ་རྗེས་སུ་གནང་བ་མཛད་ནས་དེ་ཉིད་ཀྱི་བྱེ་བྲག་བཀག་པ་མཛད་དེ། ཐུག་ཐུག་ཟེར་བ་དང་། ཐྲིག་ཐྲིག་ཟེར་བ་བཅ
འདིའི་དོགས་རྟགས་ནང་(དཔེན་,དབེན་) འདི་ལྟར་བཀོད་རོགས།

2018-11-14 22:17 UTC, rekongrabten commented on derge-tengyur-tags/189_ཚད་མ།_ཝེ.txt
> + [1a]
འདིའི་མདུན་ལ་སྟོང་པ་ཞིག་ཤོར་འདུག

2018-11-14 22:17 UTC, rekongrabten commented on derge-tengyur-tags/204_སྣ་ཚོགས།_ཅོ.txt
> +[53b.1]ཚེ་འདི་དང་ཕྱི་མ་དང་འཆི་འཕོ་བའི་རྣམ་པའི་མིང་ལ། དྲྀཥྚི་དྷརྨཿ། ཨི་ཧ་ཏྲཿ། ཨ་མུ་ཏྲཿ། ཨི་ཧ་ཛ་ནྨཿ། ཨཱ་བ་ཏྱཱཾ། པཱ་ར་ཛནྨི་ཀཿ། ཛཱ་ཏི་བྱ་ཏི་བྲྀཏྟཾ། སཱམྤ་རཱ་ཡི་ཀཿ། སམྤ་རཱ་ཡཿ། ཛཱ་ཏི་པ་རི་བརྟྟཿ། ཙྱུ་ཏི། ཙྱ་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས། དབེན་པའི་རྣམ་པའི་མིང་ལ།  ཞེས་ཡིན་དགོས་པས། དབེན་པའི་    དང   རྣམ་པའི་  གཉིས་མ་དཔེ་གཟིགས་རོགས།

2018-11-15 11:05 UTC, drakpagyamtso commented
2018/11/15

2018-11-15 14:42 UTC, rekongrabten requested changes
འདི་གཉིས་བསྐྱར་དུ་བཟོ་རོགས།

2018-11-15 14:42 UTC, rekongrabten commented on derge-tengyur-tags/118_མདོ་སྡེ།_ཏི.txt
> +[68a.5]འགྲེལ་པ་ལས། དེ་ལ་ཤིན་ཏུ་དག་པ་ཞེས་བྱ་བ་ནི་མ་དག་པ་མེད་པའི་ཕྱིར་དང་། གཅིན(་རྐྱག་,སྐྱག་)དང་བྲལ་བའི་ཕྱིར་རོ། །ཤིན་ཏུ་བདེ་བ་ནི་སྡུག་བསྔལ་གྱི་ཚོར་བ་དང་། ཚོར་བ་བར་མེད་པའི་ཕྱིར་རོ། །ཤིན་ཏུ་ཁ་ན་མ་ཐོ་བ་མ
འདི་བཟོ་རོགས།

2018-11-15 14:42 UTC, rekongrabten commented on derge-tengyur-tags/212_སྣ་ཚོགས།_པོ.txt
> +[185b.2]པ་དང་། །འབྱང་བ་དང་ནི་སྤྱོ་བ་ལ། །བཻ་ཏེ་རཱ་ཎཱི་ཞེས་བྱ་བ། །ཡི་དགས་ཆུ་ཀླུང་སྲིན་པོའི་མ། །ཤི་ར་པཱ་ཎི་མདའ་ཡི་ལྟོང་རྐ ། །སཱ་ཡི་(ཀྱད་དད་མངས་,ཀྱང་དམངས་)འཚོ་བའོ། །སི་ལ་རི་ཎི་སྤྱོད་པ་ཡི། །དབྱེ་བ་དང་ནི་ཏ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-16 05:25 UTC, closed without merging

2018-11-23 05:21 UTC, drakpagyamtso commented
ནང་འདྲེན2018/11/23

2018-11-23 05:21 UTC, drakpagyamtso commented
དེ་རིང་

2018-11-23 05:23 UTC, drakpagyamtso commented
2018/11/23