ནང་འདྲེན།
Esukhia/derge-tengyur-old pull request #73
Opened 2018-11-03 04:07 UTC by Sangkhar

2018-11-03 13:02 UTC, rekongrabten requested changes
འདི་གཉིས་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-03 13:02 UTC, rekongrabten commented on derge-tengyur-tags/117_མདོ་སྡེ།_ཉི.txt
> +[15a.2]ནི་བྱང་ཆུབ་ཀྱི་སེམས་ཏེ་སངས་རྒྱས་ཀྱི་ཆོས་རྣམས་ཀྱི་བྱེད་པའོ། །འབྲས་བུ་ནི་ཉན་ཐོས་དང་རང་སངས་རྒྱས་དང་ཡང་དག་པར་རྫོགས་པའི་སངས་རྒྱས་ཉིད་དོ། །དེའི་རང་གི་ངོ་བོ་ཇི་ལྟ་བ་རིག་པ་ནི་སྔོན་གྱི་མཐའ་ཤེས་པའོ། །ཕྱ
འདི་ལ་ཚེག་ཅིག་ཤོར་འདུག

2018-11-03 13:02 UTC, rekongrabten commented on derge-tengyur-tags/201_གསོ་རིག_ཁོ.txt
> +[312b.3]འགགས་པའི་ནད་ལ་ནི་རླུང་འཇོམས་པའི་ཏིལ་མར་གྱིས་ལུས་ཐམས་ཅད་བསྐུ་བར་བྱ་བ་དང་། ལྟེ་བ་མན་ཆད་ལེགས་པར་དུགས་བྱ་ཞིང་རླན་སྐེ་པའི་དུགས་དང་ལུས་སྤྱིངས་པའི་དུགས་ཇི་སྐད་བཤད་པ་བཞིན་བྱའོ།།རྩ་བ་བཅུ་དང་ཨེ་རཎྜ། །བ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-09 04:53 UTC, Sangkhar commented
བཟོས་ཚར་ཡོད།

2018-11-09 04:53 UTC, closed without merging