ནང་འདྲེན།
Esukhia/derge-tengyur-old pull request #81
Opened 2018-11-08 10:48 UTC by Sermig

2018-11-08 13:46 UTC, rekongrabten requested changes
འདི་བཞི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-08 13:46 UTC, rekongrabten commented on derge-tengyur-tags/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[108b.4]དེ་བཞིན་ཤ །བུད་རྔེད་གུས་མཆོད་དེ་བཞིན་དུ། །བྷ་ག་པདྨར་ཙུལྦ་རྒོ། །བུ་ཁྱོད་སྤྲོ་བ་ཡིན་ནམ་ཅི། །ཇི་ལྟར་བདེ་བར་བུས་སྒོས་ཤིག །ཅེས་སོ། །དེས་ཀྱང་། དྲི་ཆེན་དྲི་ཆུ་སོགས་ཟ་བ། །ལྷ་མོ་ཅི་ཕྱིར་བདག་མི་སྤྲོ། །
འདི་མ་དཔེར་  ཙུམྦ་ནཾ།  ཞེས་གསལ་བས་རྣ་དེ་ནཾ་བཟོ་རོགས།

2018-11-08 13:46 UTC, rekongrabten commented on derge-tengyur-tags/212_སྣ་ཚོགས།_པོ.txt
> +[165a.3]དང་། །སྐྱེ་བོར་སྐྱེ་བ་རྣམས་ལ་ཡང་། །ཡུངས་ཀར་དང་ནི་ཀྱེ་ཏ་བ། །གྲུབ་པ་ལ་ཡང་ཨསྨྲྀ་རྔུཀ །ཨམྦི་ཀཱ་ནི་ཙུ་ཀྲི་ཀ ། སྒྱུར་པོ་དང་། དེ་བཞིན་ཏིབྱེ་ཌི་ཀཱ་དང་། །སྒྱུར་བའི་ཚོགས་ལའང་བལྟ་བར་བྱ། །ཨ་བྷ་འུཀ་ནི་ཉ་ད
ཀ ། འདིའི་རྒྱབ་ངོས་ཀྱི་སྟོང་པ་དེ་གསུབ་རོགས།

2018-11-08 13:46 UTC, rekongrabten commented on derge-tengyur-tags/212_སྣ་ཚོགས།_པོ.txt
> +[165a.6]སྨྲ་བ་དང་། །ཨཱསྣ་ཤཾ་ནི་ཉིན་མོ་དང་། །ངེས་འགྲོ་འདོར་བ་རྟག་པའི་ལས། །ཨིཀྵུ་ཀུ་ནི། བུར་ཤིང་དང་། །བྲན། བཟའ། ཉི་མའི་རིགས་མི་བདག །ཨུ་དརྐ་ནི། ཚོལ་བྱེད་དང་། །ནག་མོའི་འབྲས་དང་སྨྱོས་བྱེད་ཆང་། །ཨུ་ཕྲུ་ཀ་ན
མ་དཔེར་མྱོས་ཞེས་གསལ་བས་དེ་ལྟར་བཟོ་རོགས།

2018-11-08 13:46 UTC, rekongrabten commented on derge-tengyur-tags/212_སྣ་ཚོགས།_པོ.txt
> +[166a.6]དབང་པོ་སྣ་ཚོགས་བཤེས་གཉེན་དང་། །དྲང་སྲོང་མཛོད་ཤེས་རྣམས་ལའོ། །གཏུམ་མོ་དང་ནི་ཆུ་ཀླུང་གི། །བྱེ་བྲག་ལ་ནི་ཀཽ་ཤི་ཏཱི། །ཀྲ་མུ་ཀ་སེང་ཕྲོམ་ང་། ནི་འབྲས་སྨན་གང་ལ། །གུ་བཱ་ཀ་དི་ཚངས་པའི་ཤིང་། །པིཊྚ་ཀཱ་གཞུ་མ
མ་དཔེ་སེང་ཕྲོམ་བ། ཞེས་གསལ།

2018-11-09 04:12 UTC, Sermig commented
ལགས་སོ། བསྐྱར་བཟོས་བྱས་ནས་བསྐུར་ཡོད་ལགས།

2018-11-09 04:14 UTC, closed without merging