ལས་ཀ
Esukhia/derge-tengyur-old pull request #91
Opened 2018-11-13 11:14 UTC by gyamtso59

2018-11-13 15:05 UTC, rekongrabten requested changes
འདི་གཉིས་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-13 15:05 UTC, rekongrabten commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[161b.4]ན་ནུའི་སྒྲ་སྦྱོར་བ་ན་དྲི་བའི་ལན་བརྗོད་པ་བྱུང་བའི་སྤྱི་བརྗོད་པའི་དོན་ལ་འཇུག་པའི་བྱིངས་ལས་ལཊ་འགྱུར་ཏེ། ཨ་ཀཱརྵཱིཿ། ཀ་ཊི་མ་ཎ་བ་ཀ་ན་ནུ་ཀ་རོ་མི། ཨ་བེ་ཙསྟེ་དེ་བ་དཏྟ་ན་ནུ་བྲ་བཱི་མི། དྲིས་པའི་ལན་བརྗོད
འདི་ལ་ཁྱེད་ཀྱིས་བཟོས་པའི་བརྗོད་པ་ཕྱི་མ་གཟིགས་རོགས།   མ་དཔེར་  ཀ་ཊཾ་  ཞེས་གསལ།

2018-11-13 15:05 UTC, rekongrabten commented on derge-tengyur-tags/195_སྒྲ་མདོ།_ལེ.txt
> +[273b.2]ཤྭསི་བྱ་དྷྱ་ཏི་ཨིཎ་ཨབ་ཤྱཱ་ཨཱཏ་རྣམས་ཀྱིའོ། །དི་ཧ་ཉེ་བར་སོགས་པ་ལའོ། །ལིཧ་རོ་མྱང་བ་ལའོ། །ཤླིཥ་འཁྱུད་པ་ལའོ། །ཤྭ་ས་སྲོག་འཛིན་པ་ལའོ། །བྱ་དྷ་འཐེར་བ་ལའོ། །ཨིཎ་འགྲོ་བ་ལའོ། །ཨཏི་སྔོན་དུའོ། །ཤྱཻང་འགྲོ་བ
མདུན་གྱི་སྔགས་ཡིག་དེ་གསུབ་མི་ཉན།  དེ་ཕྲེང་འབེབས་ཀྱི་གནས་ནོར་འདུག་པས་པར་བཤུས་བྱས་ཏེ་ཐིག་ཕྲེང་གོང་མའི་མཐར་འཇོག་རོགས།

2018-11-13 16:04 UTC, ngawangtrinley commented on derge-tengyur-tags/195_སྒྲ་མདོ།_ལེ.txt
> -[273b.2]དིཧི་ལི་ཧི་ཤླིཥི་ཤྭསི་བྱ་དྷྱ་ཏི་ཨིཎ་ཨབ་ཤྱཱ་ཨཱཏ་རྣམས་ཀྱིའོ། །དི་ཧ་ཉེ་བར་སོགས་པ་ལའོ། །ལིཧ་རོ་མྱང་བ་ལའོ། །ཤླིཥ་འཁྱུད་པ་ལའོ། །ཤྭ་ས་སྲོག་འཛིན་པ་ལའོ། །བྱ་དྷ་འཐེར་བ་ལའོ། །ཨིཎ་འགྲོ་བ་ལའོ། །ཨཏི་སྔོན་ད
dsd

2018-11-13 16:04 UTC, ngawangtrinley commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> -[170b.5]ལ་སོགས་པ་འགྱུར་ཏེ། ཨཱ་ཀྲ་མ་ཏེ་སཱུཪྻཿ། ཛྱོ་ཏི་ཞེས་པ་ཅི་ཞེ་ན། ཨཱ་ཀྲ་མ་ཏི་དྷཱུ་མཿ། ཨུངྒ་ཏི་ལ་ཞེས་པ་ཅི་ཞེ་ན། ཨགྣི་རིནྡྷ་ན་མཱ་ཀྲཱ་མ་ཏི། འདི་སྟེང་དུ་བགྲོད་པས་འཕགས་པར་དགོངས་པའོ། །ཉེར་བསྒྱུར་མེད་པ་ལས
dsd

2018-11-13 16:06 UTC, ngawangtrinley commented on derge-tengyur-tags/194_སྒྲ་མདོ།_རེ.txt
> +[170b.5]ལ་སོགས་པ་འགྱུར་ཏེ། ཨཱ་ཀྲ་མ་ཏེ་སཱུཪྻཿ། ཛྱོ་ཏི་ཞེས་པ་ཅི་ཞེ་ན། ཨཱ་ཀྲ་མ་ཏི་དྷཱུ་མཿ། ཨུངྒ་ཏི་ལ་ཞེས་པ་ཅི་ཞེ་ན། ཨགྣི་རི་ནྔྷ་ནམཱ་ཀྲཱ་མ་ཏི། འདི་སྟེང་དུ་བགྲོད་པས་འཕགས་པར་དགོངས་པའོ། །ཉེར་བསྒྱུར་མེད་པ་ལས
ཀཇཧ

2018-11-14 12:56 UTC, rekongrabten approved these changes

2018-11-14 12:57 UTC, merged