ལས་ཀ2018/11/13
Esukhia/derge-tengyur-old pull request #95
Opened 2018-11-13 11:27 UTC by Sangkhar

2018-11-13 14:23 UTC, rekongrabten requested changes
འདི་བརྒྱད་པོ་བསྐྱར་དུ་ནན་ཏན་གྱིས་གཟིགས་རོགས།

2018-11-13 14:23 UTC, rekongrabten commented on derge-tengyur-tags/009_རྒྱུད་འགྲེལ།_ཉ.txt
> +ྱ[304a]
འདི་ལ་ཡང་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-13 14:23 UTC, rekongrabten commented on derge-tengyur-tags/009_རྒྱུད་འགྲེལ།_ཉ.txt
> +[326b.2]ཁམ་པོར་སོ་མ་བཏང་བ་དང་ཟན་(ཆངས་ཀྱིས་,ཆང་གིས་)ཀྱང་བྱ་བ་པར་བྱ་སྟེ། དེའི་རྗེས་ལ་ཨོཾ་སརྦ་ཏ་ཐཱ་ག་ཏ་ཀཱ་ཡ་བི་ཤོ་དྷ་ནེ་སྭཱ་ཧཱ། ཞེས་བྱ་བས་ལན་བདུན་གྱིས་བསྔགས་པའི་འདི་དང་ཏིལ་མར་དང་དཱུར་བའི་ཚོམ་བུས་རབ་ཏུ་ག
འདི་བསྐྱར་དུ་གཟིགས་རོགས།

2018-11-13 14:23 UTC, rekongrabten commented on derge-tengyur-tags/149_མངོན་པ།_ཐུ.txt
> +[24a.5]འགྲོ། །ཞེས་བྱ་བ་དང་སྦྱར་རོ། །འདིར་དཔེ་བསྟན་པའི་ཕྱིར། །ཉལ་གྲོང་ཆུ་བོས་བདས་པ་བཞིན། །ཞེས་བྱ་བ་སྨོས་ཏེ། དཔེར་ན་ཆུ་མང་པོའི་ཆུ་བོའི་ཚོགས་ཀྱིས་བག་ཕབ་སྟེ་ཉལ་བའི་གྲོང་ཅན་དང་གྲོང་བདས་ནས་ཁྱེར་བ་བཞིན་དུ་བ
བྱས་བ་  ཞེས་པའི་བ་དེ་  པ་   བཟོས་ཏེ་དོགས་རྟགས་བཀོད་རོགས།

2018-11-13 14:23 UTC, rekongrabten commented on derge-tengyur-tags/152_འདུལ་བ།_པུ.txt
> +[58a.1]པའོ་ཞེས་སྨོས་པའི་བྱེ་བྲག་ནི་འདི་ཡིན་ཏེ། རྫས་ཐ་དད་པ་ཁུར་དུ་བྱས་ནས་རྐུ་བ་ལ་ནི་ཁུར་གནས་ནས་སྤོས་ན་བརྐུས་པ་ཡིན་ནོ། །ཤིང་ཐོག་ལ་སོགས་པ་བཏུས་ནས་རྐུ་བ་ལ་ནི་ཕུང་པོ་གནས་ནས་སྤོས་ན་རྐུ་བ་ཡིན་ནོ། །རྫས་ཆུ་ལ་
འདི་ལ་དོགས་རྟགས་མི་དགོས།

2018-11-13 14:23 UTC, rekongrabten commented on derge-tengyur-tags/157_འདུལ་བ།_ཚུ.txt
> +[159a.5]བཤམས་པ་འཁྲུག་ཅེས་བྱ་བ་ནི་བཤམས་བ་གློང་པའོ། །དེར་འཇུག་པ་ནི་འགྲོ་བའོ་ཞེས་ཟེར་རོ། །འབྲུའི་ཁ་ལྟ་བུ་ཞེས་བྱ་བ་ནི་མདུན་དུ་ཡང་རུ་བ་དངར་རྒྱབ་ཏུ་ཡང་རུ་བ་དངར་ལ། དབུས་ན་རྒྱལ་པོ་འདུག་པ་སྟེ་འབྲུའི་འབྲས་བུའི
བ   འདི་  པ   ཡིན་པས་དོགས་རྟགས་བཀོད་རོགས།

2018-11-13 14:23 UTC, rekongrabten commented on derge-tengyur-tags/165_འདུལ་བ།_ལུ.txt
> +[52b.4]སྟེང་ནས་བལྟར་སྣང་བ་ནི་སྦོམ་པོ་སྟེ་ཆུའི་འོག་གི་སའི་ནང་དུ་(སྤྱིངས་,སྦྱིངས་)ཏེ་མི་སྣང་ན་ཕམ། བཀུར་#བའི་སེམས་ཀྱིས་གང་འདི་ནས་ཕྱིས་བཀུར་#བར་ནའོ། །མདོ་ལྟག་མ་ལྟར་སྦས་ཏེ་བཞག་པའི་ཚེ་མི་ཕམ་གྱི་ཕྱིས་བླངས་ཏ
འདི་ལ་དོགས་རྟགས་མི་དགོས།། རང་འཇགས་སྤྱིངས་  ཞེས་འཇོག་རོགས།

2018-11-13 14:23 UTC, rekongrabten commented on derge-tengyur-tags/170_འཁྲི་ཤིང།_ཀེ.txt
> -633. ས་མུ་ཁ་རཱ་ན་ནཿ། །ནྱ་པཱ་ར་ཡཏྟ་ཡོཿཀོ་པཱ་ཏ་པྲ་བེེ་ཤཾ་དུཥྚ་མན་ཏྲི་ཎོཿ། །གུ་ཎཱནྟ་རཾ་བ་རི་ཛྙཱ་ཡ་བྷི་རུ་ཀཾ་ཧེ་རུ་ཀཾ་ཙ་སཿ། །ཨཱ་ནི་ནཱ་ཡ་པྲ་སཱ་དྱ་ཤུ་པུ་རཱ་ཎེ་ས་ཙི་བཽ་པི་ཏུཿ། །ཏ་ཏཿཙིནྟཱ་ཀྲྀ་ཤེ་རཱ་ཛྙཱི་ཤོ་ཀཱ
འདི་གཙང་མ་བཟོ་རོགས།

2018-11-13 14:23 UTC, rekongrabten commented on derge-tengyur-tags/212_སྣ་ཚོགས།_པོ.txt
> +[167b.1]མཆོད་པ་དང་། །ཕ་མེས་སླབས་དང་པྲ་བེེ་ཎ། །པི་ཝང་བགྲེང་། དཱ་ར་ཀ་ནི་འབྱེད་པ་དང་། །བུ་རྒྱུད། བག་མའི་ལས་ལའོ། །དཱི་པ་ཀ་ནི།ངག་གི་རྒྱན། །སྒྲོན་མེ་འབར་བར་བྱེད་པའོ། །དཱི་བྱ་རྐ་ནི་གཙུག་ཕུད་དང་། །ཨ་ཛ་མོ་ད་ས
འདིའི་ཐིག་ཕྲེང་བཞི་པོ་འདི་རེ་རེ་བྱས་ནས་བསྐྱར་དུ་གཟིགས་རོགས། བརྗོད་པ་སྔ་ཕྱི་ན་ནོར་བ་མང་པོ་འདུག

2018-11-14 07:35 UTC, Sangkhar commented on derge-tengyur-tags/170_འཁྲི་ཤིང།_ཀེ.txt
> -633. ས་མུ་ཁ་རཱ་ན་ནཿ། །ནྱ་པཱ་ར་ཡཏྟ་ཡོཿཀོ་པཱ་ཏ་པྲ་བེེ་ཤཾ་དུཥྚ་མན་ཏྲི་ཎོཿ། །གུ་ཎཱནྟ་རཾ་བ་རི་ཛྙཱ་ཡ་བྷི་རུ་ཀཾ་ཧེ་རུ་ཀཾ་ཙ་སཿ། །ཨཱ་ནི་ནཱ་ཡ་པྲ་སཱ་དྱ་ཤུ་པུ་རཱ་ཎེ་ས་ཙི་བཽ་པི་ཏུཿ། །ཏ་ཏཿཙིནྟཱ་ཀྲྀ་ཤེ་རཱ་ཛྙཱི་ཤོ་ཀཱ
འཁྲི་ཤིད་ཀེ། གཙང་བ་བཟོ་ཐབས་མི་འདུག

2018-11-14 10:01 UTC, Sangkhar commented
བཟོས་ཚར་ཡོད།

2018-11-14 11:25 UTC, closed without merging